%%html

<style>
.header{
    text-align:center;
    padding:25px;
    border-radius:20px;
    background:linear-gradient(135deg,#6C63FF,#00B4DB);
    color:white;
    animation:fadeIn 2s ease-in-out;
    box-shadow:0 10px 25px rgba(0,0,0,.25);
    font-family:Arial, sans-serif;
}

.header h1{
    font-size:42px;
    margin-bottom:10px;
    animation:glow 2s infinite alternate;
}

.header h2{
    font-size:20px;
    font-weight:normal;
}

.info{
    margin-top:20px;
    display:inline-block;
    text-align:left;
    background:rgba(255,255,255,.15);
    padding:18px 30px;
    border-radius:15px;
}

@keyframes fadeIn{
    from{opacity:0;transform:translateY(-30px);}
    to{opacity:1;transform:translateY(0);}
}

@keyframes glow{
    from{text-shadow:0 0 8px white;}
    to{text-shadow:0 0 20px yellow;}
}
</style>

<div class="header">

<h1>💱 Currency Exchange API Data Extraction Using Python</h1>

<h2>REST API Integration & Currency Exchange Data Processing Project</h2>

<div class="info">

<b>👩‍💻 Prepared By:</b> Sunaina Saini <br>
<b>🎓 Course:</b> B.Tech – Artificial Intelligence & Machine Learning (AIML) <br>
<b>🏢 Internship:</b> AIML Bootcamp – CodroidHub Pvt. Ltd. <br>
<b>🌐 API Used:</b> Currency Exchange API <br>
<b>💻 Language:</b> Python <br>
<b>📚 Libraries:</b> Requests, Pandas <br>
<b>📅 Date:</b> July 2026

</div>

</div>

## Import Required Libraries
Import essential Python libraries for API requests and data processing.

In [3]:
import requests
import pandas as pd

## Define Currency Exchange API Endpoint
Specify the Exchange Rate API URL to retrieve real-time currency exchange data.

In [4]:
url="https://api.frankfurter.app/latest?from=USD&to=INR,EUR,GBP,JPY"

## Send API Request
Establish a connection with the REST API using an HTTP GET request.

In [5]:
response = requests.get(url)

## Validate API Response
Verify the request was successful by checking the HTTP status code (200 OK).

In [6]:
print(response.status_code)

200

## Retrieve JSON Data
Fetch and display the JSON response received from the API.

In [7]:
print(response.json())

{'amount': 1.0, 'base': 'USD', 'date': '2026-07-14', 'rates': {'EUR': 0.87681, 'GBP': 0.74717, 'INR': 96.2, 'JPY': 162.22}}

## Store API Response
Save the JSON response into a Python variable for further processing.

In [8]:
data= response.json()

## Iterate Through Records
Loop through each university record returned by the API.

In [9]:
for item in data:
    print(item, ":", data[item])

amount : 1.0
base : USD
date : 2026-07-14
rates : {'EUR': 0.87681, 'GBP': 0.74717, 'INR': 96.2, 'JPY': 162.22}

## Convert to Pandas DataFrame
Transform the structured data into a DataFrame for analysis.

In [10]:
df =pd.DataFrame(data)
df

     amount base        date      rates
EUR     1.0  USD  2026-07-14    0.87681
GBP     1.0  USD  2026-07-14    0.74717
INR     1.0  USD  2026-07-14   96.20000
JPY     1.0  USD  2026-07-14  162.22000

In [12]:
df.head()

     amount base        date      rates
EUR     1.0  USD  2026-07-14    0.87681
GBP     1.0  USD  2026-07-14    0.74717
INR     1.0  USD  2026-07-14   96.20000
JPY     1.0  USD  2026-07-14  162.22000

## Export Dataset
Save the processed product dataset as a CSV file for future use.

In [11]:
df.to_csv("currency_exchange.csv", index=False)

print("Dataset exported successfully!")

Dataset exported successfully!