%%html

<style>
.header{
    text-align:center;
    padding:25px;
    border-radius:20px;
    background:linear-gradient(135deg,#6C63FF,#00B4DB);
    color:white;
    animation:fadeIn 2s ease-in-out;
    box-shadow:0 10px 25px rgba(0,0,0,.25);
    font-family:Arial, sans-serif;
}

.header h1{
    font-size:42px;
    margin-bottom:10px;
    animation:glow 2s infinite alternate;
}

.header h2{
    font-size:20px;
    font-weight:normal;
}

.info{
    margin-top:20px;
    display:inline-block;
    text-align:left;
    background:rgba(255,255,255,.15);
    padding:18px 30px;
    border-radius:15px;
}

@keyframes fadeIn{
    from{opacity:0;transform:translateY(-30px);}
    to{opacity:1;transform:translateY(0);}
}

@keyframes glow{
    from{text-shadow:0 0 8px white;}
    to{text-shadow:0 0 20px yellow;}
}
</style>

<div class="header">

<h1>📝 JSONPlaceholder Posts API Data Extraction Using Python</h1>

<h2>REST API Integration & Data Processing Project</h2>

<div class="info">

<b>👩‍💻 Prepared By:</b> Sunaina Saini <br>
<b>🎓 Course:</b> B.Tech – Artificial Intelligence & Machine Learning (AIML) <br>
<b>🏢 Internship:</b> AIML Bootcamp – CodroidHub Pvt. Ltd. <br>
<b>🌐 API Used:</b> JSONPlaceholder Posts API <br>
<b>💻 Language:</b> Python <br>
<b>📚 Libraries:</b> Requests, Pandas <br>
<b>📅 Date:</b> July 2026

</div>

</div>

## Import Required Libraries
Import essential Python libraries for API requests and data processing.

In [1]:
import requests
import pandas as pd

## Define JSONPlaceholder API Endpoint
Specify the JSONPlaceholder Posts API URL to retrieve post data.

In [2]:
url="https://jsonplaceholder.typicode.com/posts"

## Send API Request
Establish a connection with the REST API using an HTTP GET request.

In [3]:
response = requests.get(url)

## Validate API Response
Verify the request was successful by checking the HTTP status code (200 OK).

In [4]:
print(response.status_code)

200

## Retrieve JSON Data
Fetch and display the JSON response received from the API.

In [5]:
data = response.json()

## Store API Response
Save the JSON data into a Python variable for further processing.

In [6]:
posts = data

## Preview API Records
Display individual post records to understand the JSON structure.

In [7]:
for post in posts[:5]:
    print(post)

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
{'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}
{'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}
{'userId': 1, 'id': 4, 'title': 'eum et est occaecati', 'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'}
{'userId': 1, 'id': 5, 'title': 'nesciunt quas odio', 'body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'}

## Extract Required Post Information
Access fields such as User ID, Post ID, Title, and Body.

In [8]:
records = []

for post in posts:
    records.append({
        "User ID": post["userId"],
        "Post ID": post["id"],
        "Title": post["title"],
        "Body": post["body"]
    })

## Create Structured Dataset
Organize the extracted post information into a structured list of dictionaries.

In [9]:
records

[{'User ID': 1,
  'Post ID': 1,
  'Title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
  'Body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'},
 {'User ID': 1,
  'Post ID': 2,
  'Title': 'qui est esse',
  'Body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'},
 {'User ID': 1,
  'Post ID': 3,
  'Title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
  'Body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'},
 {'User ID': 1,
  'Post ID': 4,
  'Title': 'eum et est occaecati',
  'Body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'},
 {'User ID': 1,
  'Post ID': 5,
  'Title': 'nesciunt quas odio',
  'Body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'},
 {'User ID': 1,
  'Post ID': 6,
  'Title': 'dolorem eum magni eos aperiam quia',
  'Body': 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae'},
 {'User ID': 1,
  'Post ID': 7,
  'Title': 'magnam facilis autem',
  'Body': 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas'},
 {'User ID': 1,
  'Post ID': 8,
  'Title': 'dolorem dolore est ipsam',
  'Body': 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae'},
 {'User ID': 1,
  'Post ID': 9,
  'Title': 'nesciunt iure omnis dolorem tempora et accusantium',
  'Body': 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas'},
 {'User ID': 1,
  'Post ID': 10,
  'Title': 'optio molestias id quia eum',
  'Body': 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error'},
 {'User ID': 2,
  'Post ID': 11,
  'Title': 'et ea vero quia laudantium autem',
  'Body': 'delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi'},
 {'User ID': 2,
  'Post ID': 12,
  'Title': 'in quibusdam tempore odit est dolorem',
  'Body': 'itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio'},
 {'User ID': 2,
  'Post ID': 13,
  'Title': 'dolorum ut in voluptas mollitia et saepe quo animi',
  'Body': 'aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam'},
 {'User ID': 2,
  'Post ID': 14,
  'Title': 'voluptatem eligendi optio',
  'Body': 'fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum'},
 {'User ID': 2,
  'Post ID': 15,
  'Title': 'eveniet quod temporibus',
  'Body': 'reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae'},
 {'User ID': 2,
  'Post ID': 16,
  'Title': 'sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio',
  'Body': 'suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta'},
 {'User ID': 2,
  'Post ID': 17,
  'Title': 'fugit voluptas sed molestias voluptatem provident',
  'Body': 'eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo'},
 {'User ID': 2,
  'Post ID': 18,
  'Title': 'voluptate et itaque vero tempora molestiae',
  'Body': 'eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam'},
 {'User ID': 2,
  'Post ID': 19,
  'Title': 'adipisci placeat illum aut reiciendis qui',
  'Body': 'illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas'},
 {'User ID': 2,
  'Post ID': 20,
  'Title': 'doloribus ad provident suscipit at',
  'Body': 'qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo'},
 {'User ID': 3,
  'Post ID': 21,
  'Title': 'asperiores ea ipsam voluptatibus modi minima quia sint',
  'Body': 'repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt'},
 {'User ID': 3,
  'Post ID': 22,
  'Title': 'dolor sint quo a velit explicabo quia nam',
  'Body': 'eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse'},
 {'User ID': 3,
  'Post ID': 23,
  'Title': 'maxime id vitae nihil numquam',
  'Body': 'veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis'},
 {'User ID': 3,
  'Post ID': 24,
  'Title': 'autem hic labore sunt dolores incidunt',
  'Body': 'enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt'},
 {'User ID': 3,
  'Post ID': 25,
  'Title': 'rem alias distinctio quo quis',
  'Body': 'ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio'},
 {'User ID': 3,
  'Post ID': 26,
  'Title': 'est et quae odit qui non',
  'Body': 'similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero'},
 {'User ID': 3,
  'Post ID': 27,
  'Title': 'quasi id et eos tenetur aut quo autem',
  'Body': 'eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur'},
 {'User ID': 3,
  'Post ID': 28,
  'Title': 'delectus ullam et corporis nulla voluptas sequi',
  'Body': 'non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum'},
 {'User ID': 3,
  'Post ID': 29,
  'Title': 'iusto eius quod necessitatibus culpa ea',
  'Body': 'odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores'},
 {'User ID': 3,
  'Post ID': 30,
  'Title': 'a quo magni similique perferendis',
  'Body': 'alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia'},
 {'User ID': 4,
  'Post ID': 31,
  'Title': 'ullam ut quidem id aut vel consequuntur',
  'Body': 'debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae'},
 {'User ID': 4,
  'Post ID': 32,
  'Title': 'doloremque illum aliquid sunt',
  'Body': 'deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime'},
 {'User ID': 4,
  'Post ID': 33,
  'Title': 'qui explicabo molestiae dolorem',
  'Body': 'rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod'},
 {'User ID': 4,
  'Post ID': 34,
  'Title': 'magnam ut rerum iure',
  'Body': 'ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis'},
 {'User ID': 4,
  'Post ID': 35,
  'Title': 'id nihil consequatur molestias animi provident',
  'Body': 'nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit'},
 {'User ID': 4,
  'Post ID': 36,
  'Title': 'fuga nam accusamus voluptas reiciendis itaque',
  'Body': 'ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore'},
 {'User ID': 4,
  'Post ID': 37,
  'Title': 'provident vel ut sit ratione est',
  'Body': 'debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui'},
 {'User ID': 4,
  'Post ID': 38,
  'Title': 'explicabo et eos deleniti nostrum ab id repellendus',
  'Body': 'animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure'},
 {'User ID': 4,
  'Post ID': 39,
  'Title': 'eos dolorem iste accusantium est eaque quam',
  'Body': 'corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex'},
 {'User ID': 4,
  'Post ID': 40,
  'Title': 'enim quo cumque',
  'Body': 'ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam'},
 {'User ID': 5,
  'Post ID': 41,
  'Title': 'non est facere',
  'Body': 'molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe'},
 {'User ID': 5,
  'Post ID': 42,
  'Title': 'commodi ullam sint et excepturi error explicabo praesentium voluptas',
  'Body': 'odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut'},
 {'User ID': 5,
  'Post ID': 43,
  'Title': 'eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis',
  'Body': 'similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis'},
 {'User ID': 5,
  'Post ID': 44,
  'Title': 'optio dolor molestias sit',
  'Body': 'temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae'},
 {'User ID': 5,
  'Post ID': 45,
  'Title': 'ut numquam possimus omnis eius suscipit laudantium iure',
  'Body': 'est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem'},
 {'User ID': 5,
  'Post ID': 46,
  'Title': 'aut quo modi neque nostrum ducimus',
  'Body': 'voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid'},
 {'User ID': 5,
  'Post ID': 47,
  'Title': 'quibusdam cumque rem aut deserunt',
  'Body': 'voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate'},
 {'User ID': 5,
  'Post ID': 48,
  'Title': 'ut voluptatem illum ea doloribus itaque eos',
  'Body': 'voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit'},
 {'User ID': 5,
  'Post ID': 49,
  'Title': 'laborum non sunt aut ut assumenda perspiciatis voluptas',
  'Body': 'inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut'},
 {'User ID': 5,
  'Post ID': 50,
  'Title': 'repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem',
  'Body': 'error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur'},
 {'User ID': 6,
  'Post ID': 51,
  'Title': 'soluta aliquam aperiam consequatur illo quis voluptas',
  'Body': 'sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem'},
 {'User ID': 6,
  'Post ID': 52,
  'Title': 'qui enim et consequuntur quia animi quis voluptate quibusdam',
  'Body': 'iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum'},
 {'User ID': 6,
  'Post ID': 53,
  'Title': 'ut quo aut ducimus alias',
  'Body': 'minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique'},
 {'User ID': 6,
  'Post ID': 54,
  'Title': 'sit asperiores ipsam eveniet odio non quia',
  'Body': 'totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia'},
 {'User ID': 6,
  'Post ID': 55,
  'Title': 'sit vel voluptatem et non libero',
  'Body': 'debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit'},
 {'User ID': 6,
  'Post ID': 56,
  'Title': 'qui et at rerum necessitatibus',
  'Body': 'aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi'},
 {'User ID': 6,
  'Post ID': 57,
  'Title': 'sed ab est est',
  'Body': 'at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est'},
 {'User ID': 6,
  'Post ID': 58,
  'Title': 'voluptatum itaque dolores nisi et quasi',
  'Body': 'veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam'},
 {'User ID': 6,
  'Post ID': 59,
  'Title': 'qui commodi dolor at maiores et quis id accusantium',
  'Body': 'perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt'},
 {'User ID': 6,
  'Post ID': 60,
  'Title': 'consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere',
  'Body': 'asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis'},
 {'User ID': 7,
  'Post ID': 61,
  'Title': 'voluptatem doloribus consectetur est ut ducimus',
  'Body': 'ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit'},
 {'User ID': 7,
  'Post ID': 62,
  'Title': 'beatae enim quia vel',
  'Body': 'enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio'},
 {'User ID': 7,
  'Post ID': 63,
  'Title': 'voluptas blanditiis repellendus animi ducimus error sapiente et suscipit',
  'Body': 'enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta'},
 {'User ID': 7,
  'Post ID': 64,
  'Title': 'et fugit quas eum in in aperiam quod',
  'Body': 'id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui'},
 {'User ID': 7,
  'Post ID': 65,
  'Title': 'consequatur id enim sunt et et',
  'Body': 'voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur'},
 {'User ID': 7,
  'Post ID': 66,
  'Title': 'repudiandae ea animi iusto',
  'Body': 'officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe'},
 {'User ID': 7,
  'Post ID': 67,
  'Title': 'aliquid eos sed fuga est maxime repellendus',
  'Body': 'reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae'},
 {'User ID': 7,
  'Post ID': 68,
  'Title': 'odio quis facere architecto reiciendis optio',
  'Body': 'magnam molestiae perferendis quisquam\nqui cum reiciendis\nquaerat animi amet hic inventore\nea quia deleniti quidem saepe porro velit'},
 {'User ID': 7,
  'Post ID': 69,
  'Title': 'fugiat quod pariatur odit minima',
  'Body': 'officiis error culpa consequatur modi asperiores et\ndolorum assumenda voluptas et vel qui aut vel rerum\nvoluptatum quisquam perspiciatis quia rerum consequatur totam quas\nsequi commodi repudiandae asperiores et saepe a'},
 {'User ID': 7,
  'Post ID': 70,
  'Title': 'voluptatem laborum magni',
  'Body': 'sunt repellendus quae\nest asperiores aut deleniti esse accusamus repellendus quia aut\nquia dolorem unde\neum tempora esse dolore'},
 {'User ID': 8,
  'Post ID': 71,
  'Title': 'et iusto veniam et illum aut fuga',
  'Body': 'occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis'},
 {'User ID': 8,
  'Post ID': 72,
  'Title': 'sint hic doloribus consequatur eos non id',
  'Body': 'quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit'},
 {'User ID': 8,
  'Post ID': 73,
  'Title': 'consequuntur deleniti eos quia temporibus ab aliquid at',
  'Body': 'voluptatem cumque tenetur consequatur expedita ipsum nemo quia explicabo\naut eum minima consequatur\ntempore cumque quae est et\net in consequuntur voluptatem voluptates aut'},
 {'User ID': 8,
  'Post ID': 74,
  'Title': 'enim unde ratione doloribus quas enim ut sit sapiente',
  'Body': 'odit qui et et necessitatibus sint veniam\nmollitia amet doloremque molestiae commodi similique magnam et quam\nblanditiis est itaque\nquo et tenetur ratione occaecati molestiae tempora'},
 {'User ID': 8,
  'Post ID': 75,
  'Title': 'dignissimos eum dolor ut enim et delectus in',

## Convert to Pandas DataFrame
Transform the structured data into a DataFrame for analysis.

In [10]:
df = pd.DataFrame(data)
df

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

## Preview Dataset
Display the first few rows of the processed dataset.

In [11]:
df.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

## Export Dataset
Save the processed dataset as a CSV file for future use.

In [12]:
df.to_csv("posts_dataset.csv", index=False)
print("Dataset exported successfully!")

Dataset exported successfully!