%%html

<style>
.header{
    text-align:center;
    padding:25px;
    border-radius:20px;
    background:linear-gradient(135deg,#6C63FF,#00B4DB);
    color:white;
    animation:fadeIn 2s ease-in-out;
    box-shadow:0 10px 25px rgba(0,0,0,.25);
    font-family:Arial, sans-serif;
}

.header h1{
    font-size:40px;
    margin-bottom:10px;
    animation:glow 2s infinite alternate;
}

.header h2{
    font-size:20px;
    font-weight:normal;
    margin-bottom:18px;
}

.info{
    margin-top:15px;
    display:inline-block;
    text-align:left;
    background:rgba(255,255,255,.15);
    padding:18px 30px;
    border-radius:15px;
    line-height:1.8;
    font-size:16px;
}

@keyframes fadeIn{
    from{
        opacity:0;
        transform:translateY(-30px);
    }
    to{
        opacity:1;
        transform:translateY(0);
    }
}

@keyframes glow{
    from{
        text-shadow:0 0 8px white;
    }
    to{
        text-shadow:0 0 20px #FFD700;
    }
}
</style>

<div class="header">

<h1>📚 Static Web Scraping Using Python & BeautifulSoup</h1>

<h2>Extracting Goodreads Quotes Data from a Static Website</h2>

<div class="info">

<b>👩‍💻 Prepared By:</b> Sunaina Saini <br>
<b>🎓 Course:</b> B.Tech – Artificial Intelligence & Machine Learning (AIML) <br>
<b>🏢 Internship:</b> AIML Bootcamp – CodroidHub Pvt. Ltd. <br>
<b>🌐 Website:</b> Goodreads Quotes (Static Website) <br>
<b>🕸️ Scraping Type:</b> Static Web Scraping <br>
<b>💻 Language:</b> Python <br>
<b>📚 Libraries:</b> Requests, BeautifulSoup4, Pandas <br>
<b>📂 Output:</b> CSV Dataset of Quotes, Authors & Tags <br>
<b>📅 Date:</b> July 2026

</div>

</div>

# Import Required Libraries

Import all the libraries needed for web scraping, data handling, and exporting the scraped data.

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

# Define the Target Website

Specify the URL of the webpage that will be scraped.

In [2]:
url = 'https://www.goodreads.com/quotes'

# Add Browser Headers


Provide request headers so the website recognizes the request as coming from a real web browser.

In [3]:
HEADERS = ({'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

})

# Send HTTP Request

Send a GET request to the website and retrieve its HTML content.

In [4]:
response = requests.get(url,headers = HEADERS)

# Check the Response


Verify whether the request was successful by checking the HTTP status code.

In [5]:
print(response.status_code)

200

# Inspect Response Content


Check the type of the downloaded content.

In [6]:
type(response.content)

bytes

# Parse the HTML

Convert the HTML into a BeautifulSoup object for easier navigation.

In [7]:
soup = BeautifulSoup(response.content,"html.parser")

# Preview the HTML Structure


Display the parsed HTML structure for understanding the webpage layout.

In [8]:
soup

<!DOCTYPE html>

<html class="desktop withSiteHeaderTopFullImage">
<head>
<title>Popular Quotes</title>
<meta content="Popular quotes from Goodreads members. Oscar Wilde: ‘Be yourself; everyone else is already taken.’, Marilyn Monroe: ‘I'm selfish, impatient and a little ..." name="description"/>
<meta content="telephone=no" name="format-detection"/>
<link href="https://www.goodreads.com/quotes" rel="canonical"/>
<!-- * Copied from https://info.analytics.a2z.com/#/docs/data_collection/csa/onboard */ -->
<script>
  //<![CDATA[
    !function(){function n(n,t){var r=i(n);return t&&(r=r("instance",t)),r}var r=[],c=0,i=function(t){return function(){var n=c++;return r.push([t,[].slice.call(arguments,0),n,{time:Date.now()}]),i(n)}};n._s=r,this.csa=n}();

    if (window.csa) {
      window.csa("Config", {
        "Application": "GoodreadsMonolith",
        "Events.SushiEndpoint": "https://unagi.amazon.com/1/events/com.amazon.csm.csa.prod",
        "Events.Namespace": "csa",
        "CacheDetection.RequestID": "3FNWDWKKB1921GSFFZ7Q",
        "ObfuscatedMarketplaceId": "A1PQBFHBHS6YH1"
      });

      window.csa("Events")("setEntity", {
        session: { id: "628-6692494-3521834" },
        page: {requestId: "3FNWDWKKB1921GSFFZ7Q", meaningful: "interactive"}
      });
    }

    var e = document.createElement("script"); e.src = "https://m.media-amazon.com/images/I/41mrkPcyPwL.js"; document.head.appendChild(e);
  //]]>
</script>
<script type="text/javascript">
        if (window.Mobvious === undefined) {
          window.Mobvious = {};
        }
        window.Mobvious.device_type = 'desktop';
        </script>
<script src="https://s.gr-assets.com/assets/webfontloader-c578336baa6da50a1f0d46c5164fc699.js"></script>
<script>
//<![CDATA[

  WebFont.load({
    classes: false,
    custom: {
      families: ["Lato:n4,n7,i4", "Merriweather:n4,n7,i4"],
      urls: ["https://s.gr-assets.com/assets/gr/fonts-cf24b9fb9a07049b1cf20d385104c1a8.css"]
    }
  });

//]]>
</script>
<link href="https://s.gr-assets.com/assets/goodreads-57bcf22ed25e8ed5728f9d3075a2f4b6.css" media="all" rel="stylesheet"/>
<link href="https://s.gr-assets.com/assets/common_images-dcd3965f0535a83a75a402676f031c66.css" media="screen" rel="stylesheet"/>
<script type="text/javascript">
    window.CKEDITOR_BASEPATH = 'https://s.gr-assets.com/assets/ckeditor/';
  </script>
<script src="https://s.gr-assets.com/assets/desktop/libraries-c07ee2e4be9ade4a64546b3ec60b523b.js"></script>
<script src="https://s.gr-assets.com/assets/application-4c83f04f97af870ab7d547e3954de913.js"></script>
<script>
  //<![CDATA[
    var gptAdSlots = gptAdSlots || [];
    var googletag = googletag || {};
    googletag.cmd = googletag.cmd || [];
    (function() {
      var gads = document.createElement("script");
      gads.async = true;
      gads.type = "text/javascript";
      var useSSL = "https:" == document.location.protocol;
      gads.src = (useSSL ? "https:" : "http:") +
      "//securepubads.g.doubleclick.net/tag/js/gpt.js";
      var node = document.getElementsByTagName("script")[0];
      node.parentNode.insertBefore(gads, node);
    })();
    // page settings
  //]]>
</script>
<script>
  //<![CDATA[
    googletag.cmd.push(function() {
      googletag.pubads().setTargeting("sid", "osid.da0a0d41cbb3f5a4d5bf3b41541a0649");
    googletag.pubads().setTargeting("grsession", "osid.da0a0d41cbb3f5a4d5bf3b41541a0649");
    googletag.pubads().setTargeting("surface", "desktop");
    googletag.pubads().setTargeting("signedin", "false");
    googletag.pubads().setTargeting("gr_author", "false");
    googletag.pubads().setTargeting("author", []);
    googletag.pubads().setTargeting("shelf", ["life","love","inspirational"]);
    googletag.pubads().setTargeting("tags", ["4722","4125","210"]);
    googletag.pubads().setTargeting("gtargeting", "1");
    googletag.pubads().setTargeting("resource", "quotes_index");
      googletag.pubads().enableAsyncRendering();
      googletag.pubads().enableSingleRequest();
      googletag.pubads().collapseEmptyDivs(true);
      googletag.pubads().disableInitialLoad();
      if (false) {
        googletag.setConfig({
          safeFrame: {
            forceSafeFrame: true,
            sandbox: true
          }
        });
      }
      googletag.enableServices();
    });
  //]]>
</script>
<script>
  //<![CDATA[
    ! function(a9, a, p, s, t, A, g) {
      if (a[a9]) return;

      function q(c, r) {
        a[a9]._Q.push([c, r])
      }
      a[a9] = {
      init: function() {
        q("i", arguments)
      },
      fetchBids: function() {
        q("f", arguments)
      },
      setDisplayBids: function() {},
        _Q: []
      };
      A = p.createElement(s);
      A.async = !0;
      A.src = t;
      g = p.getElementsByTagName(s)[0];
      g.parentNode.insertBefore(A, g)
    }("apstag", window, document, "script", "//c.amazon-adsystem.com/aax2/apstag.js");

    apstag.init({
      pubID: '3211', adServer: 'googletag', bidTimeout: 4e3, deals: true, params: { aps_privacy: '1YN' }
    });
  //]]>
</script>
<meta content="authenticity_token" name="csrf-param"/>
<meta content="1fVrkRcP91r5Ogax86OHwOVq4kiA1bdgzmtitg1WX6CLhYsaZNlfqkA2Xop8+gGkJK4N71A3J9aWsFzh59U1kw==" name="csrf-token"/>
<meta content="3FNWDWKKB1921GSFFZ7Q" name="request-id"/>
<script defer="defer" src="https://s.gr-assets.com/assets/react_client_side/external_dependencies-ebf499aa1f.js"></script>
<script defer="defer" src="https://s.gr-assets.com/assets/react_client_side/site_header-5a008262f2.js"></script>
<script defer="defer" src="https://s.gr-assets.com/assets/react_client_side/custom_react_ujs-b1220d5e0a4820e90b905c302fc5cb52.js"></script>
<link href="/opensearch.xml" rel="search" title="Goodreads" type="application/opensearchdescription+xml"/>
<meta content="Popular quotes from Goodreads members. Oscar Wilde: ‘Be yourself; everyone else is already taken.’, Marilyn Monroe: ‘I'm selfish, impatient and a little ..." name="description"/>
<meta content="summary" name="twitter:card"/>
<meta content="@goodreads" name="twitter:site"/>
<meta content="Popular Quotes" name="twitter:title"/>
<meta content="Popular quotes from Goodreads members. Oscar Wilde: ‘Be yourself; everyone else is already taken.’, Marilyn Monroe: ‘I'm selfish, impatient and a little ..." name="twitter:description"/>
<meta content="cEf8XOH0pulh1aYQeZ1gkXHsQ3dMPSyIGGYqmF53690=" name="verify-v1"/>
<meta content="PfFjeZ9OK1RrUrKlmAPn_iZJ_vgHaZO1YQ-QlG2VsJs" name="google-site-verification"/>
<meta content="app-id=355833469" name="apple-itunes-app"/>
</head>
<body class="">
<div data-react-class="ReactComponents.StoresInitializer" data-react-props="{}"><noscript data-react-checksum="-1189277317" data-reactid=".132wivoygae"></noscript></div>
<div class="content" id="bodycontainer">
<script>
  //<![CDATA[
    var initializeGrfb = function() {
      $grfb.initialize({
        appId: "2415071772"
      });
    };
    if (typeof $grfb !== "undefined") {
      initializeGrfb();
    } else {
      window.addEventListener("DOMContentLoaded", function() {
        if (typeof $grfb !== "undefined") {
          initializeGrfb();
        }
      });
    }
  //]]>
</script>
<script>
  //<![CDATA[
    function loadScript(url, callback) {
      var script = document.createElement("script");
      script.type = "text/javascript";

      if (script.readyState) {  //Internet Explorer
          script.onreadystatechange = function() {
            if (script.readyState == "loaded" ||
                    script.readyState == "complete") {
              script.onreadystatechange = null;
              callback();
            }
          };
      } else {  //Other browsers
        script.onload = function() {
          callback();
        };
      }

      script.src = url;
      document.getElementsByTagName("head")[0].appendChild(script);
    }

    function initAppleId() {
      AppleID.auth.init({
        clientId : 'com.goodreads.app',
        scope : 'name email',
        redirectURI: 'https://www.goodreads.com/apple_users/sign_in_with_apple_web',
        state: 'apple_oauth_state_68d9ef26-9b43-418f-9ac8-fd60abb49e80'
      });
    }

    var initializeSiwa = function() {
      var APPLE_SIGN_IN_JS_URL =  "https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js"
      loadScript(APPLE_SIGN_IN_JS_URL, initAppleId);
    };
    if (typeof AppleID !== "undefined") {
      initAppleId();
    } else {
      initializeSiwa();
    }
  //]]>
</script>
<div class="siteHeader">

In [9]:
print(soup.prettify())

<!DOCTYPE html>
<html class="desktop withSiteHeaderTopFullImage">
 <head>
  <title>
   Popular Quotes
  </title>
  <meta content="Popular quotes from Goodreads members. Oscar Wilde: ‘Be yourself; everyone else is already taken.’, Marilyn Monroe: ‘I'm selfish, impatient and a little ..." name="description"/>
  <meta content="telephone=no" name="format-detection"/>
  <link href="https://www.goodreads.com/quotes" rel="canonical"/>
  <!-- * Copied from https://info.analytics.a2z.com/#/docs/data_collection/csa/onboard */ -->
  <script>
   //<![CDATA[
    !function(){function n(n,t){var r=i(n);return t&&(r=r("instance",t)),r}var r=[],c=0,i=function(t){return function(){var n=c++;return r.push([t,[].slice.call(arguments,0),n,{time:Date.now()}]),i(n)}};n._s=r,this.csa=n}();

    if (window.csa) {
      window.csa("Config", {
        "Application": "GoodreadsMonolith",
        "Events.SushiEndpoint": "https://unagi.amazon.com/1/events/com.amazon.csm.csa.prod",
        "Events.Namespace": "csa",
        "CacheDetection.RequestID": "3FNWDWKKB1921GSFFZ7Q",
        "ObfuscatedMarketplaceId": "A1PQBFHBHS6YH1"
      });

      window.csa("Events")("setEntity", {
        session: { id: "628-6692494-3521834" },
        page: {requestId: "3FNWDWKKB1921GSFFZ7Q", meaningful: "interactive"}
      });
    }

    var e = document.createElement("script"); e.src = "https://m.media-amazon.com/images/I/41mrkPcyPwL.js"; document.head.appendChild(e);
  //]]>
  </script>
  <script type="text/javascript">
   if (window.Mobvious === undefined) {
          window.Mobvious = {};
        }
        window.Mobvious.device_type = 'desktop';
  </script>
  <script src="https://s.gr-assets.com/assets/webfontloader-c578336baa6da50a1f0d46c5164fc699.js">
  </script>
  <script>
   //<![CDATA[

  WebFont.load({
    classes: false,
    custom: {
      families: ["Lato:n4,n7,i4", "Merriweather:n4,n7,i4"],
      urls: ["https://s.gr-assets.com/assets/gr/fonts-cf24b9fb9a07049b1cf20d385104c1a8.css"]
    }
  });

//]]>
  </script>
  <link href="https://s.gr-assets.com/assets/goodreads-57bcf22ed25e8ed5728f9d3075a2f4b6.css" media="all" rel="stylesheet"/>
  <link href="https://s.gr-assets.com/assets/common_images-dcd3965f0535a83a75a402676f031c66.css" media="screen" rel="stylesheet"/>
  <script type="text/javascript">
   window.CKEDITOR_BASEPATH = 'https://s.gr-assets.com/assets/ckeditor/';
  </script>
  <script src="https://s.gr-assets.com/assets/desktop/libraries-c07ee2e4be9ade4a64546b3ec60b523b.js">
  </script>
  <script src="https://s.gr-assets.com/assets/application-4c83f04f97af870ab7d547e3954de913.js">
  </script>
  <script>
   //<![CDATA[
    var gptAdSlots = gptAdSlots || [];
    var googletag = googletag || {};
    googletag.cmd = googletag.cmd || [];
    (function() {
      var gads = document.createElement("script");
      gads.async = true;
      gads.type = "text/javascript";
      var useSSL = "https:" == document.location.protocol;
      gads.src = (useSSL ? "https:" : "http:") +
      "//securepubads.g.doubleclick.net/tag/js/gpt.js";
      var node = document.getElementsByTagName("script")[0];
      node.parentNode.insertBefore(gads, node);
    })();
    // page settings
  //]]>
  </script>
  <script>
   //<![CDATA[
    googletag.cmd.push(function() {
      googletag.pubads().setTargeting("sid", "osid.da0a0d41cbb3f5a4d5bf3b41541a0649");
    googletag.pubads().setTargeting("grsession", "osid.da0a0d41cbb3f5a4d5bf3b41541a0649");
    googletag.pubads().setTargeting("surface", "desktop");
    googletag.pubads().setTargeting("signedin", "false");
    googletag.pubads().setTargeting("gr_author", "false");
    googletag.pubads().setTargeting("author", []);
    googletag.pubads().setTargeting("shelf", ["life","love","inspirational"]);
    googletag.pubads().setTargeting("tags", ["4722","4125","210"]);
    googletag.pubads().setTargeting("gtargeting", "1");
    googletag.pubads().setTargeting("resource", "quotes_index");
      googletag.pubads().enableAsyncRendering();
      googletag.pubads().enableSingleRequest();
      googletag.pubads().collapseEmptyDivs(true);
      googletag.pubads().disableInitialLoad();
      if (false) {
        googletag.setConfig({
          safeFrame: {
            forceSafeFrame: true,
            sandbox: true
          }
        });
      }
      googletag.enableServices();
    });
  //]]>
  </script>
  <script>
   //<![CDATA[
    ! function(a9, a, p, s, t, A, g) {
      if (a[a9]) return;

      function q(c, r) {
        a[a9]._Q.push([c, r])
      }
      a[a9] = {
      init: function() {
        q("i", arguments)
      },
      fetchBids: function() {
        q("f", arguments)
      },
      setDisplayBids: function() {},
        _Q: []
      };
      A = p.createElement(s);
      A.async = !0;
      A.src = t;
      g = p.getElementsByTagName(s)[0];
      g.parentNode.insertBefore(A, g)
    }("apstag", window, document, "script", "//c.amazon-adsystem.com/aax2/apstag.js");

    apstag.init({
      pubID: '3211', adServer: 'googletag', bidTimeout: 4e3, deals: true, params: { aps_privacy: '1YN' }
    });
  //]]>
  </script>
  <meta content="authenticity_token" name="csrf-param"/>
  <meta content="1fVrkRcP91r5Ogax86OHwOVq4kiA1bdgzmtitg1WX6CLhYsaZNlfqkA2Xop8+gGkJK4N71A3J9aWsFzh59U1kw==" name="csrf-token"/>
  <meta content="3FNWDWKKB1921GSFFZ7Q" name="request-id"/>
  <script defer="defer" src="https://s.gr-assets.com/assets/react_client_side/external_dependencies-ebf499aa1f.js">
  </script>
  <script defer="defer" src="https://s.gr-assets.com/assets/react_client_side/site_header-5a008262f2.js">
  </script>
  <script defer="defer" src="https://s.gr-assets.com/assets/react_client_side/custom_react_ujs-b1220d5e0a4820e90b905c302fc5cb52.js">
  </script>
  <link href="/opensearch.xml" rel="search" title="Goodreads" type="application/opensearchdescription+xml"/>
  <meta content="Popular quotes from Goodreads members. Oscar Wilde: ‘Be yourself; everyone else is already taken.’, Marilyn Monroe: ‘I'm selfish, impatient and a little ..." name="description"/>
  <meta content="summary" name="twitter:card"/>
  <meta content="@goodreads" name="twitter:site"/>
  <meta content="Popular Quotes" name="twitter:title"/>
  <meta content="Popular quotes from Goodreads members. Oscar Wilde: ‘Be yourself; everyone else is already taken.’, Marilyn Monroe: ‘I'm selfish, impatient and a little ..." name="twitter:description"/>
  <meta content="cEf8XOH0pulh1aYQeZ1gkXHsQ3dMPSyIGGYqmF53690=" name="verify-v1"/>
  <meta content="PfFjeZ9OK1RrUrKlmAPn_iZJ_vgHaZO1YQ-QlG2VsJs" name="google-site-verification"/>
  <meta content="app-id=355833469" name="apple-itunes-app"/>
 </head>
 <body class="">
  <div data-react-class="ReactComponents.StoresInitializer" data-react-props="{}">
   <noscript data-react-checksum="-1189277317" data-reactid=".132wivoygae">
   </noscript>
  </div>
  <div class="content" id="bodycontainer">
   <script>
    //<![CDATA[
    var initializeGrfb = function() {
      $grfb.initialize({
        appId: "2415071772"
      });
    };
    if (typeof $grfb !== "undefined") {
      initializeGrfb();
    } else {
      window.addEventListener("DOMContentLoaded", function() {
        if (typeof $grfb !== "undefined") {
          initializeGrfb();
        }
      });
    }
  //]]>
   </script>
   <script>
    //<![CDATA[
    function loadScript(url, callback) {
      var script = document.createElement("script");
      script.type = "text/javascript";

      if (script.readyState) {  //Internet Explorer
          script.onreadystatechange = function() {
            if (script.readyState == "loaded" ||
                    script.readyState == "complete") {
              script.onreadystatechange = null;
              callback();
            }
          };
      } else {  //Other browsers
        script.onload = function() {
          callback();
        };
      }

      script.src = url;
      document.getElementsByTagName("head")[0].appendChild(script);
    }

    function initAppleId() {
      AppleID.auth.init({
        clientId : 'com.goodreads.app',
        scope : 'name email',
        redirectURI: 'https://www.goodreads.com/apple_users/sign_in_with_apple_web',
        state: 'apple_oauth_state_68d9ef26-9b43-418f-9ac8-fd60abb49e80'
      });
    }

    var initializeSiwa = function() {
      var APPLE_SIGN_IN_JS_URL =  "https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js"
      loadScript(APPLE_SIGN_IN_JS_URL, initAppleId);
    };
    if (typeof AppleID !== "undefined") {
      initAppleId();
    } else {
      initializeSiwa();
    }
  //]]>
   </script>
   <div class="siteHeader">
    <div data-react-class="ReactComponents.HeaderStoreConnector" data-react-props='{"myBooksUrl":"/review/list?ref=nav_mybooks","browseUrl":"/book?ref=nav_brws","recommendationsUrl":"/recommendations?ref=nav_brws_recs","choiceAwardsUrl":"/choiceawards?ref=nav_brws_gca","genresIndexUrl":"/genres?ref=nav_brws_genres","giveawayUrl":"/giveaway?ref=nav_brws_giveaways","exploreUrl":"/book?ref=nav_brws_explore","homeUrl":"/?ref=nav_home","listUrl":"/list?ref=nav_brws_lists","newsUrl":"/news?ref=nav_brws_news","communityUrl":"/group?ref=nav_comm","groupsUrl":"/group?ref=nav_comm_groups","quotesUrl":"/quotes?ref=nav_comm_quotes","featuredAskAuthorUrl":"/ask_the_author?ref=nav_comm_askauthor","autocompleteUrl":"/book/auto_complete","defaultLogoActionUrl":"/","topFullImage":{"clickthroughUrl":"https://www.goodreads.com/blog/show/3138?ref=top_mys_thrill_horror_eb","altText":"Dark \u0026 Twisty","backgroundColor":"#626BA9","xs":{"1x":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/siteheaderbannerimages/1782723615i/735.jpg","2x":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/siteheaderbannerimages/1782723620i/736.jpg"},"md":{"1x":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/siteheaderbannerimages/1782723600i/733.jpg","2x":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/siteheaderbannerimages/1782723608i/734.jpg"}},"logo":{"clickthroughUrl":"/","altText":"Goodreads Home"},"searchPath":"/search","iOSDownloadUrl":"https://itunes.apple.com/app/apple-store/id355833469?pt=325668\u0026ct=Mobile%20Homepage\u0026mt=8","androidDownloadUrl":"https://play.google.com/store/apps/details?id=com.goodreads\u0026utm_source=mw_header\u0026pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1","showAppDownloadButton":true,"newReleasesUrl":"/book/popular_by_date/2026/7?ref=nav_brws_newrels","signInUrl":"/user/sign_in","signUpUrl":"/user/sign_up","signInWithReturnUrl":true,"deployServices":[],"defaultLogoAltText":"Goodreads Home","mobviousDeviceType":"desktop"}'>
     <header data-react-checksum="-382419168" data-reactid=".j5559a8z54">
      <div class="siteHeader__topFullImageContainer" data-reactid=".j5559a8z54.0" style="background-color:#626BA9;">
       <a class="siteHeader__topFullImageLink" data-reactid=".j5559a8z54.0.0" href="https://www.goodreads.com/blog/show/3138?ref=top_mys_thrill_horror_eb">
        <picture data-reactid=".j5559a8z54.0.0.0">
         <source data-reactid=".j5559a8z54.0.0.0.0" media="(min-width: 768px)" srcset="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/siteheaderbannerimages/1782723600i/733.jpg 1x, https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/siteheaderbannerimages/1782723608i/734.jpg 2x"/>
         <img alt="Dark &amp; Twisty" class="siteHeader__topFullImage" data-reactid=".j5559a8z54.0.0.0.1" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/siteheaderbannerimages/1782723615i/735.jpg" srcset="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/siteheaderbannerimages/1782723620i/736.jpg 2x"/>
        </picture>
       </a>
      </div>
      <div class="siteHeader__topLine gr-box gr-box--withShadow" data-reactid=".j5559a8z54.1">
       <div class="siteHeader__contents" data-reactid=".j5559a8z54.1.0">
        <div class="siteHeader__topLevelItem siteHeader__topLevelItem--searchIcon" data-reactid=".j5559a8z54.1.0.0">
         <button aria-label="Toggle search" class="siteHeader__searchIcon gr-iconButton" data-reactid=".j5559a8z54.1.0.0.0" data-ux-click="true" type="button">
         </button>
        </div>
        <a aria-label="Goodreads Home" class="siteHeader__logo" data-reactid=".j5559a8z54.1.0.1" href="/" title="Goodreads Home">
        </a>
        <nav class="siteHeader__primaryNavInline" data-reactid=".j5559a8z54.1.0.2">
         <ul class="siteHeader__menuList" data-reactid=".j5559a8z54.1.0.2.0" role="menu">
          <li class="siteHeader__topLevelItem siteHeader__topLevelItem--home" data-reactid=".j5559a8z54.1.0.2.0.0">
           <a class="siteHeader__topLevelLink" data-reactid=".j5559a8z54.1.0.2.0.0.0" href="/?ref=nav_home">
            Home
           </a>
          </li>
          <li class="siteHeader__topLevelItem" data-reactid=".j5559a8z54.1.0.2.0.1">
           <a class="siteHeader__topLevelLink" data-reactid=".j5559a8z54.1.0.2.0.1.0" href="/review/list?ref=nav_mybooks">
            My Books
           </a>
          </li>
          <li class="siteHeader__topLevelItem" data-reactid=".j5559a8z54.1.0.2.0.2">
           <div class="primaryNavMenu primaryNavMenu--siteHeaderBrowseMenu ignore-react-onclickoutside" data-reactid=".j5559a8z54.1.0.2.0.2.0">
            <a aria-expanded="false" aria-haspopup="true" class="primaryNavMenu__trigger primaryNavMenu__trigger--siteHeaderBrowseMenu" data-reactid=".j5559a8z54.1.0.2.0.2.0.0" data-ux-click="true" href="/book?ref=nav_brws" role="button">
             <span data-reactid=".j5559a8z54.1.0.2.0.2.0.0.0">
              Browse ▾
             </span>
            </a>
            <div class="primaryNavMenu__menu gr-box gr-box--withShadowLarge wide" data-reactid=".j5559a8z54.1.0.2.0.2.0.1" role="menu">
             <div class="siteHeader__browseMenuDropdown" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0">
              <ul class="siteHeader__subNav" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0">
               <li aria-label="Recommendations" class="menuLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.0" role="menuitem Recommendations">
                <a class="siteHeader__subNavLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.0.0" href="/recommendations?ref=nav_brws_recs">
                 Recommendations
                </a>
               </li>
               <li aria-label="Choice Awards" class="menuLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.1" role="menuitem Choice Awards">
                <a class="siteHeader__subNavLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.1.0" href="/choiceawards?ref=nav_brws_gca">
                 Choice Awards
                </a>
               </li>
               <li aria-label="Genres" class="menuLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.2" role="menuitem Genres">
                <a class="siteHeader__subNavLink siteHeader__subNavLink--genresIndex" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.2.0" href="/genres?ref=nav_brws_genres">
                 Genres
                </a>
               </li>
               <li aria-label="Giveaways" class="menuLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.3" role="menuitem Giveaways">
                <a class="siteHeader__subNavLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.3.0" href="/giveaway?ref=nav_brws_giveaways">
                 Giveaways
                </a>
               </li>
               <li aria-label="New Releases" class="menuLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.4" role="menuitem New Releases">
                <a class="siteHeader__subNavLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.4.0" href="/book/popular_by_date/2026/7?ref=nav_brws_newrels">
                 New Releases
                </a>
               </li>
               <li aria-label="Lists" class="menuLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.5" role="menuitem Lists">
                <a class="siteHeader__subNavLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.5.0" href="/list?ref=nav_brws_lists">
                 Lists
                </a>
               </li>
               <li aria-label="Explore" class="menuLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.6" role="menuitem Explore">
                <a class="siteHeader__subNavLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.6.0" href="/book?ref=nav_brws_explore">
                 Explore
                </a>
               </li>
               <li aria-label="News &amp; Interviews" class="menuLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.7" role="menuitem News &amp; Interviews">
                <a class="siteHeader__subNavLink" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.0.7.0" href="/news?ref=nav_brws_news">
                 News &amp; Interviews
                </a>
               </li>
              </ul>
              <div class="siteHeader__spotlight siteHeader__spotlight--withoutSubMenu" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1">
               <div class="genreListContainer" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0">
                <div class="siteHeader__heading siteHeader__title" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.0">
                 Genres
                </div>
                <ul class="genreList" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0">
                 <li class="genreList__genre" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Art" role="menuitem">
                  <a class="genreList__genreLink gr-hyperlink gr-hyperlink--naked" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Art.0" href="/genres/art">
                   Art
                  </a>
                 </li>
                 <li class="genreList__genre" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Biography" role="menuitem">
                  <a class="genreList__genreLink gr-hyperlink gr-hyperlink--naked" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Biography.0" href="/genres/biography">
                   Biography
                  </a>
                 </li>
                 <li class="genreList__genre" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Business" role="menuitem">
                  <a class="genreList__genreLink gr-hyperlink gr-hyperlink--naked" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Business.0" href="/genres/business">
                   Business
                  </a>
                 </li>
                 <li class="genreList__genre" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Children's" role="menuitem">
                  <a class="genreList__genreLink gr-hyperlink gr-hyperlink--naked" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Children's.0" href="/genres/children-s">
                   Children's
                  </a>
                 </li>
                 <li class="genreList__genre" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Christian" role="menuitem">
                  <a class="genreList__genreLink gr-hyperlink gr-hyperlink--naked" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Christian.0" href="/genres/christian">
                   Christian
                  </a>
                 </li>
                 <li class="genreList__genre" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Classics" role="menuitem">
                  <a class="genreList__genreLink gr-hyperlink gr-hyperlink--naked" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Classics.0" href="/genres/classics">
                   Classics
                  </a>
                 </li>
                 <li class="genreList__genre" data-reactid=".j5559a8z54.1.0.2.0.2.0.1.0.1.0.1:$genreList0.0:$Comics" role="menuitem">

# Locate Quote Containers


Find all quote cards using their HTML class.

In [10]:
book_data = soup.find_all( "div",class_="quote")
#book_data = soup.find_all( "div",class_="quoteText")
len(book_data)

30

# Verify Scraped Elements


Display the first quote container to understand its HTML structure.

In [11]:
print(soup.find("div",class_="quote"))

<div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="/author/show/3565.Oscar_Wilde">
<img alt="Oscar Wilde" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1673611182i/3565._UX200_CR0,15,200,200_.jpg"/>
</a>
<div class="quoteText">
      “Be yourself; everyone else is already taken.”
    <br/>
  ―
  <span class="authorOrTitle">
    Oscar Wilde
  </span>
</div>
<div class="quoteFooter">
<div class="right">
<a class="smallText" href="/quotes/19884-be-yourself-everyone-else-is-already-taken" title="View this quote">178537 likes</a>
</div>
</div>
</div>
<div class="action">
<a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
</div>
</div>

# Display All Quote Containers


Print all the quote elements extracted from the webpage.

In [12]:
print(book_data)

[<div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="/author/show/3565.Oscar_Wilde">
<img alt="Oscar Wilde" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1673611182i/3565._UX200_CR0,15,200,200_.jpg"/>
</a>
<div class="quoteText">
      “Be yourself; everyone else is already taken.”
    <br/>
  ―
  <span class="authorOrTitle">
    Oscar Wilde
  </span>
</div>
<div class="quoteFooter">
<div class="right">
<a class="smallText" href="/quotes/19884-be-yourself-everyone-else-is-already-taken" title="View this quote">178537 likes</a>
</div>
</div>
</div>
<div class="action">
<a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
</div>
</div>, <div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="https://images.gr-assets.com/quotes/1511992603p8/8630.jpg">
<img alt="I'm selfish, impatient and a little insecure. I make mistakes, I am out of control" src="https://images.gr-assets.com/quotes/1511992603p2/8630.jpg"/>
</a>
<div class="quoteText">
      “I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.”
    <br/>
  ―
  <span class="authorOrTitle">
    Marilyn Monroe
  </span>
</div>
<div class="quoteFooter">
<div class="greyText smallText left">
     tags:
       <a href="/quotes/tag/attributed-no-source">attributed-no-source</a>,
       <a href="/quotes/tag/best">best</a>,
       <a href="/quotes/tag/life">life</a>,
       <a href="/quotes/tag/love">love</a>,
       <a href="/quotes/tag/misattributed-marilyn-monroe">misattributed-marilyn-monroe</a>,
       <a href="/quotes/tag/mistakes">mistakes</a>,
       <a href="/quotes/tag/out-of-control">out-of-control</a>,
       <a href="/quotes/tag/truth">truth</a>,
       <a href="/quotes/tag/worst">worst</a>
</div>
<div class="right">
<a class="smallText" href="/quotes/8630-i-m-selfish-impatient-and-a-little-insecure-i-make-mistakes" title="View this quote">165858 likes</a>
</div>
</div>
</div>
<div class="action">
<a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
</div>
</div>, <div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="/author/show/22302.Frank_Zappa">
<img alt="Frank Zappa" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1696236573i/22302._UX200_CR0,0,200,200_.jpg"/>
</a>
<div class="quoteText">
      “So many books, so little time.”
    <br/>
  ―
  <span class="authorOrTitle">
    Frank Zappa
  </span>
</div>
<div class="quoteFooter">
<div class="greyText smallText left">
     tags:
       <a href="/quotes/tag/books">books</a>,
       <a href="/quotes/tag/humor">humor</a>
</div>
<div class="right">
<a class="smallText" href="/quotes/66-so-many-books-so-little-time" title="View this quote">152626 likes</a>
</div>
</div>
</div>
<div class="action">
<a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
</div>
</div>, <div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="/author/show/9810.Albert_Einstein">
<img alt="Albert Einstein" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1429114964i/9810._UX200_CR0,14,200,200_.jpg"/>
</a>
<div class="quoteText">
      “Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.”
    <br/>
  ―
  <span class="authorOrTitle">
    Albert Einstein
  </span>
</div>
<div class="quoteFooter">
<div class="greyText smallText left">
     tags:
       <a href="/quotes/tag/attributed-no-source">attributed-no-source</a>,
       <a href="/quotes/tag/human-nature">human-nature</a>,
       <a href="/quotes/tag/humor">humor</a>,
       <a href="/quotes/tag/infinity">infinity</a>,
       <a href="/quotes/tag/philosophy">philosophy</a>,
       <a href="/quotes/tag/science">science</a>,
       <a href="/quotes/tag/stupidity">stupidity</a>,
       <a href="/quotes/tag/universe">universe</a>
</div>
<div class="right">
<a class="smallText" href="/quotes/942-two-things-are-infinite-the-universe-and-human-stupidity-and" title="View this quote">149048 likes</a>
</div>
</div>
</div>
<div class="action">
<a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
</div>
</div>, <div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="/author/show/13755.Marcus_Tullius_Cicero">
<img alt="Marcus Tullius Cicero" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1197881416i/13755._UX200_CR0,47,200,200_.jpg"/>
</a>
<div class="quoteText">
      “A room without books is like a body without a soul.”
    <br/>
  ―
  <span class="authorOrTitle">
    Marcus Tullius Cicero
  </span>
</div>
<div class="quoteFooter">
<div class="greyText smallText left">
     tags:
       <a href="/quotes/tag/attributed-no-source">attributed-no-source</a>,
       <a href="/quotes/tag/books">books</a>,
       <a href="/quotes/tag/simile">simile</a>,
       <a href="/quotes/tag/soul">soul</a>
</div>
<div class="right">
<a class="smallText" href="/quotes/764-a-room-without-books-is-like-a-body-without-a" title="View this quote">136075 likes</a>
</div>
</div>
</div>
<div class="action">
<a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
</div>
</div>, <div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="/author/show/5768330.Bernard_M_Baruch">
<img alt="Bernard M. Baruch" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1331977133i/5768330._UX200_CR0,30,200,200_.jpg"/>
</a>
<div class="quoteText">
      “Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.”
    <br/>
  ―
  <span class="authorOrTitle">
    Bernard M. Baruch
  </span>
</div>
<div class="quoteFooter">
<div class="greyText smallText left">
     tags:
       <a href="/quotes/tag/ataraxy">ataraxy</a>,
       <a href="/quotes/tag/be-yourself">be-yourself</a>,
       <a href="/quotes/tag/confidence">confidence</a>,
       <a href="/quotes/tag/fitting-in">fitting-in</a>,
       <a href="/quotes/tag/individuality">individuality</a>,
       <a href="/quotes/tag/misattributed-dr-seuss">misattributed-dr-seuss</a>,
       <a href="/quotes/tag/those-who-matter">those-who-matter</a>
</div>
<div class="right">
<a class="smallText" href="/quotes/865-be-who-you-are-and-say-what-you-feel-because" title="View this quote">130621 likes</a>
</div>
</div>
</div>
<div class="action">
<a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
</div>
</div>, <div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="/author/show/1744830.William_W_Purkey">
<img alt="William W. Purkey" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1282396130i/1744830._UX200_CR0,47,200,200_.jpg"/>
</a>
<div class="quoteText">
      “You've gotta dance like there's nobody watching,<br/>Love like you'll never be hurt,<br/>Sing like there's nobody listening,<br/>And live like it's heaven on earth.”
    <br/>
  ―
  <span class="authorOrTitle">
    William W. Purkey
  </span>
</div>
<div class="quoteFooter">
<div class="greyText smallText left">
     tags:
       <a href="/quotes/tag/dance">dance</a>,
       <a href="/quotes/tag/heaven">heaven</a>,
       <a href="/quotes/tag/hurt">hurt</a>,
       <a href="/quotes/tag/inspirational">inspirational</a>,
       <a href="/quotes/tag/life">life</a>,
       <a href="/quotes/tag/love">love</a>,
       <a href="/quotes/tag/sing">sing</a>
</div>
<div class="right">
<a class="smallText" href="/quotes/10123-you-ve-gotta-dance-like-there-s-nobody-watching-love-like-you-ll" title="View this quote">129389 likes</a>
</div>
</div>
</div>
<div class="action">
<a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
</div>
</div>, <div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="/author/show/61105.Dr_Seuss">
<img alt="Dr. Seuss" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1193930952i/61105._UX200_CR0,30,200,200_.jpg"/>
</a>
<div class="quoteText">
      “You know you're in love when you can't fall asleep because reality is finally better than your dreams.”
    <br/>
  ―
  <span class="authorOrTitle">
    Dr. Seuss
  </span>
</div>
<div class="quoteFooter">
<div class="greyText smallText left">
     tags:
       <a href="/quotes/tag/attributed-no-source">attributed-no-source</a>,
       <a href="/quotes/tag/dreams">dreams</a>,
       <a href="/quotes/tag/love">love</a>,
       <a href="/quotes/tag/reality">reality</a>,
       <a href="/quotes/tag/sleep">sleep</a>
</div>
<div class="right">
<a class="smallText" href="/quotes/7901-you-know-you-re-in-love-when-you-can-t-fall-asleep" title="View this quote">127726 likes</a>
</div>
</div>
</div>
<div class="action">
<a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
</div>
</div>, <div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="/author/show/259666.Mae_West">
<img alt="Mae West" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1738043431i/259666._UX200_CR0,23,200,200_.jpg"/>
</a>
<div class="quoteText">
      “You only live once, but if you do it right, once is enough.”
    <br/>
  ―
  <span class="authorOrTitle">
    Mae West
  </span>
</div>
<div class="quoteFooter">
<div class="greyText smallText left">
     tags:
       <a href="/quotes/tag/humor">humor</a>,
       <a href="/quotes/tag/life">life</a>
</div>
<div class="right">
<a class="smallText" href="/quotes/1598-you-only-live-once-but-if-you-do-it-right" title="View this quote">119603 likes</a>
</div>
</div>
</div>
<div class="action">
<a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
</div>
</div>, <div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="/author/show/5810891.Mahatma_Gandhi">
<img alt="Mahatma Gandhi" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1356810912i/5810891._UX200_CR0,21,200,200_.jpg"/>
</a>
<div class="quoteText">
      “Be the change that you wish to see in the world.”
    <br/>
  ―
  <span class="authorOrTitle">
    Mahatma Gandhi
  </span>
</div>
<div class="quoteFooter">
<div class="greyText smallText left">
     tags:
       <a href="/quotes/tag/action">action</a>,
       <a href="/quotes/tag/change">change</a>,
       <a href="/quotes/tag/inspirational">inspirational</a>,
       <a href="/quotes/tag/misattributed-to-gandhi">misattributed-to-gandhi</a>,
       <a href="/quotes/tag/philosophy">philosophy</a>,
       <a href="/quotes/tag/wish">wish</a>
</div>
<div class="right">
<a class="smallText" href="/quotes/24499-be-the-change-that-you-wish-to-see-in-the" title="View this quote">114737 likes</a>
</div>
</div>
</div>
<div class="action">
<a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
</div>
</div>, <div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="/author/show/7715.Robert_Frost">
<img alt="Robert Frost" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1605640483i/7715._UX200_CR0,33,200,200_.jpg"/>
</a>
<div class="quoteText">
      “In three words I can sum up everything I've learned about life: it goes on.”
    <br/>
  ―
  <span class="authorOrTitle">
    Robert Frost
  </span>
</div>
<div class="quoteFooter">
<div class="greyText smallText left">
     tags:
       <a href="/quotes/tag/life">life</a>
</div>
<div class="right">
<a class="smallText" href="/quotes/258-in-three-words-i-can-sum-up-everything-i-ve-learned" title="View this quote">109662 likes</a>
</div>
</div>
</div>
<div class="action">
<a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
</div>
</div>, <div class="quote">
<div class="quoteDetails">
<a class="leftAlignedImage quoteAvatar" href="/author/show/1077326.J_K_Rowling">
<img alt="J.K. Rowling" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1596216614i/1077326._UX200_CR0,15,200,200_.jpg"/>
</a>
<div class="quoteText">
      “If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.”
    <br/>
  ―
  <span class="authorOrTitle">
    J.K. Rowling,
  </span>
<span id="quote_book_link_6">
<a class="authorOrTitle" href="/work/quotes/3046572">Harry Potter and the Goblet of Fire</a>
</span>
<script charset="utf-8" type="text/javascript">
//<![CDATA[

  function submitShelfLink(unique_id, book_id, shelf_id, shelf_name, submit_form, exclusive) {
    var checkbox_id = 'shelf_name_' + unique_id + '_' + shelf_id;
    var element = document.getElementById(checkbox_id)

    var checked = element.checked
    if (checked && exclusive) {
      // can't uncheck a radio by clicking it!
      return
    }
    if(document.getElementById("savingMessage")){
      Element.show('savingMessage')
    }
    var element_id = 'shelfInDropdownName_' + unique_id + '_' + shelf_id;
    Element.update(element_id, "saving...");
    if (submit_form) {
      Element.hide('shelfDropdown_' + unique_id)
      var form = document.getElementById('addBookForm' + book_id)
      if (form) {
        form.shelf.value = shelf_name
        form.onsubmit()
      }
    }
    else {
      var action = checked ? 'remove' : ''
      element.checked = !element.checked
      new Ajax.Request('/shelf/add_to_shelf', {asynchronous:true, evalScripts:true, onSuccess:function(request){shelfSubmitted(request, book_id, checkbox_id, element_id, unique_id, shelf_name)}, parameters:'book_id=' + book_id + '&name=' + shelf_name + '&a=' + action + '&authenticity_token=' + encodeURIComponent('NE3JMyK2GTy2fYhips9UzOheLeCm/QPKVbnIei7GRSBqPSm4UWCxzA9x0FkpltKoKZrCR3Yfk3wNYvYtxEUvEw==')})
    }
  }

  function shelfSubmitted(request, book_id, checkbox_id, element_id, unique_id, shelf_name) {
    Element.update('shelfListfalse_' + book_id, request.responseText)
    afterShelfSave(checkbox_id, element_id, unique_id, shelf_name.escapeHTML())
  }

  function refreshGroupBox(group_id, book_id) {
    new Ajax.Updater('addGroupBooks' + book_id + '', '/group/add_book_box', {asynchronous:true, evalScripts:true, onSuccess:function(request){refreshGroupBoxComplete(request, book_id);}, parameters:'id=' + group_id + '&book_id=' + book_id + '&refresh=true' + '&authenticity_token=' + encodeURIComponent('3yw3EhgknS756jZS3a+7TuabfOn4gADM3cagSl7KiheBXNeZa/I13kDmbmlS9j0qJ1+TTihikHqFHZ4dtEngJA==')})
  }
//]]>
</script>
<script>
//<![CDATA[

In [13]:
book_data

[<div class="quote">
 <div class="quoteDetails">
 <a class="leftAlignedImage quoteAvatar" href="/author/show/3565.Oscar_Wilde">
 <img alt="Oscar Wilde" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1673611182i/3565._UX200_CR0,15,200,200_.jpg"/>
 </a>
 <div class="quoteText">
       “Be yourself; everyone else is already taken.”
     <br/>
   ―
   <span class="authorOrTitle">
     Oscar Wilde
   </span>
 </div>
 <div class="quoteFooter">
 <div class="right">
 <a class="smallText" href="/quotes/19884-be-yourself-everyone-else-is-already-taken" title="View this quote">178537 likes</a>
 </div>
 </div>
 </div>
 <div class="action">
 <a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
 </div>
 </div>,
 <div class="quote">
 <div class="quoteDetails">
 <a class="leftAlignedImage quoteAvatar" href="https://images.gr-assets.com/quotes/1511992603p8/8630.jpg">
 <img alt="I'm selfish, impatient and a little insecure. I make mistakes, I am out of control" src="https://images.gr-assets.com/quotes/1511992603p2/8630.jpg"/>
 </a>
 <div class="quoteText">
       “I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.”
     <br/>
   ―
   <span class="authorOrTitle">
     Marilyn Monroe
   </span>
 </div>
 <div class="quoteFooter">
 <div class="greyText smallText left">
      tags:
        <a href="/quotes/tag/attributed-no-source">attributed-no-source</a>,
        <a href="/quotes/tag/best">best</a>,
        <a href="/quotes/tag/life">life</a>,
        <a href="/quotes/tag/love">love</a>,
        <a href="/quotes/tag/misattributed-marilyn-monroe">misattributed-marilyn-monroe</a>,
        <a href="/quotes/tag/mistakes">mistakes</a>,
        <a href="/quotes/tag/out-of-control">out-of-control</a>,
        <a href="/quotes/tag/truth">truth</a>,
        <a href="/quotes/tag/worst">worst</a>
 </div>
 <div class="right">
 <a class="smallText" href="/quotes/8630-i-m-selfish-impatient-and-a-little-insecure-i-make-mistakes" title="View this quote">165858 likes</a>
 </div>
 </div>
 </div>
 <div class="action">
 <a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
 </div>
 </div>,
 <div class="quote">
 <div class="quoteDetails">
 <a class="leftAlignedImage quoteAvatar" href="/author/show/22302.Frank_Zappa">
 <img alt="Frank Zappa" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1696236573i/22302._UX200_CR0,0,200,200_.jpg"/>
 </a>
 <div class="quoteText">
       “So many books, so little time.”
     <br/>
   ―
   <span class="authorOrTitle">
     Frank Zappa
   </span>
 </div>
 <div class="quoteFooter">
 <div class="greyText smallText left">
      tags:
        <a href="/quotes/tag/books">books</a>,
        <a href="/quotes/tag/humor">humor</a>
 </div>
 <div class="right">
 <a class="smallText" href="/quotes/66-so-many-books-so-little-time" title="View this quote">152626 likes</a>
 </div>
 </div>
 </div>
 <div class="action">
 <a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
 </div>
 </div>,
 <div class="quote">
 <div class="quoteDetails">
 <a class="leftAlignedImage quoteAvatar" href="/author/show/9810.Albert_Einstein">
 <img alt="Albert Einstein" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1429114964i/9810._UX200_CR0,14,200,200_.jpg"/>
 </a>
 <div class="quoteText">
       “Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.”
     <br/>
   ―
   <span class="authorOrTitle">
     Albert Einstein
   </span>
 </div>
 <div class="quoteFooter">
 <div class="greyText smallText left">
      tags:
        <a href="/quotes/tag/attributed-no-source">attributed-no-source</a>,
        <a href="/quotes/tag/human-nature">human-nature</a>,
        <a href="/quotes/tag/humor">humor</a>,
        <a href="/quotes/tag/infinity">infinity</a>,
        <a href="/quotes/tag/philosophy">philosophy</a>,
        <a href="/quotes/tag/science">science</a>,
        <a href="/quotes/tag/stupidity">stupidity</a>,
        <a href="/quotes/tag/universe">universe</a>
 </div>
 <div class="right">
 <a class="smallText" href="/quotes/942-two-things-are-infinite-the-universe-and-human-stupidity-and" title="View this quote">149048 likes</a>
 </div>
 </div>
 </div>
 <div class="action">
 <a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
 </div>
 </div>,
 <div class="quote">
 <div class="quoteDetails">
 <a class="leftAlignedImage quoteAvatar" href="/author/show/13755.Marcus_Tullius_Cicero">
 <img alt="Marcus Tullius Cicero" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1197881416i/13755._UX200_CR0,47,200,200_.jpg"/>
 </a>
 <div class="quoteText">
       “A room without books is like a body without a soul.”
     <br/>
   ―
   <span class="authorOrTitle">
     Marcus Tullius Cicero
   </span>
 </div>
 <div class="quoteFooter">
 <div class="greyText smallText left">
      tags:
        <a href="/quotes/tag/attributed-no-source">attributed-no-source</a>,
        <a href="/quotes/tag/books">books</a>,
        <a href="/quotes/tag/simile">simile</a>,
        <a href="/quotes/tag/soul">soul</a>
 </div>
 <div class="right">
 <a class="smallText" href="/quotes/764-a-room-without-books-is-like-a-body-without-a" title="View this quote">136075 likes</a>
 </div>
 </div>
 </div>
 <div class="action">
 <a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
 </div>
 </div>,
 <div class="quote">
 <div class="quoteDetails">
 <a class="leftAlignedImage quoteAvatar" href="/author/show/5768330.Bernard_M_Baruch">
 <img alt="Bernard M. Baruch" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1331977133i/5768330._UX200_CR0,30,200,200_.jpg"/>
 </a>
 <div class="quoteText">
       “Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.”
     <br/>
   ―
   <span class="authorOrTitle">
     Bernard M. Baruch
   </span>
 </div>
 <div class="quoteFooter">
 <div class="greyText smallText left">
      tags:
        <a href="/quotes/tag/ataraxy">ataraxy</a>,
        <a href="/quotes/tag/be-yourself">be-yourself</a>,
        <a href="/quotes/tag/confidence">confidence</a>,
        <a href="/quotes/tag/fitting-in">fitting-in</a>,
        <a href="/quotes/tag/individuality">individuality</a>,
        <a href="/quotes/tag/misattributed-dr-seuss">misattributed-dr-seuss</a>,
        <a href="/quotes/tag/those-who-matter">those-who-matter</a>
 </div>
 <div class="right">
 <a class="smallText" href="/quotes/865-be-who-you-are-and-say-what-you-feel-because" title="View this quote">130621 likes</a>
 </div>
 </div>
 </div>
 <div class="action">
 <a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
 </div>
 </div>,
 <div class="quote">
 <div class="quoteDetails">
 <a class="leftAlignedImage quoteAvatar" href="/author/show/1744830.William_W_Purkey">
 <img alt="William W. Purkey" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1282396130i/1744830._UX200_CR0,47,200,200_.jpg"/>
 </a>
 <div class="quoteText">
       “You've gotta dance like there's nobody watching,<br/>Love like you'll never be hurt,<br/>Sing like there's nobody listening,<br/>And live like it's heaven on earth.”
     <br/>
   ―
   <span class="authorOrTitle">
     William W. Purkey
   </span>
 </div>
 <div class="quoteFooter">
 <div class="greyText smallText left">
      tags:
        <a href="/quotes/tag/dance">dance</a>,
        <a href="/quotes/tag/heaven">heaven</a>,
        <a href="/quotes/tag/hurt">hurt</a>,
        <a href="/quotes/tag/inspirational">inspirational</a>,
        <a href="/quotes/tag/life">life</a>,
        <a href="/quotes/tag/love">love</a>,
        <a href="/quotes/tag/sing">sing</a>
 </div>
 <div class="right">
 <a class="smallText" href="/quotes/10123-you-ve-gotta-dance-like-there-s-nobody-watching-love-like-you-ll" title="View this quote">129389 likes</a>
 </div>
 </div>
 </div>
 <div class="action">
 <a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
 </div>
 </div>,
 <div class="quote">
 <div class="quoteDetails">
 <a class="leftAlignedImage quoteAvatar" href="/author/show/61105.Dr_Seuss">
 <img alt="Dr. Seuss" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1193930952i/61105._UX200_CR0,30,200,200_.jpg"/>
 </a>
 <div class="quoteText">
       “You know you're in love when you can't fall asleep because reality is finally better than your dreams.”
     <br/>
   ―
   <span class="authorOrTitle">
     Dr. Seuss
   </span>
 </div>
 <div class="quoteFooter">
 <div class="greyText smallText left">
      tags:
        <a href="/quotes/tag/attributed-no-source">attributed-no-source</a>,
        <a href="/quotes/tag/dreams">dreams</a>,
        <a href="/quotes/tag/love">love</a>,
        <a href="/quotes/tag/reality">reality</a>,
        <a href="/quotes/tag/sleep">sleep</a>
 </div>
 <div class="right">
 <a class="smallText" href="/quotes/7901-you-know-you-re-in-love-when-you-can-t-fall-asleep" title="View this quote">127726 likes</a>
 </div>
 </div>
 </div>
 <div class="action">
 <a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
 </div>
 </div>,
 <div class="quote">
 <div class="quoteDetails">
 <a class="leftAlignedImage quoteAvatar" href="/author/show/259666.Mae_West">
 <img alt="Mae West" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1738043431i/259666._UX200_CR0,23,200,200_.jpg"/>
 </a>
 <div class="quoteText">
       “You only live once, but if you do it right, once is enough.”
     <br/>
   ―
   <span class="authorOrTitle">
     Mae West
   </span>
 </div>
 <div class="quoteFooter">
 <div class="greyText smallText left">
      tags:
        <a href="/quotes/tag/humor">humor</a>,
        <a href="/quotes/tag/life">life</a>
 </div>
 <div class="right">
 <a class="smallText" href="/quotes/1598-you-only-live-once-but-if-you-do-it-right" title="View this quote">119603 likes</a>
 </div>
 </div>
 </div>
 <div class="action">
 <a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
 </div>
 </div>,
 <div class="quote">
 <div class="quoteDetails">
 <a class="leftAlignedImage quoteAvatar" href="/author/show/5810891.Mahatma_Gandhi">
 <img alt="Mahatma Gandhi" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1356810912i/5810891._UX200_CR0,21,200,200_.jpg"/>
 </a>
 <div class="quoteText">
       “Be the change that you wish to see in the world.”
     <br/>
   ―
   <span class="authorOrTitle">
     Mahatma Gandhi
   </span>
 </div>
 <div class="quoteFooter">
 <div class="greyText smallText left">
      tags:
        <a href="/quotes/tag/action">action</a>,
        <a href="/quotes/tag/change">change</a>,
        <a href="/quotes/tag/inspirational">inspirational</a>,
        <a href="/quotes/tag/misattributed-to-gandhi">misattributed-to-gandhi</a>,
        <a href="/quotes/tag/philosophy">philosophy</a>,
        <a href="/quotes/tag/wish">wish</a>
 </div>
 <div class="right">
 <a class="smallText" href="/quotes/24499-be-the-change-that-you-wish-to-see-in-the" title="View this quote">114737 likes</a>
 </div>
 </div>
 </div>
 <div class="action">
 <a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
 </div>
 </div>,
 <div class="quote">
 <div class="quoteDetails">
 <a class="leftAlignedImage quoteAvatar" href="/author/show/7715.Robert_Frost">
 <img alt="Robert Frost" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1605640483i/7715._UX200_CR0,33,200,200_.jpg"/>
 </a>
 <div class="quoteText">
       “In three words I can sum up everything I've learned about life: it goes on.”
     <br/>
   ―
   <span class="authorOrTitle">
     Robert Frost
   </span>
 </div>
 <div class="quoteFooter">
 <div class="greyText smallText left">
      tags:
        <a href="/quotes/tag/life">life</a>
 </div>
 <div class="right">
 <a class="smallText" href="/quotes/258-in-three-words-i-can-sum-up-everything-i-ve-learned" title="View this quote">109662 likes</a>
 </div>
 </div>
 </div>
 <div class="action">
 <a class="gr-button gr-button--small" href="/user/new" rel="nofollow">Like</a>
 </div>
 </div>,
 <div class="quote">
 <div class="quoteDetails">
 <a class="leftAlignedImage quoteAvatar" href="/author/show/1077326.J_K_Rowling">
 <img alt="J.K. Rowling" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/authors/1596216614i/1077326._UX200_CR0,15,200,200_.jpg"/>
 </a>
 <div class="quoteText">
       “If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.”
     <br/>
   ―
   <span class="authorOrTitle">
     J.K. Rowling,
   </span>
 <span id="quote_book_link_6">
 <a class="authorOrTitle" href="/work/quotes/3046572">Harry Potter and the Goblet of Fire</a>
 </span>
 <script charset="utf-8" type="text/javascript">
 //<![CDATA[

   function submitShelfLink(unique_id, book_id, shelf_id, shelf_name, submit_form, exclusive) {
     var checkbox_id = 'shelf_name_' + unique_id + '_' + shelf_id;
     var element = document.getElementById(checkbox_id)

     var checked = element.checked
     if (checked && exclusive) {
       // can't uncheck a radio by clicking it!
       return
     }
     if(document.getElementById("savingMessage")){
       Element.show('savingMessage')
     }
     var element_id = 'shelfInDropdownName_' + unique_id + '_' + shelf_id;
     Element.update(element_id, "saving...");
     if (submit_form) {
       Element.hide('shelfDropdown_' + unique_id)
       var form = document.getElementById('addBookForm' + book_id)
       if (form) {
         form.shelf.value = shelf_name
         form.onsubmit()
       }
     }
     else {
       var action = checked ? 'remove' : ''
       element.checked = !element.checked
       new Ajax.Request('/shelf/add_to_shelf', {asynchronous:true, evalScripts:true, onSuccess:function(request){shelfSubmitted(request, book_id, checkbox_id, element_id, unique_id, shelf_name)}, parameters:'book_id=' + book_id + '&name=' + shelf_name + '&a=' + action + '&authenticity_token=' + encodeURIComponent('NE3JMyK2GTy2fYhips9UzOheLeCm/QPKVbnIei7GRSBqPSm4UWCxzA9x0FkpltKoKZrCR3Yfk3wNYvYtxEUvEw==')})
     }
   }

   function shelfSubmitted(request, book_id, checkbox_id, element_id, unique_id, shelf_name) {
     Element.update('shelfListfalse_' + book_id, request.responseText)
     afterShelfSave(checkbox_id, element_id, unique_id, shelf_name.escapeHTML())
   }

   function refreshGroupBox(group_id, book_id) {
     new Ajax.Updater('addGroupBooks' + book_id + '', '/group/add_book_box', {asynchronous:true, evalScripts:true, onSuccess:function(request){refreshGroupBoxComplete(request, book_id);}, parameters:'id=' + group_id + '&book_id=' + book_id + '&refresh=true' + '&authenticity_token=' + encodeURIComponent('3yw3EhgknS756jZS3a+7TuabfOn4gADM3cagSl7KiheBXNeZa/I13kDmbmlS9j0qJ1+TTihikHqFHZ4dtEngJA==')})
   }
 //]]>
 </script>
 <script>
 //<![CDATA[

# Count Total Quotes


Determine the total number of quotes available on the page.

In [14]:
print(len(book_data))

30

# Extract Required Information


Loop through each quote card and extract useful information such as:

Quote,
Author,
Tags

In [15]:
# 1. Create a separate list for results
all_books = []

for book in book_data:
    title = book.find("span", class_="authorOrTitle")
    quote = book.find("div", class_="quoteText")
    likes = book.find("a", class_="smallText")

    # 2. Append to the new list instead
    all_books.append({
        "title": title.text.strip() if title else "N/A",
        "quote": quote.text.strip() if quote else "N/A",
        "likes": likes.text.strip() if likes else "N/A",
    })

# Create a DataFrame


Convert the extracted data into a Pandas DataFrame for easier analysis.

In [16]:
df = pd.DataFrame(all_books)
df

,title,quote,likes
0,Oscar Wilde,“Be yourself; everyone else is already taken.”...,178537 likes
1,Marilyn Monroe,"“I'm selfish, impatient and a little insecure....",165858 likes
2,Frank Zappa,"“So many books, so little time.”\n \n ―\n ...",152626 likes
3,Albert Einstein,“Two things are infinite: the universe and hum...,149048 likes
4,Marcus Tullius Cicero,“A room without books is like a body without a...,136075 likes
5,Bernard M. Baruch,"“Be who you are and say what you feel, because...",130621 likes
6,William W. Purkey,“You've gotta dance like there's nobody watchi...,129389 likes
7,Dr. Seuss,“You know you're in love when you can't fall a...,127726 likes
8,Mae West,"“You only live once, but if you do it right, o...",119603 likes
9,Mahatma Gandhi,“Be the change that you wish to see in the wor...,114737 likes
10,Robert Frost,“In three words I can sum up everything I've l...,109662 likes
11,"J.K. Rowling,","“If you want to know what a man's like, take a...",101803 likes
12,Albert Camus,“Don’t walk in front of me… I may not followDo...,93921 likes
13,Mark Twain,"“If you tell the truth, you don't have to reme...",92603 likes
14,Maya Angelou,“I've learned that people will forget what you...,89706 likes
15,"C.S. Lewis,",“Friendship ... is born at the moment when one...,88256 likes
16,Oscar Wilde,“To live is the rarest thing in the world. Mos...,85321 likes
17,Elbert Hubbard,“A friend is someone who knows all about you a...,84474 likes
18,Oscar Wilde,“Always forgive your enemies; nothing annoys t...,82104 likes
19,"Martin Luther King Jr.,",“Darkness cannot drive out darkness: only ligh...,78657 likes
20,Mahatma Gandhi,“Live as if you were to die tomorrow. Learn as...,77964 likes
21,"Stephen Chbosky,",“We accept the love we think we deserve.”\n ...,76992 likes
22,"Friedrich Nietzsche,","“Without music, life would be a mistake.”\n ...",74661 likes
23,"Oscar Wilde,",“I am so clever that sometimes I don't underst...,71842 likes
24,Ralph Waldo Emerson,“To be yourself in a world that is constantly ...,69947 likes
25,Steve Jobs,“Here's to the crazy ones. The misfits. The re...,68359 likes
26,Narcotics Anonymous,"“Insanity is doing the same thing, over and ov...",64797 likes
27,"Andre Gide,",“It is better to be hated for what you are tha...,62546 likes
28,Marilyn Monroe,“I believe that everything happens for a reaso...,62254 likes
29,"H. Jackson Brown Jr.,",“Twenty years from now you will be more disapp...,60460 likes

# Preview the Dataset


Display the first few rows of the scraped dataset.

In [17]:
df.head()

,title,quote,likes
0,Oscar Wilde,“Be yourself; everyone else is already taken.”...,178537 likes
1,Marilyn Monroe,"“I'm selfish, impatient and a little insecure....",165858 likes
2,Frank Zappa,"“So many books, so little time.”\n \n ―\n ...",152626 likes
3,Albert Einstein,“Two things are infinite: the universe and hum...,149048 likes
4,Marcus Tullius Cicero,“A room without books is like a body without a...,136075 likes

# Export to CSV


Save the scraped data as a CSV file for future use.

In [18]:
df.to_csv("goodreads_scraped_books.csv", index=False)
print("CSV file created successfully!")

CSV file created successfully!