%%html

<style>
.header{
    text-align:center;
    padding:25px;
    border-radius:20px;
    background:linear-gradient(135deg,#6C63FF,#00B4DB);
    color:white;
    animation:fadeIn 2s ease-in-out;
    box-shadow:0 10px 25px rgba(0,0,0,.25);
    font-family:Arial, sans-serif;
}

.header h1{
    font-size:40px;
    margin-bottom:10px;
    animation:glow 2s infinite alternate;
}

.header h2{
    font-size:20px;
    font-weight:normal;
    margin-bottom:18px;
}

.info{
    margin-top:15px;
    display:inline-block;
    text-align:left;
    background:rgba(255,255,255,.15);
    padding:18px 30px;
    border-radius:15px;
    line-height:1.8;
    font-size:16px;
}

@keyframes fadeIn{
    from{
        opacity:0;
        transform:translateY(-30px);
    }
    to{
        opacity:1;
        transform:translateY(0);
    }
}

@keyframes glow{
    from{
        text-shadow:0 0 8px white;
    }
    to{
        text-shadow:0 0 20px #FFD700;
    }
}
</style>

<div class="header">

<h1>📈 Mutual Funds Web Scraping Using Python</h1>

<h2>Extracting Mutual Fund Data from a Financial Website</h2>

<div class="info">

<b>👩‍💻 Prepared By:</b> Sunaina Saini <br>
<b>🎓 Course:</b> B.Tech – Artificial Intelligence & Machine Learning (AIML) <br>
<b>🏢 Internship:</b> AIML Bootcamp – CodroidHub Pvt. Ltd. <br>
<b>🌐 Website:</b> Mutual Funds Website <br>
<b>🕸️ Scraping Type:</b> Static Web Scraping <br>
<b>💻 Language:</b> Python <br>
<b>📚 Libraries:</b> Requests, BeautifulSoup4, Pandas <br>
<b>📂 Output:</b> CSV Dataset of Mutual Fund Information <br>
<b>📅 Date:</b> July 2026

</div>

</div>

# Import Required Libraries

Import all the libraries needed for web scraping, data handling, and exporting the scraped data.

In [8]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

# Define the Target Website

Specify the URL of the webpage that will be scraped.

In [9]:
url = "https://finance.yahoo.com/markets/mutualfunds/top/"
response = requests.get(url)

# Add Browser Headers


Provide request headers so the website recognizes the request as coming from a real web browser.

In [10]:
HEADERS = ({'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

})

# Send HTTP Request

Send a GET request to the website and retrieve its HTML content.

In [11]:
response = requests.get(url,headers = HEADERS)

# Check the Response


Verify whether the request was successful by checking the HTTP status code.

In [12]:
print(response.status_code)

200

# Inspect Response Content


Check the type of the downloaded content.

In [13]:
type(response.content)

bytes

# Parse the HTML

Convert the HTML into a BeautifulSoup object for easier navigation.

In [14]:
soup = BeautifulSoup(response.content,"html.parser")

# Preview the HTML Structure


Display the parsed HTML structure for understanding the webpage layout.

In [15]:
soup

<!DOCTYPE html>

<html class="desktop neo-green dock-upscale" data-color-scheme="auto" data-color-theme-enabled="true" lang="en-US" theme="auto">
<head>
<meta charset="utf-8"/>
<meta content="guce.yahoo.com" name="oath:guce:consent-host"/>
<link crossorigin="anonymous" href="//s.yimg.com" rel="preconnect"/><link href="//geo.yahoo.com" rel="preconnect"/><link href="//query1.finance.yahoo.com" rel="preconnect"/><link href="//consent.cmp.oath.com" rel="preconnect"/><link as="worker" href="/__rapidworker-1.2.js" rel="preload"/><link href="https://s.yimg.com/uc/finance/webcore/js/_staticFinProtobuf.4ac0aa7cd811394598dc.js" rel="preconnect"/><link href="https://cdn.jsdelivr.net/npm/protobufjs@7.1.2/dist/minimal/protobuf.min.js" rel="preconnect"/><script>window.finNeoPageStart = Date.now();</script><script>
    (function(){if(!window.YAHOO){window.YAHOO={}};window.YAHOO.context={"consent":{"allowContentPersonalization":true,"allowCrossDeviceMapping":true,"allowFirstPartyAds":true,"allowSellPersonalInfo":true,"canEmbedThirdPartyContent":true,"canSell":true,"consentedVendors":["acast","brightcove","dailymotion","facebook","flourish","giphy","instagram","nbcuniversal","playbuzz","scribblelive","soundcloud","tiktok","vimeo","twitter","youtube","masque"]},"authed":"0","ynet":"0","ssl":"1","spdy":"0","ytee":"0","mode":"normal","tpConsent":true,"site":"finance","adblock":"0","bucket":"","colo":"sg3","device":"desktop","bot":"0","browser":"chrome","app":"unknown","ecma":"modern","environment":"prod","gdpr":false,"lang":"en-US","dir":"ltr","intl":"us","network":"mobile","os":"windows nt","partner":"none","region":"US","time":1784996840401,"tz":"Asia/Kolkata","usercountry":"IN","rmp":"0","webview":"0","feature":["benjiPrefetchAuction2","disableInterstitialUpsells","disableServiceRewrite","disableBack2Classic","disableYPFTaxArticleDisclosure","enable1PVideoTranscript","enableAnalystRatings","enableAPIRedisCaching","enableASArticleChartEmbed","enableCGResponseCaching","enableCalendarEventsCaching","disablePremiumTiersCaching","enableAboutRedirects","enableArticleCSN","enableBestHubs","enableBestCreditCardsPage","enableBestMortgageRatesPage","enableCccBoost","enableCGAuthorFeed","enableCGHomepageV1","enableCGHomepageV2","enableCGNewsStream","enableCGTopicStream","enableCGPersonalFinancePagination","enableCGPfContentLists","enableCGPortfolioNews","enableCGEventsLanding","enableCGShowsLanding","enableCGEventDetail","enableCGShowDetail","enableCGVideosCategory","enableCGVideoHub","enableCGEVPlayer","enableCGArticleFeatures","enableCGPersonalFinanceArticles","enableCGLiveBlog","enableCGSlideshow","enableCGVideoContentPage","enableCGRelatedStreamContent","enableCGFeatureBar","enableCGFeatureBarList","enableCGPartnerHub","enablePolarisPartnerHub","enableChartbeat","enableChatSupport","enableQSPCommunityService","enableCommunityMuteUser","enableQSPCommunityFeedTabs","enableCommunityCustomTakeItDownCopy","enableCorporateActions","enablePremiumAdsCSNStyleHandling","enableCompare","enableContentOfferVertical","enableCompareConvertCurrency","enableConsentAndGTM","enableCrumbRefresh","enableCSN","enableCurrencyConverter","enableDarkMode","enableDidomi","enableDockAddToFollowing","enableDockHomeStream","enableDockPortfolioControl","enableDockFooterAdOnScroll","enableExperimentalDockModules","enableFollow","enableEarningsTranscript","enableEarningsTranscriptAI","enableEntityDiscover","enableEntityDiscoverInStream","enableAICuratedTopicsBatch1","enableHistoricalStockPicks","enableHomeNewsStreamNewsletter","enableImportCSVReview","enableLazyMidCenter2NAds","enableLazyQSP","enableServiceWorker","enableMarketIndicesHeader","enableMarketsLeafHeatMap","enablePartnerHubsInL2Mobile","enableMultiQuote","enableMyMoneyOptIn","enableMyMoneyIntroVideo","enableNcpStreamCaching","enablePfConsistentNav","enableNeoBasicPFs","enableNeoGreen","enableNeoHouseCalcPage","enableNeoInvestmentIdea","enableNeoMortgageCalcPage","enableNeoQSPReportsLeaf","enableNeoResearchReport","enableNimbusSubNav","enableEnhancedScreeners","enableOvernight","enablePartnerDropdownNav","enablePersonalFinanceNewsletterIntegration","enablePersonalFinanceZillowIntegration","enablePfPremium","enablePfStreaming","enablePlaid","enablePinholeScreenshotOGForQuote","enablePlus","enablePolarisSeamlessScrollArticleRecommendations","enablePrivateCompany","enablePrivateCompanySurvey","enableQSP1PNews","enableQSPAiAnalystSheet","enableQSPAiAnalystSheetChatVersionV11","enableQSPAlphaSpaceCTA","enableQSPAnalysisGAAPToggle","enableQSPChartEarnings","enableQSPChartNewShading","enableQSPChartRangeTooltips","enableQSPCryptoLogo","enableQSPEarningsVsRev","enableQSPExpandedEarnings","enableQSPChartsFiscalYear","enableQSPHistoryPlusDownload","enableQSPIPO","enableQSPLiveEarnings","enableQSPHoldingsCard","enableQSPNavIcon","enableQSPQuoteHeaderV2","enableQSPPriceInsightsAnomaly","enableQSPAINewsHeadlines","enableQSPStockPicks","enableQSPStockPicksMF","enableQuoteLookup","enableRecentQuotes","enableResearchHub","enablePersistentScoutDock","enableScreenerCustomColumns","enableIndexHeatmap","enableScreenerHeatMap","enableScreenersCollapseDock","enableScreenersCustomiseResults","enableScreenersSpEarnings","enableScreenersDownload","enableScreenersIndex","enableScreenersExchange","enableSECFiling","enableSessionSnapshot","enableSkipNav","enableSkipToDock","enableSkipToNav","enableSmartAssetMsgA","enableStockPicksTableSort","enableStockPicksTableFiltering","enableStockStoryPfPage","enableStreamInjectionSlot","enableTickerAIInsights","enableTopCryptoAttr","enable24HourCrypto","enableTradeNow","enableAlphaSpaceL2","enableAlphaSpaceStandaloneRedirect","enableUpgradeBadgeDesign","enableUnifiedContentStream","enableVideoInHero","enableDockQuoteEventsModule","enablePfDetailDockCollapse","enablePfPrivateCompany","enableHoneyLinks","partnerAARP","enableCGFollowedLatestNews","enableStockPicks","enableStockPicksProduction","enableDockModuleDescriptions","enableSimpleHeaderCheckout","enableDockFooterSettings","enableDigDeeperArticles","enableDigDeeperArticlesWebview","enableDigDeeperPFArticles","enableDigDeeperPFArticlesWebview","enableDigDeeperProviderFiltering","enableMostPopularCCards","enableCreditCardCompare","enableCreditCardCompositeId","enableAffiliateLinkComponent","enableGoogleAnalytics","enableWorkspaceGtmOptionsSignal","enableTransparentChart","disableSustainability","enablePolarisPfReadMoreStream","enableYCPCommentsProfile","enableTransUnionLandingPage","conditonallyDisableTopicFollow","disablePredictionMarketsPolling","enableNewVideoLivePlacement","disableLiveBugOnVideos","enableHomepageV3","enableTopicModularContent","enablePerksHub","enableCreditCardComparePFArticle","enableMortgageCalculatorDirectLink","enableSubsGoldTrial","enablePushly","disableSodarInLinkedInWebview","disableAdsInLinkedInWebview","enableMetaLabDesignHeader","enableMetaLabDesignDock","enableMetaLabDesignFooter","enableMetaLabDesignNewsStream","enableBuildersHub","enableAIHub","enableFoodAndDrinkHub","enableMediaHub","enableAutoEVsHub","enablePartnerHub","enablePartnerHubArticle","enablePartnerHubArticleOrigin","enablePartnerHubArticleMetadata","enablePartnerHubMarketIndicesHeader","enablePartnerHubMetaLabDesignHeader","enablePartnerHubMetaLabDesignDock","enablePartnerHubMetaLabDesignNewsStream","enablePartnerHubNavBranding","enableYahooScoutComscoreTracking","enableGA4CompositeId","enableAlphaSpaceCTA","enableAdRefresh20s","enableQSPCommunityServiceOnEquities","enableGenericHeatMap","enableQSPIndustryHeatmap"],"isDebug":false,"isForScreenshot":false,"isWebview":false,"isLinkedInWebview":false,"theme":"auto","pnrID":"","isError":false,"gucJurisdiction":"","areAdsEnabled":true,"ccpa":{"warning":"","footerSequence":["terms_and_privacy","dashboard"],"links":{"dashboard":{"url":"https://guce.yahoo.com/privacy-dashboard?locale=en-US","label":"Privacy Dashboard","id":"privacy-link-dashboard"},"terms_and_privacy":{"multiurl":true,"label":"${terms_link}Terms${end_link} and ${privacy_link}Privacy Policy${end_link}","urls":{"terms_link":"https://guce.yahoo.com/terms?locale=en-US","privacy_link":"https://guce.yahoo.com/privacy-policy?locale=en-US"},"ids":{"terms_link":"privacy-link-terms-link","privacy_link":"privacy-link-privacy-link"}}}},"yrid":"1kpiob9l69ov8","user":{"age":0,"firstName":null,"gender":"","year":0},"clientVersion":"0.1.13848.1784902211"};})();</script><script>function onRapidAssetLoad(){if(typeof onRapidLoad === "function"){onRapidLoad()}}</script><script>function initFinSearch(){window.FinSearch?.init({"uiConfig":{"isSearchRedesign":true,"isNeoGreen":true,"showStockStory":false},"searchConfig":{"recommendCount":5,"enableCccBoost":true,"enablePrivateCompany":true,"enableCb":false}});}</script><script>!function(){var e={1040:function(e){"use strict";function t(e){return(t="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e})(e)}e.exports=function(){for(var e,n,a=[],s=window,r=s;r;){try{if(r.frames.__tcfapiLocator){e=r;break}}catch(e){}if(r===s.top)break;r=r.parent}e||(function e(){var t=s.document,n=!!s.frames.__tcfapiLocator;if(!n)if(t.body){var a=t.createElement("iframe");a.style.cssText="display:none",a.name="__tcfapiLocator",t.body.appendChild(a)}else setTimeout(e,5);return!n}(),s.__tcfapi=function(){for(var e=arguments.length,t=new Array(e),s=0;s<e;s++)t[s]=arguments[s];if(!t.length)return a;"setGdprApplies"===t[0]?t.length>3&&2===parseInt(t[1],10)&&"boolean"==typeof t[3]&&(n=t[3],"function"==typeof t[2]&&t[2]("set",!0)):"ping"===t[0]?"function"==typeof t[2]&&t[2]({gdprApplies:n,cmpLoaded:!1,cmpStatus:"stub"}):a.push(t)},s.addEventListener("message",(function(e){var n="string"==typeof e.data,a={};if(n)try{a=JSON.parse(e.data)}catch(e){}else a=e.data;var s="object"===t(a)&&null!==a?a.__tcfapiCall:null;s&&window.__tcfapi(s.command,s.version,(function(t,a){var r={__tcfapiReturn:{returnValue:t,success:a,callId:s.callId}};e&&e.source&&e.source.postMessage&&e.source.postMessage(n?JSON.stringify(r):r,"*")}),s.parameter)}),!1))}},5385:function(){"use strict";window.__gpp_addFrame=function(e){if(!window.frames[e])if(document.body){var t=document.createElement("iframe");t.style.cssText="display:none",t.name=e,document.body.appendChild(t)}else window.setTimeout(window.__gpp_addFrame,10,e)},window.__gpp_stub=function(){var e=arguments;if(__gpp.queue=__gpp.queue||[],__gpp.events=__gpp.events||[],!e.length||1==e.length&&"queue"==e[0])return __gpp.queue;if(1==e.length&&"events"==e[0])return __gpp.events;var t=e[0],n=e.length>1?e[1]:null,a=e.length>2?e[2]:null;if("ping"===t)n({gppVersion:"1.1",cmpStatus:"stub",cmpDisplayStatus:"hidden",signalStatus:"not ready",supportedAPIs:["2:tcfeuv2","5:tcfcav1","6:uspv1","7:usnatv1","8:uscav1","9:usvav1","10:uscov1","11:usutv1","12:usctv1"],cmpId:0,sectionList:[],applicableSections:[],gppString:"",parsedSections:{}},!0);else if("addEventListener"===t){"lastId"in __gpp||(__gpp.lastId=0),__gpp.lastId++;var s=__gpp.lastId;__gpp.events.push({id:s,callback:n,parameter:a}),n({eventName:"listenerRegistered",listenerId:s,data:!0,pingData:{gppVersion:"1.1",cmpStatus:"stub",cmpDisplayStatus:"hidden",signalStatus:"not ready",supportedAPIs:["2:tcfeuv2","5:tcfcav1","6:uspv1","7:usnatv1","8:uscav1","9:usvav1","10:uscov1","11:usutv1","12:usctv1"],cmpId:0,sectionList:[],applicableSections:[],gppString:"",parsedSections:{}}},!0)}else if("removeEventListener"===t){for(var r=!1,o=0;o<__gpp.events.length;o++)if(__gpp.events[o].id==a){__gpp.events.splice(o,1),r=!0;break}n({eventName:"listenerRemoved",listenerId:a,data:r,pingData:{gppVersion:"1.1",cmpStatus:"stub",cmpDisplayStatus:"hidden",signalStatus:"not ready",supportedAPIs:["2:tcfeuv2","5:tcfcav1","6:uspv1","7:usnatv1","8:uscav1","9:usvav1","10:uscov1","11:usutv1","12:usctv1"],cmpId:0,sectionList:[],applicableSections:[],gppString:"",parsedSections:{}}},!0)}else"hasSection"===t?n(!1,!0):"getSection"===t||"getField"===t?n(null,!0):__gpp.queue.push([].slice.apply(e))},window.__gpp_msghandler=function(e){var t="string"==typeof e.data;try{var n=t?JSON.parse(e.data):e.data}catch(e){n=null}if("object"==typeof n&&null!==n&&"__gppCall"in n){var a=n.__gppCall;window.__gpp(a.command,(function(n,s){var r={__gppReturn:{returnValue:n,success:s,callId:a.callId}};e.source.postMessage(t?JSON.stringify(r):r,"*")}),"parameter"in a?a.parameter:null,"version"in a?a.version:"1.1")}},"__gpp"in window&&"function"==typeof window.__gpp||(window.__gpp=window.__gpp_stub,window.addEventListener("message",window.__gpp_msghandler,!1),window.__gpp_addFrame("__gppLocator"))},1007:function(e,t,n){"use strict";n.r(t);var a=n(1040);n.n(a)()()},9476:function(){!function(){for(var e,t="__uspapiLocator",n=[],a=window;a;){try{if(a.frames[t]){e=a;break}}catch(e){}if(a===window.top)break;a=a.parent}e||(function e(){var n=window.document;if(!window.frames[t])if(n.body){var a=n.createElement("iframe");a.style.cssText="display:none",a.name=t,n.body.appendChild(a)}else setTimeout(e,5)}(),window.__uspapi=function(){for(var e=arguments.length,t=new Array(e),a=0;a<e;a++)t[a]=arguments[a];if(!t.length)return n;n.push(t)},window.addEventListener("message",(function(e){var t="string"==typeof e.data,n={};try{n=t?JSON.parse(e.data):e.data}catch(e){}var a=n.__uspapiCall;a&&window.__uspapi(a.command,a.version,(function(n,s){var r={__uspapiReturn:{returnValue:n,success:s,callId:a.callId}};t&&(r=JSON.stringify(r)),e&&e.source&&e.source.postMessage(r,"*")}),a.parameter)}),!1))}()}},t={};function n(a){var s=t[a];if(void 0!==s)return s.exports;var r=t[a]={exports:{}};return e[a](r,r.exports,n),r.exports}n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,{a:t}),t},n.d=function(e,t){for(var a in t)n.o(t,a)&&!n.o(e,a)&&Object.defineProperty(e,a,{enumerable:!0,get:t[a]})},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},function(){"use strict";n(9476);!window.document.documentMode&&(n(1007),n(5385))}()}();</script><script>(function(){window.YAHOO=window.YAHOO||{};window.YAHOO.comscore=window.YAHOO.comscore||{"c1":2,"c2":"7241469","cs_fpit":"c","cs_fpdt":"01","c14":-1,"cs_fpdm":"*null"};})();</script><script>
window._nimbusEvLoad = window._nimbusEvLoad || { _player: false };
            function _nimbusSendEVLoadEvent() {
                if (_nimbusEvLoad._player){
                    window.finNeoEVReady = Date.now();
                    window.dispatchEvent(new CustomEvent('NIMBUS_EV_READY',{detail: {}}));
                }
            }
            function onNimbusEVPlayerReady(){_nimbusEvLoad._player = true;_nimbusSendEVLoadEvent();}

In [16]:
print(soup.prettify())

<!DOCTYPE html>
<html class="desktop neo-green dock-upscale" data-color-scheme="auto" data-color-theme-enabled="true" lang="en-US" theme="auto">
 <head>
  <meta charset="utf-8"/>
  <meta content="guce.yahoo.com" name="oath:guce:consent-host"/>
  <link crossorigin="anonymous" href="//s.yimg.com" rel="preconnect"/>
  <link href="//geo.yahoo.com" rel="preconnect"/>
  <link href="//query1.finance.yahoo.com" rel="preconnect"/>
  <link href="//consent.cmp.oath.com" rel="preconnect"/>
  <link as="worker" href="/__rapidworker-1.2.js" rel="preload"/>
  <link href="https://s.yimg.com/uc/finance/webcore/js/_staticFinProtobuf.4ac0aa7cd811394598dc.js" rel="preconnect"/>
  <link href="https://cdn.jsdelivr.net/npm/protobufjs@7.1.2/dist/minimal/protobuf.min.js" rel="preconnect"/>
  <script>
   window.finNeoPageStart = Date.now();
  </script>
  <script>
   (function(){if(!window.YAHOO){window.YAHOO={}};window.YAHOO.context={"consent":{"allowContentPersonalization":true,"allowCrossDeviceMapping":true,"allowFirstPartyAds":true,"allowSellPersonalInfo":true,"canEmbedThirdPartyContent":true,"canSell":true,"consentedVendors":["acast","brightcove","dailymotion","facebook","flourish","giphy","instagram","nbcuniversal","playbuzz","scribblelive","soundcloud","tiktok","vimeo","twitter","youtube","masque"]},"authed":"0","ynet":"0","ssl":"1","spdy":"0","ytee":"0","mode":"normal","tpConsent":true,"site":"finance","adblock":"0","bucket":"","colo":"sg3","device":"desktop","bot":"0","browser":"chrome","app":"unknown","ecma":"modern","environment":"prod","gdpr":false,"lang":"en-US","dir":"ltr","intl":"us","network":"mobile","os":"windows nt","partner":"none","region":"US","time":1784996840401,"tz":"Asia/Kolkata","usercountry":"IN","rmp":"0","webview":"0","feature":["benjiPrefetchAuction2","disableInterstitialUpsells","disableServiceRewrite","disableBack2Classic","disableYPFTaxArticleDisclosure","enable1PVideoTranscript","enableAnalystRatings","enableAPIRedisCaching","enableASArticleChartEmbed","enableCGResponseCaching","enableCalendarEventsCaching","disablePremiumTiersCaching","enableAboutRedirects","enableArticleCSN","enableBestHubs","enableBestCreditCardsPage","enableBestMortgageRatesPage","enableCccBoost","enableCGAuthorFeed","enableCGHomepageV1","enableCGHomepageV2","enableCGNewsStream","enableCGTopicStream","enableCGPersonalFinancePagination","enableCGPfContentLists","enableCGPortfolioNews","enableCGEventsLanding","enableCGShowsLanding","enableCGEventDetail","enableCGShowDetail","enableCGVideosCategory","enableCGVideoHub","enableCGEVPlayer","enableCGArticleFeatures","enableCGPersonalFinanceArticles","enableCGLiveBlog","enableCGSlideshow","enableCGVideoContentPage","enableCGRelatedStreamContent","enableCGFeatureBar","enableCGFeatureBarList","enableCGPartnerHub","enablePolarisPartnerHub","enableChartbeat","enableChatSupport","enableQSPCommunityService","enableCommunityMuteUser","enableQSPCommunityFeedTabs","enableCommunityCustomTakeItDownCopy","enableCorporateActions","enablePremiumAdsCSNStyleHandling","enableCompare","enableContentOfferVertical","enableCompareConvertCurrency","enableConsentAndGTM","enableCrumbRefresh","enableCSN","enableCurrencyConverter","enableDarkMode","enableDidomi","enableDockAddToFollowing","enableDockHomeStream","enableDockPortfolioControl","enableDockFooterAdOnScroll","enableExperimentalDockModules","enableFollow","enableEarningsTranscript","enableEarningsTranscriptAI","enableEntityDiscover","enableEntityDiscoverInStream","enableAICuratedTopicsBatch1","enableHistoricalStockPicks","enableHomeNewsStreamNewsletter","enableImportCSVReview","enableLazyMidCenter2NAds","enableLazyQSP","enableServiceWorker","enableMarketIndicesHeader","enableMarketsLeafHeatMap","enablePartnerHubsInL2Mobile","enableMultiQuote","enableMyMoneyOptIn","enableMyMoneyIntroVideo","enableNcpStreamCaching","enablePfConsistentNav","enableNeoBasicPFs","enableNeoGreen","enableNeoHouseCalcPage","enableNeoInvestmentIdea","enableNeoMortgageCalcPage","enableNeoQSPReportsLeaf","enableNeoResearchReport","enableNimbusSubNav","enableEnhancedScreeners","enableOvernight","enablePartnerDropdownNav","enablePersonalFinanceNewsletterIntegration","enablePersonalFinanceZillowIntegration","enablePfPremium","enablePfStreaming","enablePlaid","enablePinholeScreenshotOGForQuote","enablePlus","enablePolarisSeamlessScrollArticleRecommendations","enablePrivateCompany","enablePrivateCompanySurvey","enableQSP1PNews","enableQSPAiAnalystSheet","enableQSPAiAnalystSheetChatVersionV11","enableQSPAlphaSpaceCTA","enableQSPAnalysisGAAPToggle","enableQSPChartEarnings","enableQSPChartNewShading","enableQSPChartRangeTooltips","enableQSPCryptoLogo","enableQSPEarningsVsRev","enableQSPExpandedEarnings","enableQSPChartsFiscalYear","enableQSPHistoryPlusDownload","enableQSPIPO","enableQSPLiveEarnings","enableQSPHoldingsCard","enableQSPNavIcon","enableQSPQuoteHeaderV2","enableQSPPriceInsightsAnomaly","enableQSPAINewsHeadlines","enableQSPStockPicks","enableQSPStockPicksMF","enableQuoteLookup","enableRecentQuotes","enableResearchHub","enablePersistentScoutDock","enableScreenerCustomColumns","enableIndexHeatmap","enableScreenerHeatMap","enableScreenersCollapseDock","enableScreenersCustomiseResults","enableScreenersSpEarnings","enableScreenersDownload","enableScreenersIndex","enableScreenersExchange","enableSECFiling","enableSessionSnapshot","enableSkipNav","enableSkipToDock","enableSkipToNav","enableSmartAssetMsgA","enableStockPicksTableSort","enableStockPicksTableFiltering","enableStockStoryPfPage","enableStreamInjectionSlot","enableTickerAIInsights","enableTopCryptoAttr","enable24HourCrypto","enableTradeNow","enableAlphaSpaceL2","enableAlphaSpaceStandaloneRedirect","enableUpgradeBadgeDesign","enableUnifiedContentStream","enableVideoInHero","enableDockQuoteEventsModule","enablePfDetailDockCollapse","enablePfPrivateCompany","enableHoneyLinks","partnerAARP","enableCGFollowedLatestNews","enableStockPicks","enableStockPicksProduction","enableDockModuleDescriptions","enableSimpleHeaderCheckout","enableDockFooterSettings","enableDigDeeperArticles","enableDigDeeperArticlesWebview","enableDigDeeperPFArticles","enableDigDeeperPFArticlesWebview","enableDigDeeperProviderFiltering","enableMostPopularCCards","enableCreditCardCompare","enableCreditCardCompositeId","enableAffiliateLinkComponent","enableGoogleAnalytics","enableWorkspaceGtmOptionsSignal","enableTransparentChart","disableSustainability","enablePolarisPfReadMoreStream","enableYCPCommentsProfile","enableTransUnionLandingPage","conditonallyDisableTopicFollow","disablePredictionMarketsPolling","enableNewVideoLivePlacement","disableLiveBugOnVideos","enableHomepageV3","enableTopicModularContent","enablePerksHub","enableCreditCardComparePFArticle","enableMortgageCalculatorDirectLink","enableSubsGoldTrial","enablePushly","disableSodarInLinkedInWebview","disableAdsInLinkedInWebview","enableMetaLabDesignHeader","enableMetaLabDesignDock","enableMetaLabDesignFooter","enableMetaLabDesignNewsStream","enableBuildersHub","enableAIHub","enableFoodAndDrinkHub","enableMediaHub","enableAutoEVsHub","enablePartnerHub","enablePartnerHubArticle","enablePartnerHubArticleOrigin","enablePartnerHubArticleMetadata","enablePartnerHubMarketIndicesHeader","enablePartnerHubMetaLabDesignHeader","enablePartnerHubMetaLabDesignDock","enablePartnerHubMetaLabDesignNewsStream","enablePartnerHubNavBranding","enableYahooScoutComscoreTracking","enableGA4CompositeId","enableAlphaSpaceCTA","enableAdRefresh20s","enableQSPCommunityServiceOnEquities","enableGenericHeatMap","enableQSPIndustryHeatmap"],"isDebug":false,"isForScreenshot":false,"isWebview":false,"isLinkedInWebview":false,"theme":"auto","pnrID":"","isError":false,"gucJurisdiction":"","areAdsEnabled":true,"ccpa":{"warning":"","footerSequence":["terms_and_privacy","dashboard"],"links":{"dashboard":{"url":"https://guce.yahoo.com/privacy-dashboard?locale=en-US","label":"Privacy Dashboard","id":"privacy-link-dashboard"},"terms_and_privacy":{"multiurl":true,"label":"${terms_link}Terms${end_link} and ${privacy_link}Privacy Policy${end_link}","urls":{"terms_link":"https://guce.yahoo.com/terms?locale=en-US","privacy_link":"https://guce.yahoo.com/privacy-policy?locale=en-US"},"ids":{"terms_link":"privacy-link-terms-link","privacy_link":"privacy-link-privacy-link"}}}},"yrid":"1kpiob9l69ov8","user":{"age":0,"firstName":null,"gender":"","year":0},"clientVersion":"0.1.13848.1784902211"};})();
  </script>
  <script>
   function onRapidAssetLoad(){if(typeof onRapidLoad === "function"){onRapidLoad()}}
  </script>
  <script>
   function initFinSearch(){window.FinSearch?.init({"uiConfig":{"isSearchRedesign":true,"isNeoGreen":true,"showStockStory":false},"searchConfig":{"recommendCount":5,"enableCccBoost":true,"enablePrivateCompany":true,"enableCb":false}});}
  </script>
  <script>
   !function(){var e={1040:function(e){"use strict";function t(e){return(t="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e})(e)}e.exports=function(){for(var e,n,a=[],s=window,r=s;r;){try{if(r.frames.__tcfapiLocator){e=r;break}}catch(e){}if(r===s.top)break;r=r.parent}e||(function e(){var t=s.document,n=!!s.frames.__tcfapiLocator;if(!n)if(t.body){var a=t.createElement("iframe");a.style.cssText="display:none",a.name="__tcfapiLocator",t.body.appendChild(a)}else setTimeout(e,5);return!n}(),s.__tcfapi=function(){for(var e=arguments.length,t=new Array(e),s=0;s<e;s++)t[s]=arguments[s];if(!t.length)return a;"setGdprApplies"===t[0]?t.length>3&&2===parseInt(t[1],10)&&"boolean"==typeof t[3]&&(n=t[3],"function"==typeof t[2]&&t[2]("set",!0)):"ping"===t[0]?"function"==typeof t[2]&&t[2]({gdprApplies:n,cmpLoaded:!1,cmpStatus:"stub"}):a.push(t)},s.addEventListener("message",(function(e){var n="string"==typeof e.data,a={};if(n)try{a=JSON.parse(e.data)}catch(e){}else a=e.data;var s="object"===t(a)&&null!==a?a.__tcfapiCall:null;s&&window.__tcfapi(s.command,s.version,(function(t,a){var r={__tcfapiReturn:{returnValue:t,success:a,callId:s.callId}};e&&e.source&&e.source.postMessage&&e.source.postMessage(n?JSON.stringify(r):r,"*")}),s.parameter)}),!1))}},5385:function(){"use strict";window.__gpp_addFrame=function(e){if(!window.frames[e])if(document.body){var t=document.createElement("iframe");t.style.cssText="display:none",t.name=e,document.body.appendChild(t)}else window.setTimeout(window.__gpp_addFrame,10,e)},window.__gpp_stub=function(){var e=arguments;if(__gpp.queue=__gpp.queue||[],__gpp.events=__gpp.events||[],!e.length||1==e.length&&"queue"==e[0])return __gpp.queue;if(1==e.length&&"events"==e[0])return __gpp.events;var t=e[0],n=e.length>1?e[1]:null,a=e.length>2?e[2]:null;if("ping"===t)n({gppVersion:"1.1",cmpStatus:"stub",cmpDisplayStatus:"hidden",signalStatus:"not ready",supportedAPIs:["2:tcfeuv2","5:tcfcav1","6:uspv1","7:usnatv1","8:uscav1","9:usvav1","10:uscov1","11:usutv1","12:usctv1"],cmpId:0,sectionList:[],applicableSections:[],gppString:"",parsedSections:{}},!0);else if("addEventListener"===t){"lastId"in __gpp||(__gpp.lastId=0),__gpp.lastId++;var s=__gpp.lastId;__gpp.events.push({id:s,callback:n,parameter:a}),n({eventName:"listenerRegistered",listenerId:s,data:!0,pingData:{gppVersion:"1.1",cmpStatus:"stub",cmpDisplayStatus:"hidden",signalStatus:"not ready",supportedAPIs:["2:tcfeuv2","5:tcfcav1","6:uspv1","7:usnatv1","8:uscav1","9:usvav1","10:uscov1","11:usutv1","12:usctv1"],cmpId:0,sectionList:[],applicableSections:[],gppString:"",parsedSections:{}}},!0)}else if("removeEventListener"===t){for(var r=!1,o=0;o<__gpp.events.length;o++)if(__gpp.events[o].id==a){__gpp.events.splice(o,1),r=!0;break}n({eventName:"listenerRemoved",listenerId:a,data:r,pingData:{gppVersion:"1.1",cmpStatus:"stub",cmpDisplayStatus:"hidden",signalStatus:"not ready",supportedAPIs:["2:tcfeuv2","5:tcfcav1","6:uspv1","7:usnatv1","8:uscav1","9:usvav1","10:uscov1","11:usutv1","12:usctv1"],cmpId:0,sectionList:[],applicableSections:[],gppString:"",parsedSections:{}}},!0)}else"hasSection"===t?n(!1,!0):"getSection"===t||"getField"===t?n(null,!0):__gpp.queue.push([].slice.apply(e))},window.__gpp_msghandler=function(e){var t="string"==typeof e.data;try{var n=t?JSON.parse(e.data):e.data}catch(e){n=null}if("object"==typeof n&&null!==n&&"__gppCall"in n){var a=n.__gppCall;window.__gpp(a.command,(function(n,s){var r={__gppReturn:{returnValue:n,success:s,callId:a.callId}};e.source.postMessage(t?JSON.stringify(r):r,"*")}),"parameter"in a?a.parameter:null,"version"in a?a.version:"1.1")}},"__gpp"in window&&"function"==typeof window.__gpp||(window.__gpp=window.__gpp_stub,window.addEventListener("message",window.__gpp_msghandler,!1),window.__gpp_addFrame("__gppLocator"))},1007:function(e,t,n){"use strict";n.r(t);var a=n(1040);n.n(a)()()},9476:function(){!function(){for(var e,t="__uspapiLocator",n=[],a=window;a;){try{if(a.frames[t]){e=a;break}}catch(e){}if(a===window.top)break;a=a.parent}e||(function e(){var n=window.document;if(!window.frames[t])if(n.body){var a=n.createElement("iframe");a.style.cssText="display:none",a.name=t,n.body.appendChild(a)}else setTimeout(e,5)}(),window.__uspapi=function(){for(var e=arguments.length,t=new Array(e),a=0;a<e;a++)t[a]=arguments[a];if(!t.length)return n;n.push(t)},window.addEventListener("message",(function(e){var t="string"==typeof e.data,n={};try{n=t?JSON.parse(e.data):e.data}catch(e){}var a=n.__uspapiCall;a&&window.__uspapi(a.command,a.version,(function(n,s){var r={__uspapiReturn:{returnValue:n,success:s,callId:a.callId}};t&&(r=JSON.stringify(r)),e&&e.source&&e.source.postMessage(r,"*")}),a.parameter)}),!1))}()}},t={};function n(a){var s=t[a];if(void 0!==s)return s.exports;var r=t[a]={exports:{}};return e[a](r,r.exports,n),r.exports}n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,{a:t}),t},n.d=function(e,t){for(var a in t)n.o(t,a)&&!n.o(e,a)&&Object.defineProperty(e,a,{enumerable:!0,get:t[a]})},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},function(){"use strict";n(9476);!window.document.documentMode&&(n(1007),n(5385))}()}();
  </script>
  <script>
   (function(){window.YAHOO=window.YAHOO||{};window.YAHOO.comscore=window.YAHOO.comscore||{"c1":2,"c2":"7241469","cs_fpit":"c","cs_fpdt":"01","c14":-1,"cs_fpdm":"*null"};})();
  </script>
  <script>
   window._nimbusEvLoad = window._nimbusEvLoad || { _player: false };
            function _nimbusSendEVLoadEvent() {
                if (_nimbusEvLoad._player){
                    window.finNeoEVReady = Date.now();
                    window.dispatchEvent(new CustomEvent('NIMBUS_EV_READY',{detail: {}}));
                }
            }
            function onNimbusEVPlayerReady(){_nimbusEvLoad._player = true;_nimbusSendEVLoadEvent();}
  </script>
  <script type="module">

# Locate Quote Containers


Find all quote cards using their HTML class.

In [17]:
mutual_funds= soup.find_all( "div", class_='container yf-1nql2a7')
len(mutual_funds)
mutual_funds

[<div class="container yf-1nql2a7" data-testid="markets-table-wrapper"> <div style="display: contents; --select-min-width:fit-content; --select-max-height:30dvh; --menu-small-max-height:30dvh;"><div class="tabList l1 tw-max-w-full tw-overflow-x-scroll yf-664qgj" data-testid="tabs-container" role="tablist"> <a aria-selected="false" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Top Gainers"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Top%20Gainers" href="/markets/mutualfunds/gainers/" id="tab-gainers" role="tab" tabindex="-1" title="Top Gainers">Top Gainers  </a> <a aria-selected="false" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Top Losers"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Top%20Losers" href="/markets/mutualfunds/losers/" id="tab-losers" role="tab" tabindex="-1" title="Top Losers">Top Losers  </a> <a aria-selected="false" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Top Performing"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Top%20Performing" href="/markets/mutualfunds/top-performing/" id="tab-top-performing" role="tab" tabindex="-1" title="Top Performing">Top Performing  </a> <a aria-selected="false" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Best Historical Performance"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Best%20Historical%20Performance" href="/markets/mutualfunds/best-historical-performance/" id="tab-best-historical-performance" role="tab" tabindex="-1" title="Best Historical Performance">Best Historical Performance  </a> <a aria-selected="true" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Top Mutual Funds"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Top%20Mutual%20Funds" href="/markets/mutualfunds/top/" id="tab-top" role="tab" tabindex="0" title="Top Mutual Funds">Top Mutual Funds  </a></div> </div> <div class="tableContainer yf-1nql2a7"><div class="table-container cs-regular tw-border-none yf-1ilt7hv" data-testid="data-table-v2"><table class="yf-1ilt7hv bd"><thead class="yf-1ilt7hv"><tr class="yf-1ilt7hv"> <th class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv so lpin shad" data-testid-header="ticker"><div class="colCont yf-1ilt7hv"> Symbol </div> </th> <th class="leftAlignHeader companyName yf-1ilt7hv so" data-testid-header="companyshortname.raw"><div class="colCont yf-1ilt7hv"> Name </div> </th> <th class="yf-1ilt7hv so" data-testid-header="intradayprice"><div class="colCont yf-1ilt7hv"> <div class="container yf-1d5e06g"><span>Price</span> </div> </div> </th> <th class="yf-1ilt7hv so" data-testid-header="intradaypricechange"><div class="colCont yf-1ilt7hv"> Change </div> </th> <th class="yf-1ilt7hv so sorted" data-testid-header="percentchange"><div class="colCont yf-1ilt7hv"><div aria-hidden="true" class="icon fin-icon inherit-icn sz-medium yf-15ilbqr"><!-- HTML_TAG_START --><svg viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M16.59 8.59 12 13.17 7.41 8.59 6 10l6 6 6-6z"></path></svg><!-- HTML_TAG_END --> </div> Change % </div> </th> <th class="yf-1ilt7hv so" data-testid-header="fiftydaymovingavg"><div class="colCont yf-1ilt7hv"> <div class="yf-10yevti"><span>50 Day </span><span>Average </span> </div> </div> </th> <th class="yf-1ilt7hv so" data-testid-header="twohundreddaymovingavg"><div class="colCont yf-1ilt7hv"> <div class="yf-10yevti"><span>200 Day </span><span>Average </span> </div> </div> </th> <th class="yf-1ilt7hv so" data-testid-header="trailing_3m_return"><div class="colCont yf-1ilt7hv"> <div class="yf-10yevti"><span>3 Month </span><span>Return </span> </div> </div> </th> <th class="yf-1ilt7hv so" data-testid-header="trailing_ytd_return"><div class="colCont yf-1ilt7hv"> YTD Return </div> </th> <th class="yf-1ilt7hv so" data-testid-header="fiftytwowkpercentchange"><div class="colCont yf-1ilt7hv"> <div class="yf-10yevti"><span>52 Wk </span><span>Change % </span> </div> </div> </th> <th class="yf-1ilt7hv" data-testid-header="fiftyTwoWeekRange"><div class="colCont yf-1ilt7hv"> 52 Wk Range </div> </th> </tr></thead> <tbody> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="0"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Invenomic Super Institutional" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"BIVSX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:BIVSX;source:mutualfunds-datatable%20default" href="/quote/BIVSX/" title="Invenomic Super Institutional"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">BIVSX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="Invenomic Super Institutional">Invenomic Super Institutional </div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-7ua2fk base" data-testid="change">18.11 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="1.02">+1.02</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="5.9684024">(+5.97%)</fin-streamer></div></div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+1.02 </span> </td> <td class="yf-1ilt7hv" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+5.97% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftydaymovingavg" style="--_depth: false;">      16.12 </td> <td class="yf-1ilt7hv" data-testid-cell="twohundreddaymovingavg" style="--_depth: false;">      17.11 </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_3m_return" style="--_depth: false;"> <span class="txt-negative yf-7ua2fk base" data-testid="colorChange">-0.35% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_ytd_return" style="--_depth: false;"> <span class="txt-negative yf-7ua2fk base" data-testid="colorChange">-12.01% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+2.09% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 110.00px;width: 0px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 107px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>14.01</span> <span>19.16</span></div> </div> </td></tr> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="1"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Cohen &amp; Steers Realty Shares R" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"CSJRX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:CSJRX;source:mutualfunds-datatable%20default" href="/quote/CSJRX/" title="Cohen &amp; Steers Realty Shares R"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">CSJRX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="Cohen &amp; Steers Realty Shares R">Cohen &amp; Steers Realty Shares R </div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-7ua2fk base" data-testid="change">77.69 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="1.93">+1.93</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="2.5475183">(+2.55%)</fin-streamer></div></div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+1.93 </span> </td> <td class="yf-1ilt7hv" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+2.55% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftydaymovingavg" style="--_depth: false;">      74.79 </td> <td class="yf-1ilt7hv" data-testid-cell="twohundreddaymovingavg" style="--_depth: false;">      70.23 </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_3m_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+3.44% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_ytd_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+12.28% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+13.95% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 137.00px;width: 0px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 134px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>65.03</span> <span>77.69</span></div> </div> </td></tr> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="2"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Cohen &amp; Steers Realty Shares I" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"CSJIX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:CSJIX;source:mutualfunds-datatable%20default" href="/quote/CSJIX/" title="Cohen &amp; Steers Realty Shares I"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">CSJIX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="Cohen &amp; Steers Realty Shares I">Cohen &amp; Steers Realty Shares I </div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-7ua2fk base" data-testid="change">77.44 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="1.92">+1.92</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="2.5423727">(+2.54%)</fin-streamer></div></div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+1.92 </span> </td> <td class="yf-1ilt7hv" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+2.54% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftydaymovingavg" style="--_depth: false;">      74.57 </td> <td class="yf-1ilt7hv" data-testid-cell="twohundreddaymovingavg" style="--_depth: false;">      70.02 </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_3m_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+3.44% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_ytd_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+12.28% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+13.92% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 137.00px;width: 0px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 134px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>64.81</span> <span>77.44</span></div> </div> </td></tr> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="3"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Cohen &amp; Steers Realty Shares L" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"CSRSX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:CSRSX;source:mutualfunds-datatable%20default" href="/quote/CSRSX/" title="Cohen &amp; Steers Realty Shares L"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">CSRSX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="Cohen &amp; Steers Realty Shares L">Cohen &amp; Steers Realty Shares L </div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-7ua2fk base" data-testid="change">77.47 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="1.92">+1.92</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="2.5413632">(+2.54%)</fin-streamer></div></div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+1.92 </span> </td> <td class="yf-1ilt7hv" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+2.54% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftydaymovingavg" style="--_depth: false;">      74.60 </td> <td class="yf-1ilt7hv" data-testid-cell="twohundreddaymovingavg" style="--_depth: false;">      70.05 </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_3m_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+7.19% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_ytd_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+19.66% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+13.91% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 137.00px;width: 0px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 134px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>64.83</span> <span>77.47</span></div> </div> </td></tr> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="4"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Cohen &amp; Steers Instl Realty Shares" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"CSRIX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:CSRIX;source:mutualfunds-datatable%20default" href="/quote/CSRIX/" title="Cohen &amp; Steers Instl Realty Shares"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">CSRIX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="c

# Verify Scraped Elements


Display the first quote container to understand its HTML structure.

In [18]:
print(soup.find("div",class_="container yf-1nql2a7"))

<div class="container yf-1nql2a7" data-testid="markets-table-wrapper"> <div style="display: contents; --select-min-width:fit-content; --select-max-height:30dvh; --menu-small-max-height:30dvh;"><div class="tabList l1 tw-max-w-full tw-overflow-x-scroll yf-664qgj" data-testid="tabs-container" role="tablist"> <a aria-selected="false" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Top Gainers"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Top%20Gainers" href="/markets/mutualfunds/gainers/" id="tab-gainers" role="tab" tabindex="-1" title="Top Gainers">Top Gainers  </a> <a aria-selected="false" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Top Losers"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Top%20Losers" href="/markets/mutualfunds/losers/" id="tab-losers" role="tab" tabindex="-1" title="Top Losers">Top Losers  </a> <a aria-selected="false" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Top Performing"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Top%20Performing" href="/markets/mutualfunds/top-performing/" id="tab-top-performing" role="tab" tabindex="-1" title="Top Performing">Top Performing  </a> <a aria-selected="false" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Best Historical Performance"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Best%20Historical%20Performance" href="/markets/mutualfunds/best-historical-performance/" id="tab-best-historical-performance" role="tab" tabindex="-1" title="Best Historical Performance">Best Historical Performance  </a> <a aria-selected="true" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Top Mutual Funds"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Top%20Mutual%20Funds" href="/markets/mutualfunds/top/" id="tab-top" role="tab" tabindex="0" title="Top Mutual Funds">Top Mutual Funds  </a></div> </div> <div class="tableContainer yf-1nql2a7"><div class="table-container cs-regular tw-border-none yf-1ilt7hv" data-testid="data-table-v2"><table class="yf-1ilt7hv bd"><thead class="yf-1ilt7hv"><tr class="yf-1ilt7hv"> <th class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv so lpin shad" data-testid-header="ticker"><div class="colCont yf-1ilt7hv"> Symbol </div> </th> <th class="leftAlignHeader companyName yf-1ilt7hv so" data-testid-header="companyshortname.raw"><div class="colCont yf-1ilt7hv"> Name </div> </th> <th class="yf-1ilt7hv so" data-testid-header="intradayprice"><div class="colCont yf-1ilt7hv"> <div class="container yf-1d5e06g"><span>Price</span> </div> </div> </th> <th class="yf-1ilt7hv so" data-testid-header="intradaypricechange"><div class="colCont yf-1ilt7hv"> Change </div> </th> <th class="yf-1ilt7hv so sorted" data-testid-header="percentchange"><div class="colCont yf-1ilt7hv"><div aria-hidden="true" class="icon fin-icon inherit-icn sz-medium yf-15ilbqr"><!-- HTML_TAG_START --><svg viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M16.59 8.59 12 13.17 7.41 8.59 6 10l6 6 6-6z"></path></svg><!-- HTML_TAG_END --> </div> Change % </div> </th> <th class="yf-1ilt7hv so" data-testid-header="fiftydaymovingavg"><div class="colCont yf-1ilt7hv"> <div class="yf-10yevti"><span>50 Day </span><span>Average </span> </div> </div> </th> <th class="yf-1ilt7hv so" data-testid-header="twohundreddaymovingavg"><div class="colCont yf-1ilt7hv"> <div class="yf-10yevti"><span>200 Day </span><span>Average </span> </div> </div> </th> <th class="yf-1ilt7hv so" data-testid-header="trailing_3m_return"><div class="colCont yf-1ilt7hv"> <div class="yf-10yevti"><span>3 Month </span><span>Return </span> </div> </div> </th> <th class="yf-1ilt7hv so" data-testid-header="trailing_ytd_return"><div class="colCont yf-1ilt7hv"> YTD Return </div> </th> <th class="yf-1ilt7hv so" data-testid-header="fiftytwowkpercentchange"><div class="colCont yf-1ilt7hv"> <div class="yf-10yevti"><span>52 Wk </span><span>Change % </span> </div> </div> </th> <th class="yf-1ilt7hv" data-testid-header="fiftyTwoWeekRange"><div class="colCont yf-1ilt7hv"> 52 Wk Range </div> </th> </tr></thead> <tbody> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="0"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Invenomic Super Institutional" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"BIVSX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:BIVSX;source:mutualfunds-datatable%20default" href="/quote/BIVSX/" title="Invenomic Super Institutional"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">BIVSX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="Invenomic Super Institutional">Invenomic Super Institutional </div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-7ua2fk base" data-testid="change">18.11 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="1.02">+1.02</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="5.9684024">(+5.97%)</fin-streamer></div></div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+1.02 </span> </td> <td class="yf-1ilt7hv" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+5.97% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftydaymovingavg" style="--_depth: false;">      16.12 </td> <td class="yf-1ilt7hv" data-testid-cell="twohundreddaymovingavg" style="--_depth: false;">      17.11 </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_3m_return" style="--_depth: false;"> <span class="txt-negative yf-7ua2fk base" data-testid="colorChange">-0.35% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_ytd_return" style="--_depth: false;"> <span class="txt-negative yf-7ua2fk base" data-testid="colorChange">-12.01% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+2.09% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 110.00px;width: 0px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 107px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>14.01</span> <span>19.16</span></div> </div> </td></tr> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="1"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Cohen &amp; Steers Realty Shares R" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"CSJRX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:CSJRX;source:mutualfunds-datatable%20default" href="/quote/CSJRX/" title="Cohen &amp; Steers Realty Shares R"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">CSJRX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="Cohen &amp; Steers Realty Shares R">Cohen &amp; Steers Realty Shares R </div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-7ua2fk base" data-testid="change">77.69 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="1.93">+1.93</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="2.5475183">(+2.55%)</fin-streamer></div></div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+1.93 </span> </td> <td class="yf-1ilt7hv" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+2.55% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftydaymovingavg" style="--_depth: false;">      74.79 </td> <td class="yf-1ilt7hv" data-testid-cell="twohundreddaymovingavg" style="--_depth: false;">      70.23 </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_3m_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+3.44% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_ytd_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+12.28% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+13.95% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 137.00px;width: 0px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 134px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>65.03</span> <span>77.69</span></div> </div> </td></tr> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="2"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Cohen &amp; Steers Realty Shares I" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"CSJIX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:CSJIX;source:mutualfunds-datatable%20default" href="/quote/CSJIX/" title="Cohen &amp; Steers Realty Shares I"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">CSJIX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="Cohen &amp; Steers Realty Shares I">Cohen &amp; Steers Realty Shares I </div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-7ua2fk base" data-testid="change">77.44 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="1.92">+1.92</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="2.5423727">(+2.54%)</fin-streamer></div></div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+1.92 </span> </td> <td class="yf-1ilt7hv" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+2.54% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftydaymovingavg" style="--_depth: false;">      74.57 </td> <td class="yf-1ilt7hv" data-testid-cell="twohundreddaymovingavg" style="--_depth: false;">      70.02 </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_3m_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+3.44% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_ytd_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+12.28% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+13.92% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 137.00px;width: 0px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 134px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>64.81</span> <span>77.44</span></div> </div> </td></tr> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="3"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Cohen &amp; Steers Realty Shares L" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"CSRSX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:CSRSX;source:mutualfunds-datatable%20default" href="/quote/CSRSX/" title="Cohen &amp; Steers Realty Shares L"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">CSRSX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="Cohen &amp; Steers Realty Shares L">Cohen &amp; Steers Realty Shares L </div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-7ua2fk base" data-testid="change">77.47 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="1.92">+1.92</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="2.5413632">(+2.54%)</fin-streamer></div></div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+1.92 </span> </td> <td class="yf-1ilt7hv" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+2.54% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftydaymovingavg" style="--_depth: false;">      74.60 </td> <td class="yf-1ilt7hv" data-testid-cell="twohundreddaymovingavg" style="--_depth: false;">      70.05 </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_3m_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+7.19% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_ytd_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+19.66% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+13.91% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 137.00px;width: 0px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 134px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>64.83</span> <span>77.47</span></div> </div> </td></tr> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="4"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Cohen &amp; Steers Instl Realty Shares" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"CSRIX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:CSRIX;source:mutualfunds-datatable%20default" href="/quote/CSRIX/" title="Cohen &amp; Steers Instl Realty Shares"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">CSRIX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="co

# Display All Quote Containers


Print all the quote elements extracted from the webpage.

In [19]:
print(mutual_funds)

[<div class="container yf-1nql2a7" data-testid="markets-table-wrapper"> <div style="display: contents; --select-min-width:fit-content; --select-max-height:30dvh; --menu-small-max-height:30dvh;"><div class="tabList l1 tw-max-w-full tw-overflow-x-scroll yf-664qgj" data-testid="tabs-container" role="tablist"> <a aria-selected="false" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Top Gainers"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Top%20Gainers" href="/markets/mutualfunds/gainers/" id="tab-gainers" role="tab" tabindex="-1" title="Top Gainers">Top Gainers  </a> <a aria-selected="false" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Top Losers"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Top%20Losers" href="/markets/mutualfunds/losers/" id="tab-losers" role="tab" tabindex="-1" title="Top Losers">Top Losers  </a> <a aria-selected="false" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Top Performing"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Top%20Performing" href="/markets/mutualfunds/top-performing/" id="tab-top-performing" role="tab" tabindex="-1" title="Top Performing">Top Performing  </a> <a aria-selected="false" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Best Historical Performance"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Best%20Historical%20Performance" href="/markets/mutualfunds/best-historical-performance/" id="tab-best-historical-performance" role="tab" tabindex="-1" title="Best Historical Performance">Best Historical Performance  </a> <a aria-selected="true" class="tabBtn l1 yf-664qgj" data-yga='{"yLinkElement":"tab","yLinkElementType":"btn","yModuleName":"","yLinkText":"Top Mutual Funds"}' data-ylk="elm:tab;elmt:btn;itc:1;sec:;slk:Top%20Mutual%20Funds" href="/markets/mutualfunds/top/" id="tab-top" role="tab" tabindex="0" title="Top Mutual Funds">Top Mutual Funds  </a></div> </div> <div class="tableContainer yf-1nql2a7"><div class="table-container cs-regular tw-border-none yf-1ilt7hv" data-testid="data-table-v2"><table class="yf-1ilt7hv bd"><thead class="yf-1ilt7hv"><tr class="yf-1ilt7hv"> <th class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv so lpin shad" data-testid-header="ticker"><div class="colCont yf-1ilt7hv"> Symbol </div> </th> <th class="leftAlignHeader companyName yf-1ilt7hv so" data-testid-header="companyshortname.raw"><div class="colCont yf-1ilt7hv"> Name </div> </th> <th class="yf-1ilt7hv so" data-testid-header="intradayprice"><div class="colCont yf-1ilt7hv"> <div class="container yf-1d5e06g"><span>Price</span> </div> </div> </th> <th class="yf-1ilt7hv so" data-testid-header="intradaypricechange"><div class="colCont yf-1ilt7hv"> Change </div> </th> <th class="yf-1ilt7hv so sorted" data-testid-header="percentchange"><div class="colCont yf-1ilt7hv"><div aria-hidden="true" class="icon fin-icon inherit-icn sz-medium yf-15ilbqr"><!-- HTML_TAG_START --><svg viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M16.59 8.59 12 13.17 7.41 8.59 6 10l6 6 6-6z"></path></svg><!-- HTML_TAG_END --> </div> Change % </div> </th> <th class="yf-1ilt7hv so" data-testid-header="fiftydaymovingavg"><div class="colCont yf-1ilt7hv"> <div class="yf-10yevti"><span>50 Day </span><span>Average </span> </div> </div> </th> <th class="yf-1ilt7hv so" data-testid-header="twohundreddaymovingavg"><div class="colCont yf-1ilt7hv"> <div class="yf-10yevti"><span>200 Day </span><span>Average </span> </div> </div> </th> <th class="yf-1ilt7hv so" data-testid-header="trailing_3m_return"><div class="colCont yf-1ilt7hv"> <div class="yf-10yevti"><span>3 Month </span><span>Return </span> </div> </div> </th> <th class="yf-1ilt7hv so" data-testid-header="trailing_ytd_return"><div class="colCont yf-1ilt7hv"> YTD Return </div> </th> <th class="yf-1ilt7hv so" data-testid-header="fiftytwowkpercentchange"><div class="colCont yf-1ilt7hv"> <div class="yf-10yevti"><span>52 Wk </span><span>Change % </span> </div> </div> </th> <th class="yf-1ilt7hv" data-testid-header="fiftyTwoWeekRange"><div class="colCont yf-1ilt7hv"> 52 Wk Range </div> </th> </tr></thead> <tbody> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="0"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Invenomic Super Institutional" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"BIVSX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:BIVSX;source:mutualfunds-datatable%20default" href="/quote/BIVSX/" title="Invenomic Super Institutional"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">BIVSX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="Invenomic Super Institutional">Invenomic Super Institutional </div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-7ua2fk base" data-testid="change">18.11 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="1.02">+1.02</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="5.9684024">(+5.97%)</fin-streamer></div></div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+1.02 </span> </td> <td class="yf-1ilt7hv" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+5.97% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftydaymovingavg" style="--_depth: false;">      16.12 </td> <td class="yf-1ilt7hv" data-testid-cell="twohundreddaymovingavg" style="--_depth: false;">      17.11 </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_3m_return" style="--_depth: false;"> <span class="txt-negative yf-7ua2fk base" data-testid="colorChange">-0.35% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_ytd_return" style="--_depth: false;"> <span class="txt-negative yf-7ua2fk base" data-testid="colorChange">-12.01% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+2.09% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 110.00px;width: 0px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 107px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>14.01</span> <span>19.16</span></div> </div> </td></tr> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="1"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Cohen &amp; Steers Realty Shares R" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"CSJRX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:CSJRX;source:mutualfunds-datatable%20default" href="/quote/CSJRX/" title="Cohen &amp; Steers Realty Shares R"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">CSJRX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="Cohen &amp; Steers Realty Shares R">Cohen &amp; Steers Realty Shares R </div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-7ua2fk base" data-testid="change">77.69 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="1.93">+1.93</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="2.5475183">(+2.55%)</fin-streamer></div></div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+1.93 </span> </td> <td class="yf-1ilt7hv" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+2.55% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftydaymovingavg" style="--_depth: false;">      74.79 </td> <td class="yf-1ilt7hv" data-testid-cell="twohundreddaymovingavg" style="--_depth: false;">      70.23 </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_3m_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+3.44% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_ytd_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+12.28% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+13.95% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 137.00px;width: 0px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 134px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>65.03</span> <span>77.69</span></div> </div> </td></tr> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="2"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Cohen &amp; Steers Realty Shares I" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"CSJIX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:CSJIX;source:mutualfunds-datatable%20default" href="/quote/CSJIX/" title="Cohen &amp; Steers Realty Shares I"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">CSJIX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="Cohen &amp; Steers Realty Shares I">Cohen &amp; Steers Realty Shares I </div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-7ua2fk base" data-testid="change">77.44 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="1.92">+1.92</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="2.5423727">(+2.54%)</fin-streamer></div></div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+1.92 </span> </td> <td class="yf-1ilt7hv" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+2.54% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftydaymovingavg" style="--_depth: false;">      74.57 </td> <td class="yf-1ilt7hv" data-testid-cell="twohundreddaymovingavg" style="--_depth: false;">      70.02 </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_3m_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+3.44% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_ytd_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+12.28% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+13.92% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 137.00px;width: 0px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 134px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>64.81</span> <span>77.44</span></div> </div> </td></tr> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="3"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Cohen &amp; Steers Realty Shares L" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"CSRSX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:CSRSX;source:mutualfunds-datatable%20default" href="/quote/CSRSX/" title="Cohen &amp; Steers Realty Shares L"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">CSRSX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="companyshortname.raw" style="--_depth: false;"> <div class="leftAlignHeader companyName yf-362rys enableMaxWidth" title="Cohen &amp; Steers Realty Shares L">Cohen &amp; Steers Realty Shares L </div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradayprice" style="--_depth: false;"> <div class=""> <span class="yf-7ua2fk base" data-testid="change">77.47 </span> <div class="hide-desktop hide-mw txt-positive"><fin-streamer active="" data-field="regularMarketChange" data-test="colorChange" data-trend="txt" data-value="1.92">+1.92</fin-streamer> <fin-streamer active="" data-field="regularMarketChangePercent" data-template="({fmt})" data-test="colorChange" data-trend="txt" data-value="2.5413632">(+2.54%)</fin-streamer></div></div> </td> <td class="yf-1ilt7hv" data-testid-cell="intradaypricechange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+1.92 </span> </td> <td class="yf-1ilt7hv" data-testid-cell="percentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+2.54% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftydaymovingavg" style="--_depth: false;">      74.60 </td> <td class="yf-1ilt7hv" data-testid-cell="twohundreddaymovingavg" style="--_depth: false;">      70.05 </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_3m_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+7.19% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="trailing_ytd_return" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+19.66% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftytwowkpercentchange" style="--_depth: false;"> <span class="txt-positive yf-7ua2fk base" data-testid="colorChange">+13.91% </span> </td> <td class="yf-1ilt7hv" data-testid-cell="fiftyTwoWeekRange" style="--_depth: false;"> <div aria-label="Graph showing stock performance over fifty two week range" class="container yf-wummfw" role="img"><div class="line yf-wummfw" style="top: 11px;height: 2px;"><div class="candle yf-wummfw" style="top: 0;height: 2px;left: 137.00px;width: 0px;"></div> <svg class="yf-wummfw" height="10" style="top: -12px; left: 134px;" viewbox="0 0 80 110" width="8" xmlns="http://www.w3.org/2000/svg"><path d="M 0 40 A 40 40 0 0 1 80 40 L 40 110 Z"></path></svg></div> <div class="labels yf-wummfw"><span>64.83</span> <span>77.47</span></div> </div> </td></tr> <tr class="row yf-1ilt7hv" data-testid="data-table-v2-row" data-testid-row="4"> <td class="[&amp;_.symbol]:tw-text-md yf-1ilt7hv lpin shad" data-testid-cell="ticker" style="--_depth: false;"> <div style="display: contents; --background-color:transparent; --hover-bg-color:transparent; --hover-color:var(--enabled-active-emph); --text-color:var(--enabled-active-emph); --hover-focus-color:var(--hovered-emph-same); --text-decoration:underline;"><span class="ticker-wrapper yf-hzimq4"><a aria-label="Cohen &amp; Steers Instl Realty Shares" class="ticker medium [&amp;_.symbol]:tw-text-md hover noPadding yf-hzimq4" data-testid="table-cell-ticker" data-yga='{"yLinkElement":"qte","yLinkElementType":"link","yModuleName":"mutualfunds-datatable","yLinkText":"CSRIX","yTrafficOrigin":"mutualfunds-datatable default"}' data-ylk="elm:qte;elmt:link;itc:0;sec:mutualfunds-datatable;slk:CSRIX;source:mutualfunds-datatable%20default" href="/quote/CSRIX/" title="Cohen &amp; Steers Instl Realty Shares"> <div class="name yf-hzimq4"> <span class="symbol yf-hzimq4">CSRIX </span> </div> </a> </span></div> </td> <td class="leftAlignHeader companyName yf-1ilt7hv" data-testid-cell="c

# Count Total Quotes


Determine the total number of quotes available on the page.

In [21]:
print(len(mutual_funds))

1

##   Extract Mutual Fund Data


Extract the required mutual fund information from the HTML elements and store it in Python lists for further processing.

In [22]:
data = []

In [23]:
rows= soup.find_all("tr")
for row in rows:
    cols= row.find_all("td")
    data.append([col.get_text(strip=True) for col in cols])

## Create DataFrame


Combine the extracted lists into a structured Pandas DataFrame.

In [24]:
df = pd.DataFrame(data)
df

,0,1,2,3,4,5,6,7,8,9,10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BIVSX,Invenomic Super Institutional,18.11+1.02(+5.97%),+1.02,+5.97%,16.12,17.11,-0.35%,-12.01%,+2.09%,14.0119.16
2,CSJRX,Cohen & Steers Realty Shares R,77.69+1.93(+2.55%),+1.93,+2.55%,74.79,70.23,+3.44%,+12.28%,+13.95%,65.0377.69
3,CSJIX,Cohen & Steers Realty Shares I,77.44+1.92(+2.54%),+1.92,+2.54%,74.57,70.02,+3.44%,+12.28%,+13.92%,64.8177.44
4,CSRSX,Cohen & Steers Realty Shares L,77.47+1.92(+2.54%),+1.92,+2.54%,74.60,70.05,+7.19%,+19.66%,+13.91%,64.8377.47
5,CSRIX,Cohen & Steers Instl Realty Shares,56.52+1.40(+2.54%),+1.40,+2.54%,54.43,51.11,+7.22%,+19.77%,+14.09%,47.2856.52
6,CSJAX,Cohen & Steers Realty Shares A,77.52+1.92(+2.54%),+1.92,+2.54%,74.64,70.09,+3.44%,+12.28%,+13.93%,64.8977.52
7,CSJZX,Cohen & Steers Realty Shares Z,77.67+1.92(+2.53%),+1.92,+2.53%,74.80,70.23,+3.44%,+12.28%,+13.94%,64.9977.67
8,CSJCX,Cohen & Steers Realty Shares C,77.15+1.90(+2.52%),+1.90,+2.52%,74.26,69.74,+3.44%,+12.28%,+13.94%,64.6277.15
9,PHRIX,Virtus Duff & Phelps Real Estate Secs I,21.77+0.50(+2.35%),+0.50,+2.35%,20.49,19.21,+7.83%,+21.32%,+18.12%,17.5521.77
10,PHRCX,Virtus Duff & Phelps Real Estate Secs C,21.86+0.50(+2.34%),+0.50,+2.34%,20.57,19.28,+7.52%,+20.67%,+18.16%,17.6421.86
11,PHRAX,Virtus Duff & Phelps Real Estate Secs A,21.88+0.50(+2.34%),+0.50,+2.34%,20.60,19.31,+7.78%,+21.17%,+18.14%,17.6521.88
12,VRREX,Virtus Duff & Phelps Real Estate Secs R6,21.90+0.50(+2.34%),+0.50,+2.34%,20.62,19.33,+7.88%,+21.48%,+18.12%,17.6521.90
13,SEIRX,SEI Real Estate I (SIMT),17.33+0.39(+2.30%),+0.39,+2.30%,16.54,15.85,+5.42%,+17.15%,+7.84%,14.4917.33
14,SETAX,SEI Institutional Managed Trust Real Estate Fund,17.37+0.39(+2.30%),+0.39,+2.30%,16.58,15.89,+5.45%,+17.22%,+7.82%,14.5617.37
15,SREYX,SEI Real Estate Y (SIMT),17.38+0.39(+2.30%),+0.39,+2.30%,16.59,15.90,+5.59%,+17.44%,+7.82%,14.5717.38
16,PJEAX,PGIM US Real Estate A,19.18+0.43(+2.29%),+0.43,+2.29%,18.13,16.75,+7.04%,+22.20%,+25.61%,14.9419.18
17,FARCX,Nuveen Real Estate Securities Fund,17.40+0.39(+2.29%),+0.39,+2.29%,16.59,15.60,+5.81%,+19.07%,+18.29%,14.4517.40
18,PJEQX,PGIM US Real Estate R6,19.22+0.43(+2.29%),+0.43,+2.29%,18.17,16.80,+7.19%,+22.45%,+25.62%,14.9719.22
19,PJEZX,PGIM US Real Estate Z,19.22+0.43(+2.29%),+0.43,+2.29%,18.17,16.79,+7.17%,+22.39%,+25.62%,14.9719.22
20,PJECX,PGIM US Real Estate C,18.53+0.41(+2.26%),+0.41,+2.26%,17.51,16.20,+6.87%,+21.72%,+25.20%,14.4718.53
21,FREGX,Nuveen Real Estate Securities R6,17.74+0.39(+2.25%),+0.39,+2.25%,16.92,15.91,+5.94%,+19.26%,+18.35%,14.7217.74
22,FREAX,Nuveen Real Estate Securities A,16.94+0.37(+2.23%),+0.37,+2.23%,16.16,15.20,+5.78%,+18.91%,+18.13%,14.0716.94
23,AREDX,American Century Real Estate R6,30.78+0.67(+2.23%),+0.67,+2.23%,29.42,27.72,+7.62%,+19.23%,+16.90%,25.7030.78
24,ARYEX,American Century Real Estate Y,30.79+0.67(+2.22%),+0.67,+2.22%,29.42,27.72,+7.65%,+19.22%,+16.89%,25.7130.79
25,GURAX,NAA Risk Managed Real Estate A,37.94+0.81(+2.18%),+0.81,+2.18%,36.12,33.80,+6.96%,+18.22%,+19.65%,31.0737.94
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Inspect Dataset


Verify that the extracted data is correctly stored.

In [25]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BIVSX,Invenomic Super Institutional,18.11+1.02(+5.97%),+1.02,+5.97%,16.12,17.11,-0.35%,-12.01%,+2.09%,14.0119.16
2,CSJRX,Cohen & Steers Realty Shares R,77.69+1.93(+2.55%),+1.93,+2.55%,74.79,70.23,+3.44%,+12.28%,+13.95%,65.0377.69
3,CSJIX,Cohen & Steers Realty Shares I,77.44+1.92(+2.54%),+1.92,+2.54%,74.57,70.02,+3.44%,+12.28%,+13.92%,64.8177.44
4,CSRSX,Cohen & Steers Realty Shares L,77.47+1.92(+2.54%),+1.92,+2.54%,74.60,70.05,+7.19%,+19.66%,+13.91%,64.8377.47

## Export Dataset


Save the cleaned dataset for future use.

In [62]:
df.to_csv("scraped_mutual_data.csv", index=False)
print("CSV file created successfully!")

CSV file created successfully!