%%html

<style>

.header{
    text-align:center;
    padding:25px;
    border-radius:20px;
    background:linear-gradient(135deg,#6C63FF,#00B4DB);
    color:white;
    animation:fadeIn 2s ease-in-out;
    box-shadow:0 10px 25px rgba(0,0,0,.25);
    font-family:Arial,sans-serif;
}

.header h1{
    font-size:40px;
    margin-bottom:10px;
    animation:glow 2s infinite alternate;
}

.header h2{
    font-size:20px;
    font-weight:normal;
    margin-bottom:18px;
}

.info{
    margin-top:15px;
    display:inline-block;
    text-align:left;
    background:rgba(255,255,255,.15);
    padding:18px 30px;
    border-radius:15px;
    line-height:1.8;
    font-size:16px;
}


@keyframes fadeIn{

from{
opacity:0;
transform:translateY(-30px);
}

to{
opacity:1;
transform:translateY(0);
}

}


@keyframes glow{

from{
text-shadow:0 0 8px white;
}

to{
text-shadow:0 0 20px #FFD700;
}

}

</style>


<div class="header">

<h1>📚 Wikipedia Information Extractor</h1>

<h2>Extracting Structured Data & Tables Using Static Web Scraping</h2>


<div class="info">

<b>👩‍💻 Prepared By:</b> Sunaina Saini <br>

<b>🎓 Course:</b> B.Tech – Artificial Intelligence & Machine Learning (AIML)<br>

<b>🏢 Internship:</b> AIML Bootcamp – CodroidHub Pvt. Ltd.<br>

<b>🌐 Website:</b> Wikipedia <br>

<b>🕸️ Scraping Type:</b> Static Web Scraping <br>

<b>💻 Language:</b> Python <br>

<b>📚 Libraries:</b> Requests, BeautifulSoup4, Pandas <br>

<b>📂 Output:</b> Article Data, Infobox Data, Tables & Structured Datasets <br>

<b>📅 Date:</b> July 2026

</div>

</div>

## Import Required Libraries
Import all required Python libraries.

In [22]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re

## Define Wikipedia URL

Provide the Wikipedia page URL from which data will be extracted

In [23]:
url = "https://en.wikipedia.org/wiki/Albert_Einstein"

# Add Browser Headers


Provide request headers so the website recognizes the request as coming from a real web browser.

In [24]:
HEADERS = ({'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

})

## Send HTTP Request


Connect with Wikipedia server and fetch HTML content.

In [25]:
response = requests.get(url,headers = HEADERS)

## Check the Response


Verify whether the request was successful by checking the HTTP status code.

In [26]:
print(response.status_code)
if response.status_code == 200:
    print("Website connected successfully")
else:
    print("Failed:", response.status_code)

200
Website connected successfully

## Check Response Content Type

Inspect the returned webpage data.

In [27]:
type(response.content)

bytes

# Parse the HTML

Convert the HTML into a BeautifulSoup object for easier navigation.

In [28]:
soup = BeautifulSoup(response.content,"html.parser")

## Preview HTML Structure

Display webpage HTML structure.

In [29]:
soup

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>Albert Einstein - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"93d2d32e-f452-4aa1-9339-49aedeb8b76b","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Albert_Einstein","wgTitle":"Albert Einstein","wgCurRevisionId":1366516273,"wgRevisionId":1366516273,"wgArticleId":736,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description matches Wikidata","Good articles","Wikipedia indefinitely move-protected pages","Wikipedia indefinitely semi-protected pages","Use American English from August 2024","All Wikipedia articles written in American English","Use dmy dates from June 2025","Articles containing German-language text","Articles with hAudio microformats","Biography with signature","Articles with hCards","Pages using the Phonos extension","Pages with German IPA","Pages including recorded pronunciations","CS1 German-language sources (de)","CS1 location test","CS1: long volume value","CS1 French-language sources (fr)","Wikipedia articles incorporating a citation from the 1922 Encyclopaedia Britannica with Wikisource reference","Pages using Sister project links with hidden wikidata","Articles with Project Gutenberg links","Articles with Internet Archive links","Articles with LibriVox links","Nobelprize template using Wikidata property P8024","Albert Einstein","1879 births","1955 deaths","20th-century American physicists","20th-century German physicists","20th-century American engineers","20th-century American inventors","20th-century Swiss inventors","20th-century American letter writers","20th-century American male writers","20th-century American science writers","Academic staff of Charles University","Academic staff of ETH Zurich","Academic staff of the University of Bern","Academic staff of the University of Zurich","Activists for African-American civil rights","American civil rights activists","American agnostics","American Ashkenazi Jews","American democratic socialists","American humanists","American male non-fiction writers","American Nobel laureates","American pacifists","American people of German descent","American people of Jewish descent","American philosophers of mathematics","American quantum physicists","American relativity theorists","American socialists","American theoretical physicists","Anti-nationalists","Contributors to the Encyclopædia Britannica","Deaths from abdominal aortic aneurysm","Denaturalized citizens of Germany","Einstein family","ETH Zurich alumni","European democratic socialists","German agnostics","German Ashkenazi Jews","German emigrants to Switzerland","German humanists","German male non-fiction writers","German Nobel laureates","German people of Jewish descent","German quantum physicists","German relativity theorists","German civil rights activists","German socialists","German theoretical physicists","Institute for Advanced Study faculty","Jewish agnostics","Jewish American non-fiction writers","Jewish American physicists","Jewish American socialists","Jewish German physicists","Jewish emigrants from Nazi Germany to the United States","Emigrants from Nazi Germany to the United States","Jewish Nobel laureates","Max Planck Institute directors","International members of the American Philosophical Society","Members of the Royal Netherlands Academy of Arts and Sciences","Members of the United States National Academy of Sciences","Naturalised citizens of Austria","Naturalised citizens of Switzerland","Naturalized citizens of the United States","Nobel laureates in Physics","Pantheists","Patent examiners","People from Ulm","People who lost German citizenship","Philosophers of mathematics","Philosophers of science","Recipients of Franklin Medal","Scientists from Munich","Stateless people","Swiss agnostics","Swiss Ashkenazi Jews","Swiss cosmologists","Swiss emigrants to the United States","Swiss Nobel laureates","Swiss people of German descent","Swiss people of Jewish descent","Swiss physicists","Swiss socialists","University of Zurich alumni","Winners of the Max Planck Medal","Emigrants from Württemberg to the United States","19th-century American Jews","19th-century German Jews","19th-century Swiss Jews"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Albert_Einstein","wgRelevantArticleId":736,"wgTempUserName":null,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":["autoconfirmed"],"wgRestrictionMove":["sysop"],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":200000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Astronomy":{"class":"GA","importance":"Mid"},"Astronomy/Cosmology task force":{"class":"GA","importance":""},"Biography":{"class":"GA","importance":""},"Biography/Core biographies":{"class":"GA","importance":""},"Biography/science and academia work group":{"class":"GA","importance":"Top"},"European history":{"class":"GA","importance":"Mid"},"Germany":{"class":"GA","importance":"Top"},"Guild of Copy Editors":{"class":"GA","importance":""},"History of Science":{"class":"GA","importance":"Top"},"Israel":{"class":"GA","importance":"High"},"Jewish history":{"class":"GA","importance":"High"},"Mathematics":{"class":"GA","importance":"High"},"New Jersey":{"class":"GA","importance":"Mid"},"Philosophy":{"class":"GA","importance":"Low"},"Philosophy/Philosophers":{"class":"GA","importance":"Low"},"Philosophy/Philosophy of science":{"class":"GA","importance":"Low"},"Physics":{"class":"GA","importance":"Top"},"Physics/Biographies Taskforce":{"class":"GA","importance":""},"Physics/History Taskforce":{"class":"GA","importance":""},"Physics/relativity task force":{"class":"GA","importance":""},"Project-independent assessment":{"class":"GA","importance":""},"Religion":{"class":"GA","importance":"Low"},"Socialism":{"class":"GA","importance":"Mid"},"Switzerland":{"class":"GA","importance":"High"},"United States":{"class":"GA","importance":"Low"},"Veganism and Vegetarianism":{"class":"GA","importance":"High"}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q937","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.phonos.styles":"ready","ext.phonos.icons":"ready","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","ext.tmh.player.styles":"ready","mediawiki.skinning.content.parsoid":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.makeCollapsible.styles":"ready","mediawiki.skins.legacy":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready","ext.wikimediaBadges.ulsV2":"ready"};RLPAGEMODULES=["ext.phonos.init","ext.cite.ux-enhancements","mediawiki.page.media","ext.tmh.player","ext.scribunto.logs","site","mediawiki.page.ready","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.phonos.icons%2Cstyles%7Cext.tmh.player.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediaBadges.ulsV2%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cmediawiki.skinning.content.parsoid%7Cmediawiki.skins.legacy%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.47.0-wmf.12" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Albert_Einstein_Head_cleaned.jpg/1280px-Albert_Einstein_Head_cleaned.jpg" property="og:image"/>
<meta content="969" property="og:image:width"/>
<meta content="1200" property="og:image:height"/>
<meta content="width=1120" name="viewport"/>
<meta content="Albert Einstein - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/Albert_Einstein" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-Albert_Einstein rootpage-Albert_Einstein skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>

## Extract Wikipedia Title

Find the main heading of the Wikipedia page.

In [30]:
title = soup.find("h1")

print(title.text)

Albert Einstein

## Extract Article Paragraphs

Extract the main text content from Wikipedia.

In [31]:
paragraphs = soup.find_all("p")

len(paragraphs)

154

## Display Paragraph Data

View extracted article content.

In [32]:
for para in paragraphs[:5]:
    print(para.text)

Albert Einstein[a] (14 March 1879 – 18 April 1955) was a German-born theoretical physicist best known for developing the theory of relativity. Einstein also made important contributions to quantum theory.[1][5] His mass–energy equivalence formula E = mc2, which arises from special relativity, has been called "the world's most famous equation".[6] He received the 1921 Nobel Prize in Physics for "his services to theoretical physics, and especially for his discovery of the law of the photoelectric effect".[7]
Born as a subject to the Kingdom of Württemberg, part of the German Empire,[note 1] Einstein moved to Switzerland in 1895, forsaking his citizenship the following year. In 1896, at the age of seventeen, he enrolled in the mathematics and physics teaching diploma program at the Swiss federal polytechnic school in Zurich, graduating in 1900. He acquired Swiss citizenship a year later, which he kept for the rest of his life, and afterwards secured a permanent position at the Swiss Patent Office in Bern. In 1905, he submitted a successful PhD dissertation to the University of Zurich. In 1914, he moved to Berlin to join the Prussian Academy of Sciences and the Humboldt University of Berlin, becoming director of the Kaiser Wilhelm Institute for Physics in 1917; he also became a Prussian and consequently also German citizen again. In 1933, while Einstein was visiting the United States, Adolf Hitler came to power in Germany. Horrified by the Nazi persecution of his fellow Jews,[8] he decided to remain in the US, and was granted American citizenship in 1940.[9] On the eve of World War II, he endorsed a letter to President Franklin D. Roosevelt alerting him to the potential German nuclear weapons program and recommending that the US begin similar research, later carried out as the Manhattan Project.
In 1905, sometimes described as his annus mirabilis (miracle year), he published four groundbreaking papers.[10] In them, he outlined a theory of the photoelectric effect, explained Brownian motion, introduced his special theory of relativity, and demonstrated that if the special theory is correct, mass and energy are equivalent to each other. In 1915, he proposed a general theory of relativity that extended his system of mechanics to incorporate gravitation. A paper that he published the following year laid out the implications of general relativity for the modeling of the structure and evolution of the universe as a whole.[11][12] It introduced the cosmological constant and is further regarded as the first step in the field of modern theoretical cosmology. In 1917, Einstein wrote a paper which introduced the concepts of spontaneous emission and stimulated emission, the latter of which is the core mechanism behind the laser and maser, and which contained a trove of information that would be beneficial to developments in physics later on, such as quantum electrodynamics and quantum optics.[13]
In the middle part of his career, Einstein made important contributions to statistical mechanics and quantum theory. Especially notable was his work on the quantum physics of radiation, in which light consists of particles, subsequently called photons. With physicist Satyendra Nath Bose, he laid the groundwork for Bose–Einstein statistics. For much of the last phase of his academic life, Einstein worked on two endeavors that ultimately proved unsuccessful. First, he advocated against quantum theory's introduction of fundamental randomness into science's picture of the world, objecting that "God does not play dice".[14] Second, he attempted to devise a unified field theory by generalizing his geometric theory of gravitation to include electromagnetism. As a result, he became increasingly isolated from mainstream modern physics. Many things are named after him, including the element Einsteinium. In 1999, he was named Time's Person of the Century.[15]

## Store Article Data

Create a list containing all paragraphs.

In [33]:
article_data = []


for para in paragraphs:

    text = para.text.strip()

    if text:
        article_data.append(text)


print(len(article_data))

153

## Create Article DataFrame

Convert article text into structured format.

In [34]:
article_df = pd.DataFrame({

"Article_Content":article_data

})


article_df.head()

                                     Article_Content
0  Albert Einstein[a] (14 March 1879 – 18 April 1...
1  Born as a subject to the Kingdom of Württember...
2  In 1905, sometimes described as his annus mira...
3  In the middle part of his career, Einstein mad...
4  Einstein was born in Ulm as a subject to the K...

## Extract Wikipedia Headings

Find all section headings.

In [35]:
headings = []


for heading in soup.find_all(["h2","h3"]):

    headings.append(
        heading.text.strip()
    )


headings[:10]

['Contents',
 'Life and career',
 'Childhood, youth and education',
 'Marriages, relationships and children',
 'Assistant at the Swiss Patent Office (1902–1909)',
 'First scientific papers (1900–1905)',
 'Academic career in Europe (1908–1933)',
 'Putting general relativity to the test (1919)',
 'Coming to terms with fame (1921–1923)',
 'Serving the League of Nations (1922–1932)']

## Extract Infobox Data

Wikipedia pages contain important information inside infobox tables.

In [36]:
infobox = soup.find("table",class_="infobox")
print(infobox)

<table about="#mwt11" class="infobox biography vcard"><tbody><tr><th class="infobox-above" colspan="2"><div class="fn">Albert Einstein</div></th></tr><tr><td class="infobox-image" colspan="2"><span class="mw-default-size" typeof="mw:File/Frameless"><a class="mw-file-description" href="https://en.wikipedia.org/wiki/File:Albert_Einstein_Head_cleaned.jpg"><img class="mw-file-element mw-file-upright" data-file-height="5607" data-file-type="bitmap" data-file-width="4530" decoding="async" height="309" resource="https://en.wikipedia.org/wiki/File:Albert_Einstein_Head_cleaned.jpg" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/28/Albert_Einstein_Head_cleaned.jpg/250px-Albert_Einstein_Head_cleaned.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/28/Albert_Einstein_Head_cleaned.jpg/500px-Albert_Einstein_Head_cleaned.jpg 2x" style="--mw-file-upright: 1" width="250"/></a></span><div class="infobox-caption">Einstein in 1947</div></td></tr><tr><th class="infobox-label" scope="row">Born</th><td class="infobox-data"><span style="display:none">(<span class="bday">1879-03-14</span>)</span>14 March 1879<br/><div class="birthplace" style="display:inline"><a href="https://en.wikipedia.org/wiki/Ulm" rel="mw:WikiLink" title="Ulm">Ulm</a>, Kingdom of Württemberg, German<span typeof="mw:Entity"> </span>Empire</div><span data-plural="1" style="display:none"></span></td></tr><tr><th class="infobox-label" scope="row">Died</th><td class="infobox-data">18 April 1955<span style="display:none">(1955-04-18)</span> (aged<span typeof="mw:Entity"> </span>76)<br/><div class="deathplace" style="display:inline"><a href="https://en.wikipedia.org/wiki/Princeton,_New_Jersey" rel="mw:WikiLink" title="Princeton, New Jersey">Princeton, New Jersey</a>, U.S.</div><span data-plural="1" style="display:none"></span></td></tr><tr><th class="infobox-label" scope="row">Citizenship</th><td class="infobox-data category"><div class="collapsible-list mw-collapsible mw-collapsed" style="text-align: left;">
<div style="line-height: 1.6em; font-weight: bold;"><div><style about="#mwt13" data-mw='{"name":"templatestyles","attrs":{"src":"Nobold/styles.css"}}' data-mw-deduplicate="TemplateStyles:r886047488" typeof="mw:Extension/templatestyles">.mw-parser-output .nobold{font-weight:normal}</style><span class="nobold"><i>See list</i></span></div></div>
<ul class="mw-collapsible-content" style="margin-top: 0; margin-bottom: 0; line-height: inherit; list-style: none; margin-left: 0;"><li style="line-height: inherit; margin: 0"><span class="mw-empty-elt"><style about="#mwt14" data-mw='{"name":"templatestyles","attrs":{"src":"Plainlist/styles.css"}}' data-mw-deduplicate="TemplateStyles:r1126788409" typeof="mw:Extension/templatestyles">.mw-parser-output .plainlist ol,.mw-parser-output .plainlist ul{line-height:inherit;list-style:none;margin:0;padding:0}.mw-parser-output .plainlist ol li,.mw-parser-output .plainlist ul li{margin-bottom:0}</style></span><div class="plainlist" style=" margin-left:1em;text-indent:-1em;">
<ul><li><a href="https://en.wikipedia.org/wiki/Kingdom_of_Württemberg" rel="mw:WikiLink" title="Kingdom of Württemberg">Kingdom of Württemberg</a>, part of the <a href="https://en.wikipedia.org/wiki/German_Empire" rel="mw:WikiLink" title="German Empire">German Empire</a> (until 1896)<sup about="#mwt15" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note","name":"GEcitizen"}}' id="cite_ref-GEcitizen_1-0" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="note" href="#cite_note-GEcitizen-1" id="mwEg"><span class="mw-reflink-text" id="mwEw"><span class="cite-bracket" id="mwFA">[</span>note 1<span class="cite-bracket" id="mwFQ">]</span></span></a></sup></li>
<li><a href="https://en.wikipedia.org/wiki/Statelessness" rel="mw:WikiLink" title="Statelessness">Stateless</a> (1896–1901)</li>
<li>Switzerland (from 1901)</li>
<li><a href="https://en.wikipedia.org/wiki/Kingdom_of_Prussia" rel="mw:WikiLink" title="Kingdom of Prussia">Kingdom of Prussia</a>, part of the German Empire (1914–1918)<sup about="#mwt17" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note","name":"GEcitizen"}}' id="cite_ref-GEcitizen_1-1" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="note" href="#cite_note-GEcitizen-1" id="mwFg"><span class="mw-reflink-text" id="mwFw"><span class="cite-bracket" id="mwGA">[</span>note 1<span class="cite-bracket" id="mwGQ">]</span></span></a></sup></li>
<li><a href="https://en.wikipedia.org/wiki/Free_State_of_Prussia" rel="mw:WikiLink" title="Free State of Prussia">Free State of Prussia</a> (<a href="https://en.wikipedia.org/wiki/Weimar_Republic" rel="mw:WikiLink" title="Weimar Republic">Weimar Republic</a>, 1918–1933)<sup about="#mwt19" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note","name":"GEcitizen"}}' id="cite_ref-GEcitizen_1-2" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="note" href="#cite_note-GEcitizen-1" id="mwGg"><span class="mw-reflink-text" id="mwGw"><span class="cite-bracket" id="mwHA">[</span>note 1<span class="cite-bracket" id="mwHQ">]</span></span></a></sup></li>
<li>U.S. (from 1940)</li></ul>
</div></li></ul>
</div></td></tr><tr><th class="infobox-label" scope="row">Education</th><td class="infobox-data"><span class="mw-empty-elt"><link about="#mwt21" data-mw='{"name":"templatestyles","attrs":{"src":"Plainlist/styles.css"}}' href="mw-data:TemplateStyles:r1126788409" rel="mw-deduplicated-inline-style" typeof="mw:Extension/templatestyles"/></span><div class="plainlist" style=" margin-left:1em;text-indent:-1em;">
<ul><li><a href="https://en.wikipedia.org/wiki/ETH_Zurich" rel="mw:WikiLink" title="ETH Zurich">Swiss federal polytechnic school</a> (teaching diploma, 1900)</li>
<li><a href="https://en.wikipedia.org/wiki/University_of_Zurich" rel="mw:WikiLink" title="University of Zurich">University of Zurich</a> (<a class="mw-redirect" href="https://en.wikipedia.org/wiki/PhD" rel="mw:WikiLink" title="PhD">PhD</a>, 1905)</li></ul>
</div></td></tr><tr><th class="infobox-label" scope="row">Known<span typeof="mw:Entity"> </span>for</th><td class="infobox-data"><span class="mw-empty-elt"><link about="#mwt22" data-mw='{"name":"templatestyles","attrs":{"src":"Plainlist/styles.css"}}' href="mw-data:TemplateStyles:r1126788409" rel="mw-deduplicated-inline-style" typeof="mw:Extension/templatestyles"/></span><div class="plainlist" style=" margin-left:1em;text-indent:-1em;">
<ul><li><a href="https://en.wikipedia.org/wiki/General_relativity" rel="mw:WikiLink" title="General relativity">General relativity</a></li>
<li><a href="https://en.wikipedia.org/wiki/Special_relativity" rel="mw:WikiLink" title="Special relativity">Special relativity</a></li>
<li><a href="https://en.wikipedia.org/wiki/Photoelectric_effect" rel="mw:WikiLink" title="Photoelectric effect">Photoelectric effect</a></li>
<li><a href="https://en.wikipedia.org/wiki/Mass–energy_equivalence" rel="mw:WikiLink" title="Mass–energy equivalence"><i>E</i>=<i>mc</i><sup>2</sup> (mass–energy equivalence)</a></li>
<li><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Planck–Einstein_relation" rel="mw:WikiLink" title="Planck–Einstein relation"><i>E</i>=<i>hf</i> (Planck–Einstein relation)</a></li>
<li><a href="https://en.wikipedia.org/wiki/Brownian_motion" rel="mw:WikiLink" title="Brownian motion">Theory of Brownian motion</a></li>
<li><a href="https://en.wikipedia.org/wiki/Einstein_field_equations" rel="mw:WikiLink" title="Einstein field equations">Einstein field equations</a></li>
<li><a href="https://en.wikipedia.org/wiki/Bose–Einstein_statistics" rel="mw:WikiLink" title="Bose–Einstein statistics">Bose–Einstein statistics</a></li>
<li><a href="https://en.wikipedia.org/wiki/Bose–Einstein_condensate" rel="mw:WikiLink" title="Bose–Einstein condensate">Bose–Einstein condensate</a></li>
<li><a href="https://en.wikipedia.org/wiki/Gravitational_wave" rel="mw:WikiLink" title="Gravitational wave">Gravitational wave</a></li>
<li><a href="https://en.wikipedia.org/wiki/Cosmological_constant" rel="mw:WikiLink" title="Cosmological constant">Cosmological constant</a></li>
<li><a href="https://en.wikipedia.org/wiki/Unified_field_theory" rel="mw:WikiLink" title="Unified field theory">Unified field theory</a></li>
<li><a class="mw-redirect" href="https://en.wikipedia.org/wiki/EPR_paradox" rel="mw:WikiLink" title="EPR paradox">EPR paradox</a></li>
<li><a href="https://en.wikipedia.org/wiki/Ensemble_interpretation" rel="mw:WikiLink" title="Ensemble interpretation">Ensemble interpretation</a></li>
<li><a href="https://en.wikipedia.org/wiki/List_of_things_named_after_Albert_Einstein" rel="mw:WikiLink" title="List of things named after Albert Einstein">List of other concepts</a></li></ul>
</div></td></tr><tr><th class="infobox-label" scope="row">Spouses</th><td class="infobox-data"><span class="mw-empty-elt"><link about="#mwt23" data-mw='{"name":"templatestyles","attrs":{"src":"Plainlist/styles.css"}}' href="mw-data:TemplateStyles:r1126788409" rel="mw-deduplicated-inline-style" typeof="mw:Extension/templatestyles"/></span><div class="plainlist">
<ul><li class="mw-empty-elt"><span class="mw-empty-elt"><style about="#mwt24" data-mw='{"name":"templatestyles","attrs":{"src":"Template:Marriage/styles.css"}}' data-mw-deduplicate="TemplateStyles:r1298804929" typeof="mw:Extension/templatestyles">.mw-parser-output .marriage-line-margin2px{line-height:0;margin-bottom:-2px}.mw-parser-output .marriage-line-margin3px{line-height:0;margin-bottom:-3px}.mw-parser-output .marriage-display-inline{display:inline}</style></span></li></ul>
<div class="marriage-display-inline"><div style="display:inline-block;line-height:normal;margin-top:1px;white-space:normal;"><a href="https://en.wikipedia.org/wiki/Mileva_Marić" rel="mw:WikiLink" title="Mileva Marić">Mileva Marić</a></div>
<div class="marriage-line-margin2px"><span typeof="mw:Entity">​</span></div><span typeof="mw:Entity"> </span><div style="display:inline-block;margin-bottom:1px;"><span typeof="mw:Entity">​</span></div><span typeof="mw:Entity">(</span><abbr about="#mwt48" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mwHg\"&gt;married&lt;/span&gt;"}]]}' title="married" typeof="mw:ExpandedAttrs">m.</abbr><span typeof="mw:Entity"> </span>1903<span typeof="mw:Entity">;</span><span typeof="mw:Entity"> </span><abbr about="#mwt49" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mwHw\"&gt;divorced&lt;/span&gt;"}]]}' title="divorced" typeof="mw:ExpandedAttrs">div.</abbr><span typeof="mw:Entity"> </span>1919<span typeof="mw:Entity">)</span><wbr/><span typeof="mw:Entity">​</span></div>
<ul><li class="mw-empty-elt"><span class="mw-empty-elt"><link about="#mwt25" data-mw='{"name":"templatestyles","attrs":{"src":"Template:Marriage/styles.css"}}' href="mw-data:TemplateStyles:r1298804929" rel="mw-deduplicated-inline-style" typeof="mw:Extension/templatestyles"/></span></li></ul>
<div class="marriage-display-inline"><div style="display:inline-block;line-height:normal;margin-top:1px;white-space:normal;"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Elsa_Löwenthal" rel="mw:WikiLink" title="Elsa Löwenthal">Elsa Löwenthal</a></div>
<div class="marriage-line-margin2px"><span typeof="mw:Entity">​</span></div><span typeof="mw:Entity"> </span><div style="display:inline-block;margin-bottom:1px;"><span typeof="mw:Entity">​</span></div><span typeof="mw:Entity">(</span><abbr about="#mwt50" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mwIA\"&gt;married&lt;/span&gt;"}]]}' title="married" typeof="mw:ExpandedAttrs">m.</abbr><span typeof="mw:Entity"> </span>1919<span typeof="mw:Entity">;</span><span typeof="mw:Entity"> </span>died<span typeof="mw:Entity"> </span>1936<span typeof="mw:Entity">)</span><wbr/><span typeof="mw:Entity">​</span></div>
</div></td></tr><tr><th class="infobox-label" scope="row">Children</th><td class="infobox-data">3, including <a href="https://en.wikipedia.org/wiki/Hans_Albert_Einstein" rel="mw:WikiLink" title="Hans Albert Einstein">Hans Albert</a></td></tr><tr><th class="infobox-label" scope="row">Family</th><td class="infobox-data"><a href="https://en.wikipedia.org/wiki/Einstein_family" rel="mw:WikiLink" title="Einstein family">Einstein</a></td></tr><tr><th class="infobox-label" scope="row">Awards</th><td class="infobox-data"><div class="collapsible-list mw-collapsible mw-collapsed" style="text-align: left;">
<div style="line-height: 1.6em; font-weight: bold;"><div><link about="#mwt26" data-mw='{"name":"templatestyles","attrs":{"src":"Nobold/styles.css"}}' href="mw-data:TemplateStyles:r886047488" rel="mw-deduplicated-inline-style" typeof="mw:Extension/templatestyles"/><span class="nobold"><i>See list</i></span></div></div>
<ul class="mw-collapsible-content" style="margin-top: 0; margin-bottom: 0; line-height: inherit; list-style: none; margin-left: 0;"><li style="line-height: inherit; margin: 0"><span class="mw-empty-elt"><link about="#mwt27" data-mw='{"name":"templatestyles","attrs":{"src":"Plainlist/styles.css"}}' href="mw-data:TemplateStyles:r1126788409" rel="mw-deduplicated-inline-style" typeof="mw:Extension/templatestyles"/></span><div class="plainlist" style=" margin-left:1em;text-indent:-1em;">
<ul><li><a href="https://en.wikipedia.org/wiki/Barnard_Medal_for_Meritorious_Service_to_Science" rel="mw:WikiLink" title="Barnard Medal for Meritorious Service to Science">Barnard Medal for Meritorious Service to Science</a> (1920)</li>
<li><a href="https://en.wikipedia.org/wiki/Nobel_Prize_in_Physics" rel="mw:WikiLink" title="Nobel Prize in Physics">Nobel Prize in Physics</a> (1921)</li>
<li><a href="https://en.wikipedia.org/wiki/Matteucci_Medal" rel="mw:WikiLink" title="Matteucci Medal">Matteucci Medal</a> (1921)</li>
<li><a href="https://en.wikipedia.org/wiki/List_of_fellows_of_the_Royal_Society_elected_in_1921" rel="mw:WikiLink" title="List of fellows of the Royal Society elected in 1921">ForMemRS</a> (1921)<sup about="#mwt28" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"frs"}}' id="cite_ref-frs_2-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-frs-2" id="mwIQ"><span class="mw-reflink-text" id="mwIg"><span class="cite-bracket" id="mwIw">[</span>1<span class="cite-bracket" id="mwJA">]</span></span></a></sup></li>
<li><a href="https://en.wikipedia.org/wiki/Copley_Medal" rel="mw:WikiLink" title="Copley Medal">Copley Medal</a> (1925)<sup about="#mwt30" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"frs"}}' id="cite_ref-frs_2-1" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-frs-2" id="mwJQ"><span class="mw-reflink-text" id="mwJg"><span class="cite-bracket" id="mwJw">[</span>1<span class="cite-bracket" id="mwKA">]</span></span></a></sup></li>
<li><a href="https://en.wikipedia.org/wiki/Gold_Medal_of_the_Royal_Astronomical_Society" rel="mw:WikiLink" title="Gold Medal of the Royal Astronomical Society">Gold Medal of RAS</a> (1926)<sup about="#mwt34" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-3"}}' id="cite_ref-3" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-3" id="mwKQ"><span class="mw-reflink-text" id="mwKg"><span class="cite-bracket" id="mwKw">[</span>2<span class="cite-bracket" id="mwLA">]</span></span></a></sup></li>
<li><a href="https://en.wikipedia.org/wiki/Max_Planck_Medal" rel="mw:WikiLink" title="Max Planck Medal">Max Planck Medal</a> (1929)</li>
<li><a href="https://en.wikipedia.org/wiki/Member_of_the_National_Academy_of_Sciences" rel="mw:WikiLink" title="Member of the National Academy of Sciences">Membership of NAS</a> (1942)<sup about="#mwt39" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-4"}}' id="cite_ref-4" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-4" id="mwLQ"><span class="mw-reflink-text" id="mwLg"><span class="cite-bracket" id="mwLw">[</span>3<span class="cite-bracket" id="mwMA">]</span></span></a></sup></li>
<li><a href="https://en.wikipedia.org/wiki/Time_100:_The_Most_Important_People_of_the_Century" rel="mw:WikiLink" title="Time 100: The Most Important People of the Century"><i>Time</i> Person of the Century</a> (1999)</li></ul>
</div></li></ul>
</div></td></tr><tr><td class="infobox-full-data" colspan="2"><link about="#mwt42" data-mw='{"name":"templatestyles","attrs":{"src":"Module:Infobox/styles.css"},"body":{"extsrc":""}}' href="mw-data:TemplateStyles:r1358620234" rel="mw-deduplicated-inline-style" typeof="mw:Extension/templatestyles"/><b>Scientific career</b></td></tr><tr><th class="infobox-label" scope="row">Fields</th><td class="infobox-data category"><a href="https://en.wikipedia.org/wiki/Physics" rel="mw:WikiLink" title="Physics">Physics</a></td></tr><tr><th class="infobox-label" scope="row">Institutions</th><td class="infobox-data"><div class="collapsible-list mw-collapsible mw-collapsed" style="text-align: left;">
<div style="line-height: 1.6em; font-weight: bold;"><div><link about="#mwt43" data-mw='{"name":"templatestyles","attrs":{"src":"Nobold/styles.css"}}' href="mw-data:TemplateStyles:r886047488" rel="mw-deduplicated-inline-style" typeof="mw:Extension/templatestyles"/><span class="nobold"><i>See list</i></span></div></div>
<ul class="mw-collapsible-content" style="margin-top: 0; margin-bottom: 0; line-height: inherit; list-style: none; margin-left: 0;"><li style="line-height: inherit; margin: 0"><span class="mw-empty-elt"><link about="#mwt44" data-mw='{"name":"templatestyles","attrs":{"src":"Plainlist/styles.css"}}' href="mw-data:TemplateStyles:r1126788409" rel="mw-deduplicated-inline-style" typeof="mw:Extension/templatestyles"/></span><div class="plainlist" style=" margin-left:1em;text-indent:-1em;">
<ul><li><a href="https://en.wikipedia.org/wiki/University_of_Bern" rel="mw:WikiLink" title="University of Bern">University of Bern</a> (1908–1909)</li>
<li><a href="https://en.wikipedia.org/wiki/University_of_Zurich" rel="mw:WikiLink" title="University of Zurich">University of Zurich</a> (1909–1911)</li>
<li><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Charles_University_in_Prague" rel="mw:WikiLink" title="Charles University in Prague">Charles University in Prague</a> (1911–1912)</li>
<li><a href="https://en.wikipedia.org/wiki/ETH_Zurich" rel="mw:WikiLink" title="ETH Zurich">ETH Zurich</a> (1912–1914)</li>
<li><a href="https://en.wikipedia.org/wiki/Prussian_Academy_of_Sciences" rel="mw:WikiLink" title="Prussian Academy of Sciences">Prussian Academy of Sciences</a> (1914–1933)</li>
<li><a href="https://en.wikipedia.org/wiki/Humboldt_University_of_Berlin" rel="mw:WikiLink" title="Humboldt University of Berlin">Humboldt University of Berlin</a> (1914–1933)</li>
<li><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Kaiser_Wilhelm_Institute" rel="mw:WikiLink" title="Kaiser Wilhelm Institute">Kaiser Wilhelm Institute</a> (director, 1917–1933)</li>
<li><a href="https://en.wikipedia.org/wiki/German_Physical_Society" rel="mw:WikiLink" title="German Physical Society">German Physical Society</a> (president, 1916–1918)</li>
<li><a href="https://en.wikipedia.org/wiki/Institute_for_Advanced_Study" rel="mw:WikiLink" title="Institute for Advanced Study">Institute for Advanced Study</a> (1933–1955)</li></ul>
</div></li></ul>

## Extract Infobox Information

In [37]:
infobox_data = {}


if infobox:

    rows = infobox.find_all("tr")

    for row in rows:

        cells = row.find_all(["th","td"])

        if len(cells)==2:

            key = cells[0].text.strip()
            value = cells[1].text.strip()

            infobox_data[key]=value

else:
    print("No Infobox Found")


infobox_data

{'Born': '(1879-03-14)14 March 1879Ulm, Kingdom of Württemberg, German\xa0Empire',
 'Died': '18 April 1955(1955-04-18) (aged\xa076)Princeton, New Jersey, U.S.',
 'Citizenship': 'See list\n\nKingdom of Württemberg, part of the German Empire (until 1896)[note 1]\nStateless (1896–1901)\nSwitzerland (from 1901)\nKingdom of Prussia, part of the German Empire (1914–1918)[note 1]\nFree State of Prussia (Weimar Republic, 1918–1933)[note 1]\nU.S. (from 1940)',
 'Education': 'Swiss federal polytechnic school (teaching diploma, 1900)\nUniversity of Zurich (PhD, 1905)',
 'Known\xa0for': 'General relativity\nSpecial relativity\nPhotoelectric effect\nE=mc2 (mass–energy equivalence)\nE=hf (Planck–Einstein relation)\nTheory of Brownian motion\nEinstein field equations\nBose–Einstein statistics\nBose–Einstein condensate\nGravitational wave\nCosmological constant\nUnified field theory\nEPR paradox\nEnsemble interpretation\nList of other concepts',
 'Spouses': 'Mileva Marić\n\u200b \u200b(m.\xa01903; div.\xa01919)\u200b\n\nElsa Löwenthal\n\u200b \u200b(m.\xa01919; died\xa01936)\u200b',
 'Children': '3, including Hans Albert',
 'Family': 'Einstein',
 'Awards': 'See list\n\nBarnard Medal for Meritorious Service to Science (1920)\nNobel Prize in Physics (1921)\nMatteucci Medal (1921)\nForMemRS (1921)[1]\nCopley Medal (1925)[1]\nGold Medal of RAS (1926)[2]\nMax Planck Medal (1929)\nMembership of NAS (1942)[3]\nTime Person of the Century (1999)',
 'Fields': 'Physics',
 'Institutions': 'See list\n\nUniversity of Bern (1908–1909)\nUniversity of Zurich (1909–1911)\nCharles University in Prague (1911–1912)\nETH Zurich (1912–1914)\nPrussian Academy of Sciences (1914–1933)\nHumboldt University of Berlin (1914–1933)\nKaiser Wilhelm Institute (director, 1917–1933)\nGerman Physical Society (president, 1916–1918)\nInstitute for Advanced Study (1933–1955)',
 'Thesis': 'Eine neue Bestimmung der Moleküldimensionen (A New Determination of Molecular Dimensions)\xa0(1905)',
 'Doctoral advisor': 'Alfred Kleiner',
 'Other\xa0academic advisors': 'Heinrich Friedrich Weber',
 'Website': 'alberteinstein.com'}

## Extract Wikipedia Tables

Find all tables available on the webpage.

In [38]:
tables = soup.find_all("table")

print(
"Total Tables:",
len(tables)
)

Total Tables: 12

## Extract Wikipedia Table Data

In [39]:
table_data = []


for row in tables[0].find_all("tr"):

    cells = row.find_all(["th","td"])

    row_data = []

    for cell in cells:
        row_data.append(cell.text.strip())


    if row_data:
        table_data.append(row_data)


table_df = pd.DataFrame(table_data)


table_df.head()

                  0                                                  1
0   Albert Einstein                                                NaN
1  Einstein in 1947                                                NaN
2              Born  (1879-03-14)14 March 1879Ulm, Kingdom of Württ...
3              Died  18 April 1955(1955-04-18) (aged 76)Princeton, ...
4       Citizenship  See list\n\nKingdom of Württemberg, part of th...

# Export to CSV


Save the scraped data as a CSV file for future use.

In [40]:
table_df.to_csv(
    "wikipedia_table_data.csv",
    index=False
)

print("CSV created successfully!")

CSV created successfully!