%%html

<style>
.header{
    text-align:center;
    padding:25px;
    border-radius:20px;
    background:linear-gradient(135deg,#6C63FF,#00B4DB);
    color:white;
    animation:fadeIn 2s ease-in-out;
    box-shadow:0 10px 25px rgba(0,0,0,.25);
    font-family:Arial, sans-serif;
}

.header h1{
    font-size:40px;
    margin-bottom:10px;
    animation:glow 2s infinite alternate;
}

.header h2{
    font-size:20px;
    font-weight:normal;
}

.info{
    margin-top:15px;
    display:inline-block;
    text-align:left;
    background:rgba(255,255,255,.15);
    padding:18px 30px;
    border-radius:15px;
    line-height:1.8;
}

@keyframes fadeIn{
    from{
        opacity:0;
        transform:translateY(-30px);
    }
    to{
        opacity:1;
        transform:translateY(0);
    }
}

@keyframes glow{
    from{
        text-shadow:0 0 8px white;
    }
    to{
        text-shadow:0 0 20px #FFD700;
    }
}

</style>


<div class="header">

<h1>🐙 GitHub Trending Repository Scraping Using Selenium</h1>

<h2>Automating Browser Interaction to Extract Trending GitHub Projects</h2>


<div class="info">

<b>👩‍💻 Prepared By:</b> Sunaina Saini <br>

<b>🎓 Course:</b> B.Tech – Artificial Intelligence & Machine Learning (AIML) <br>

<b>🕸️ Scraping Type:</b> Dynamic Web Scraping <br>

<b>🌐 Website:</b> GitHub Trending <br>

<b>🔗 URL:</b> https://github.com/trending <br>

<b>🤖 Automation Tool:</b> Selenium WebDriver <br>

<b>💻 Language:</b> Python <br>

<b>📚 Libraries:</b> Selenium, Pandas, Matplotlib <br>

<b>📂 Output:</b> CSV Dataset of Trending Repositories <br>

<b>📅 Date:</b> July 2026

</div>

</div>

## Import Required Libraries


Import all required Python libraries.

In [6]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import pandas as pd
import time

## Launch Chrome Browser
Initialize Chrome WebDriver.

In [7]:
options = Options()

options.add_argument("--start-maximized")

# Uncomment for background execution
# options.add_argument("--headless=new")


driver = webdriver.Chrome(options=options)

## Open GitHub Trending Website
Open GitHub Trending page using Selenium

In [8]:
url = "https://github.com/trending"

driver.get(url)

## Wait for Page to Load
Wait until repository elements are visible on the webpage.

In [9]:
wait = WebDriverWait(driver,20)

wait.until(
    EC.presence_of_all_elements_located(
        (By.CSS_SELECTOR,"article.Box-row")
    )
)

[<selenium.webdriver.remote.webelement.WebElement (session="f1854b9a7d96d06ee930f01fe93dd5a9", element="f.E01105498CC109BDA818262BD19D6D3D.d.FB543C85FFE7B31EBFFE601B5900EF53.e.333")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f1854b9a7d96d06ee930f01fe93dd5a9", element="f.E01105498CC109BDA818262BD19D6D3D.d.FB543C85FFE7B31EBFFE601B5900EF53.e.356")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f1854b9a7d96d06ee930f01fe93dd5a9", element="f.E01105498CC109BDA818262BD19D6D3D.d.FB543C85FFE7B31EBFFE601B5900EF53.e.383")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f1854b9a7d96d06ee930f01fe93dd5a9", element="f.E01105498CC109BDA818262BD19D6D3D.d.FB543C85FFE7B31EBFFE601B5900EF53.e.411")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f1854b9a7d96d06ee930f01fe93dd5a9", element="f.E01105498CC109BDA818262BD19D6D3D.d.FB543C85FFE7B31EBFFE601B5900EF53.e.438")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f1854b9a7d96d06ee930f01fe93dd5a9", element="f.E01105498CC109BDA818262BD19D6D3D.d.FB543C85FFE7B31EBFFE601B5900EF53.e.468")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f1854b9a7d96d06ee930f01fe93dd5a9", element="f.E01105498CC109BDA818262BD19D6D3D.d.FB543C85FFE7B31EBFFE601B5900EF53.e.496")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f1854b9a7d96d06ee930f01fe93dd5a9", element="f.E01105498CC109BDA818262BD19D6D3D.d.FB543C85FFE7B31EBFFE601B5900EF53.e.526")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f1854b9a7d96d06ee930f01fe93dd5a9", element="f.E01105498CC109BDA818262BD19D6D3D.d.FB543C85FFE7B31EBFFE601B5900EF53.e.97")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f1854b9a7d96d06ee930f01fe93dd5a9", element="f.E01105498CC109BDA818262BD19D6D3D.d.FB543C85FFE7B31EBFFE601B5900EF53.e.98")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f1854b9a7d96d06ee930f01fe93dd5a9", element="f.E01105498CC109BDA818262BD19D6D3D.d.FB543C85FFE7B31EBFFE601B5900EF53.e.610")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f1854b9a7d96d06ee930f01fe93dd5a9", element="f.E01105498CC109BDA818262BD19D6D3D.d.FB543C85FFE7B31EBFFE601B5900EF53.e.638")>]

## Locate Repository Elements
Find all trending repository containers.

In [10]:
repositories = driver.find_elements(
    By.CSS_SELECTOR,
    "article.Box-row"
)


print("Total Repositories Found:", len(repositories))

Total Repositories Found: 12

## Extract Repository Information
Extract repository name, description, language, stars, forks and URL.

In [11]:
for repo in repositories:

    title = repo.find_element(
        By.CSS_SELECTOR,
        "h2 a"
    ).text

    link = repo.find_element(
        By.CSS_SELECTOR,
        "h2 a"
    ).get_attribute("href")

    print("Repository:", title)
    print("Link:", link)
    print("-"*40)

Repository: pascalorg / editor
Link: https://github.com/pascalorg/editor
----------------------------------------
Repository: jenkinsci / jenkins
Link: https://github.com/jenkinsci/jenkins
----------------------------------------
Repository: moeru-ai / airi
Link: https://github.com/moeru-ai/airi
----------------------------------------
Repository: andrewyng / aisuite
Link: https://github.com/andrewyng/aisuite
----------------------------------------
Repository: affaan-m / ECC
Link: https://github.com/affaan-m/ECC
----------------------------------------
Repository: huggingface / speech-to-speech
Link: https://github.com/huggingface/speech-to-speech
----------------------------------------
Repository: virgiliojr94 / book-to-skill
Link: https://github.com/virgiliojr94/book-to-skill
----------------------------------------
Repository: opengeos / GeoLibre
Link: https://github.com/opengeos/GeoLibre
----------------------------------------
Repository: paperswithbacktest / awesome-systematic-trading
Link: https://github.com/paperswithbacktest/awesome-systematic-trading
----------------------------------------
Repository: microsoft / agent-governance-toolkit
Link: https://github.com/microsoft/agent-governance-toolkit
----------------------------------------
Repository: yorukot / superfile
Link: https://github.com/yorukot/superfile
----------------------------------------
Repository: bradautomates / claude-video
Link: https://github.com/bradautomates/claude-video
----------------------------------------

## Create Lists

In [12]:
titles = []
descriptions = []
languages = []
stars = []
forks = []
links = []

## Store Data
Store extracted repository information into lists.

In [13]:
for repo in repositories:

    try:
        title = repo.find_element(
            By.CSS_SELECTOR,
            "h2 a"
        ).text.replace("\n"," ")

    except:
        title="N/A"



    try:
        link = repo.find_element(
            By.CSS_SELECTOR,
            "h2 a"
        ).get_attribute("href")

    except:
        link="N/A"



    try:
        description = repo.find_element(
            By.CSS_SELECTOR,
            "p"
        ).text

    except:
        description="No Description"



    try:
        language = repo.find_element(
            By.CSS_SELECTOR,
            "[itemprop='programmingLanguage']"
        ).text

    except:
        language="N/A"



    try:
        stats = repo.find_elements(
            By.CSS_SELECTOR,
            "a.Link--muted"
        )

        stars_value = stats[0].text
        forks_value = stats[1].text

    except:

        stars_value="N/A"
        forks_value="N/A"



    titles.append(title)
    descriptions.append(description)
    languages.append(language)
    stars.append(stars_value)
    forks.append(forks_value)
    links.append(link)

## Create DataFrame
Convert scraped data into a structured dataset.

In [16]:
df = pd.DataFrame({

    "Repository Name": titles,
    "Description": descriptions,
    "Language": languages,
    "Stars": stars,
    "Forks": forks,
    "Repository Link": links

})
df

,Repository Name,Description,Language,Stars,Forks,Repository Link
0,pascalorg / editor,Create and share 3D architectural projects.,TypeScript,"18,353","2,506",https://github.com/pascalorg/editor
1,jenkinsci / jenkins,Jenkins automation server,Java,"25,997","9,682",https://github.com/jenkinsci/jenkins
2,moeru-ai / airi,"💖🧸 Self hosted, you-owned Grok Companion, a co...",TypeScript,"44,550","4,433",https://github.com/moeru-ai/airi
3,andrewyng / aisuite,"Simple, unified interface to multiple Generati...",Python,"15,590","1,650",https://github.com/andrewyng/aisuite
4,affaan-m / ECC,The agent harness performance optimization sys...,JavaScript,"234,519","35,743",https://github.com/affaan-m/ECC
5,huggingface / speech-to-speech,Build local voice agents with open-source models,Python,"6,881",934,https://github.com/huggingface/speech-to-speech
6,virgiliojr94 / book-to-skill,Turn any technical book PDF into a Claude Code...,Python,"10,869","1,305",https://github.com/virgiliojr94/book-to-skill
7,opengeos / GeoLibre,"A lightweight, cloud-native GIS platform for v...",TypeScript,"3,112",373,https://github.com/opengeos/GeoLibre
8,paperswithbacktest / awesome-systematic-trading,"A curated list of awesome libraries, packages,...",Python,"9,263","1,283",https://github.com/paperswithbacktest/awesome-...
9,microsoft / agent-governance-toolkit,AI Agent Governance Toolkit — Policy enforceme...,Python,"5,026",830,https://github.com/microsoft/agent-governance-...
10,yorukot / superfile,Pretty fancy and modern terminal file manager,Go,"21,237",683,https://github.com/yorukot/superfile
11,bradautomates / claude-video,Give Claude the ability to watch any video. /w...,Python,"11,725","1,188",https://github.com/bradautomates/claude-video

## Inspect Dataset


Verify that the extracted data is correctly stored.

In [17]:
df.head()

,Repository Name,Description,Language,Stars,Forks,Repository Link
0,pascalorg / editor,Create and share 3D architectural projects.,TypeScript,"18,353","2,506",https://github.com/pascalorg/editor
1,jenkinsci / jenkins,Jenkins automation server,Java,"25,997","9,682",https://github.com/jenkinsci/jenkins
2,moeru-ai / airi,"💖🧸 Self hosted, you-owned Grok Companion, a co...",TypeScript,"44,550","4,433",https://github.com/moeru-ai/airi
3,andrewyng / aisuite,"Simple, unified interface to multiple Generati...",Python,"15,590","1,650",https://github.com/andrewyng/aisuite
4,affaan-m / ECC,The agent harness performance optimization sys...,JavaScript,"234,519","35,743",https://github.com/affaan-m/ECC

## Export Dataset
Save scraped repository data into CSV format.

In [15]:
df.to_csv("github_trending_dataset.csv",index=False)
print("Dataset exported successfully!")

Dataset exported successfully!

## Close Browser
Close the browser after completing the scraping process.

In [ ]:
driver.quit()