%%html

<style>
.header{
    text-align:center;
    padding:25px;
    border-radius:20px;
    background:linear-gradient(135deg,#6C63FF,#00B4DB);
    color:white;
    animation:fadeIn 2s ease-in-out;
    box-shadow:0 10px 25px rgba(0,0,0,.25);
    font-family:Arial, sans-serif;
}

.header h1{
    font-size:40px;
    margin-bottom:10px;
    animation:glow 2s infinite alternate;
}

.header h2{
    font-size:20px;
    font-weight:normal;
    margin-bottom:18px;
}

.info{
    margin-top:15px;
    display:inline-block;
    text-align:left;
    background:rgba(255,255,255,.15);
    padding:18px 30px;
    border-radius:15px;
    line-height:1.8;
    font-size:16px;
}

@keyframes fadeIn{
    from{
        opacity:0;
        transform:translateY(-30px);
    }
    to{
        opacity:1;
        transform:translateY(0);
    }
}

@keyframes glow{
    from{
        text-shadow:0 0 8px white;
    }
    to{
        text-shadow:0 0 20px #FFD700;
    }
}
</style>

<div class="header">

<h1>🎬 IMDb Movie Data Web Scraping Using Selenium</h1>

<h2>Automating Browser Interaction to Extract IMDb Movie Information</h2>

<div class="info">

<b>👩‍💻 Prepared By:</b> Sunaina Saini <br>
<b>🎓 Course:</b> B.Tech – Artificial Intelligence & Machine Learning (AIML) <br>
<b>🏢 Internship:</b> AIML Bootcamp – CodroidHub Pvt. Ltd. <br>
<b>🌐 Website:</b> IMDb (Internet Movie Database) <br>
<b>🔗 URL:</b> https://www.imdb.com/ <br>
<b>🕸️ Scraping Type:</b> Dynamic Web Scraping <br>
<b>🤖 Automation Tool:</b> Selenium WebDriver <br>
<b>💻 Language:</b> Python <br>
<b>📚 Libraries:</b> Selenium, Pandas, Time <br>
<b>📂 Output:</b> CSV Dataset of IMDb Movie Information <br>
<b>📅 Date:</b> July 2026

</div>

</div>

## Import Required Libraries



Import all required Python libraries.

In [64]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import pandas as pd
import time

## Launch Chrome Browser



Initialize the Chrome WebDriver.

In [74]:
url = "https://www.imdb.com/chart/top/"
driver = webdriver.Chrome()
driver.get(url)

## Wait for Page to Load



Pause execution for a few seconds to ensure the webpage loads completely.

In [75]:
time.sleep(2)

## Verify Website Loading
Check that the correct webpage has loaded by displaying its title.

In [76]:
print(driver.title)

IMDb Top 250 movies

# Locate Movie Elements


Locate all movie containers from the IMDb Top Movies page. Each movie container includes the title, rating, year,certificate, and duration, which will be extracted in the following steps.

In [77]:
# Locate all movie elements
movies = driver.find_elements(By.CSS_SELECTOR,"li.ipc-metadata-list-summary-item")
print("Total Movies Found:", len(movies))

Total Movies Found: 250

## Extract Movie data
Extract and display the data
 of each movie.

In [78]:
titles=[]
ratings=[]
years=[]
durations=[]
certificates=[]

for movie in movies:

    # Title
    try:
        title = movie.find_element(
            By.CSS_SELECTOR,
            "h4.ipc-title__text"
        ).text
    except:
        title = "N/A"

    titles.append(title)

    # Rating
    try:
        rating = movie.find_element(
            By.CSS_SELECTOR,
            ".ipc-rating-star--rating"
        ).text
    except:
        rating = "N/A"

    ratings.append(rating)

    # Metadata inside THIS movie only
    meta = movie.find_elements(
        By.CSS_SELECTOR,
        ".ipc-inline-list__item"
    )

    try:
        years.append(meta[0].text)
    except:
        years.append("N/A")

    try:
        durations.append(meta[1].text)
    except:
        durations.append("N/A")

    try:
        certificates.append(meta[2].text)
    except:
        certificates.append("N/A")

## Create DataFrame


Combine the extracted lists into a structured Pandas DataFrame.

In [79]:
df = pd.DataFrame({
    "Title": titles,
    "Rating": ratings,
    "Year": years,
    "Duration": durations,
    "Certificate": certificates
})
df

,Title,Rating,Year,Duration,Certificate
0,The Shawshank Redemption,9.3,1994,2h 22m,R
1,The Godfather,9.2,1972,2h 55m,R
2,The Dark Knight,9.1,2008,2h 32m,PG-13
3,The Godfather Part II,9.0,1974,3h 22m,R
4,The Lord of the Rings: The Return of the King,9.0,2003,3h 21m,PG-13
...,...,...,...,...,...
245,My Father and My Son,8.2,2005,1h 52m,Not Rated
246,The Passion of Joan of Arc,8.1,1928,1h 54m,Passed
247,The Handmaiden,8.1,2016,2h 25m,Not Rated
248,Andhadhun,8.2,2018,2h 19m,Not Rated
249,Sita Ramam,8.5,2022,2h 43m,N/A

## Inspect Dataset


Verify that the extracted data is correctly stored.

In [80]:

df.head()

,Title,Rating,Year,Duration,Certificate
0,The Shawshank Redemption,9.3,1994,2h 22m,R
1,The Godfather,9.2,1972,2h 55m,R
2,The Dark Knight,9.1,2008,2h 32m,PG-13
3,The Godfather Part II,9.0,1974,3h 22m,R
4,The Lord of the Rings: The Return of the King,9.0,2003,3h 21m,PG-13

## Export Dataset

In [81]:
df.to_csv("IMDb_Top_Movies.csv",index=False)
print("Dataset exported successfully!")

Dataset exported successfully!

## Close Browser

Close the browser after the scraping process is complete.

In [82]:
driver.quit()