%%html

<style>

.header{

    text-align:center;
    padding:25px;

    border-radius:20px;

    background:
    linear-gradient(
        135deg,
        #6C63FF,
        #00B4DB
    );

    color:white;

    animation:fadeIn 2s ease-in-out;

    box-shadow:
    0 10px 25px rgba(0,0,0,.25);

    font-family:Arial, sans-serif;

}



.header h1{

    font-size:40px;

    margin-bottom:10px;

    animation:glow 2s infinite alternate;

}



.header h2{

    font-size:20px;

    font-weight:normal;

    margin-bottom:18px;

}



.info{

    margin-top:15px;

    display:inline-block;

    text-align:left;

    background:
    rgba(255,255,255,.15);

    padding:18px 30px;

    border-radius:15px;

    line-height:1.8;

    font-size:16px;

}



@keyframes fadeIn{

from{

    opacity:0;

    transform:translateY(-30px);

}


to{

    opacity:1;

    transform:translateY(0);

}

}



@keyframes glow{

from{

    text-shadow:
    0 0 8px white;

}


to{

    text-shadow:
    0 0 20px #FFD700;

}

}


</style>



<div class="header">


<h1>🎬 Netflix Top 10 Data Scraping Using Selenium</h1>


<h2>
Automating Browser Interaction to Extract Netflix Trending Content
</h2>



<div class="info">


<b>👩‍💻 Prepared By:</b> Sunaina Saini <br>

<b>🎓 Course:</b> B.Tech – Artificial Intelligence & Machine Learning (AIML) <br>

<b>🌐 Website:</b> Netflix Tudum Top 10 <br>

<b>🔗 URL:</b> https://www.netflix.com/tudum/top10 <br>

<b>🕸️ Scraping Type:</b> Dynamic Web Scraping <br>

<b>🤖 Automation Tool:</b> Selenium WebDriver <br>

<b>💻 Language:</b> Python <br>

<b>📚 Libraries:</b> Selenium, Pandas, Time <br>

<b>🎥 Data Extracted:</b> Rank, Title, Poster, Views, Runtime, Hours Viewed <br>

<b>📂 Output:</b> CSV Dataset of Netflix Top 10 Content <br>

<b>📅 Date:</b> July 2026


</div>


</div>

## Import Required Libraries


Import all required Python libraries.

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import pandas as pd
import time

## Launch Chrome Browser


Initialize Chrome WebDriver.

In [2]:
options = Options()

options.add_argument("--start-maximized")


# Uncomment for background execution
# options.add_argument("--headless=new")


driver = webdriver.Chrome(options=options)

## Open Netflix Top 10 Website


Navigate Selenium browser to Netflix Top 10 webpage.

In [3]:
url = "https://www.netflix.com/tudum/top10"


driver.get(url)

## Wait for Page to Load


Wait until Netflix Top 10 table data appears.

In [4]:
wait = WebDriverWait(driver,30)


wait.until(
    EC.presence_of_all_elements_located(
        (By.CSS_SELECTOR,"table tbody tr")
    )
)


time.sleep(5)

## Locate Netflix Movie Elements


Find all movie rows from Netflix Top 10 table.

In [5]:
rows = driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
print("Total Movies Found:",len(rows))

Total Movies Found: 10

## Create Lists


Create lists to store extracted movie information.

In [6]:
rank_list = []
title_list = []
poster_list = []
weeks_list = []
views_list = []
runtime_list = []
hours_list = []

## Extract Netflix Movie Information


Extract:

- Rank
- Title
- Poster
- Weeks in Top 10
- Views
- Runtime
- Hours Viewed

In [ ]:
for row in rows:


    # Rank

    try:
        rank = row.find_element(By.CSS_SELECTOR,'[data-uia="top10-table-row-title"] .rank').text.strip()
    except:
        rank="N/A"
    # Title

    try:
        title = row.find_element(
            By.CSS_SELECTOR,
            '[data-uia="top10-table-row-title"] button'
        ).text.strip()

    except:

        title="N/A"



    # Poster

    try:
        poster = row.find_element(
            By.CSS_SELECTOR,
            '[data-uia="top10-table-row-title"] img'
        ).get_attribute("src")

    except:

        poster=""



    # Weeks

    try:
        weeks = row.find_element(
            By.CSS_SELECTOR,
            '[data-uia="top10-table-row-weeks"]'
        ).text.strip()

    except:

        weeks="N/A"



    # Views

    try:
        views = row.find_element(
            By.CSS_SELECTOR,
            '[data-uia="top10-table-row-views"]'
        ).text.strip()

    except:

        views="N/A"



    # Runtime

    try:
        runtime = row.find_element(
            By.CSS_SELECTOR,
            '[data-uia="top10-table-row-runtime"]'
        ).text.strip()

    except:

        runtime=""



    # Hours

    try:
        hours = row.find_element(
            By.CSS_SELECTOR,
            '[data-uia="top10-table-row-hours"]'
        ).text.strip()

    except:

        hours=""



    rank_list.append(rank)
    title_list.append(title)
    poster_list.append(poster)
    weeks_list.append(weeks)
    views_list.append(views)
    runtime_list.append(runtime)
    hours_list.append(hours)

## Create DataFrame


Convert scraped Netflix data into a structured dataset.

In [ ]:
df = pd.DataFrame({

    "Rank": rank_list,
    "Title": title_list,
    "Poster": poster_list,
    "Weeks": weeks_list,
    "Views": views_list,
    "Runtime": runtime_list,
    "Hours Viewed": hours_list,
    "Link": url

})


df.head()

,Rank,Title,Poster,Weeks,Views,Runtime,Hours Viewed,Link
0,01,Shipwrecked: Nightmare at Sea,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,2,"1,11,00,000",1:30,"1,66,00,000",https://www.netflix.com/tudum/top10
1,02,Voicemails for Isabelle,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,5,"57,00,000",1:58,"1,12,00,000",https://www.netflix.com/tudum/top10
2,03,Enola Holmes 3,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,3,"47,00,000",1:48,"84,00,000",https://www.netflix.com/tudum/top10
3,04,Regretting You,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,1,"39,00,000",1:56,"75,00,000",https://www.netflix.com/tudum/top10
4,05,Meg 2: The Trench,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,1,"36,00,000",1:56,"70,00,000",https://www.netflix.com/tudum/top10

In [ ]:
    "Runtime": runtime_list,
    "Hours Viewed": hours_list,
    "Link": url

})


df.head()

## Dataset Preview


View extracted Netflix Top 10 records.

In [9]:
df

,Rank,Title,Poster,Weeks,Views,Runtime,Hours Viewed,Link
0,01,Shipwrecked: Nightmare at Sea,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,2,"1,11,00,000",1:30,"1,66,00,000",https://www.netflix.com/tudum/top10
1,02,Voicemails for Isabelle,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,5,"57,00,000",1:58,"1,12,00,000",https://www.netflix.com/tudum/top10
2,03,Enola Holmes 3,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,3,"47,00,000",1:48,"84,00,000",https://www.netflix.com/tudum/top10
3,04,Regretting You,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,1,"39,00,000",1:56,"75,00,000",https://www.netflix.com/tudum/top10
4,05,Meg 2: The Trench,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,1,"36,00,000",1:56,"70,00,000",https://www.netflix.com/tudum/top10
5,06,KPop Demon Hunters,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,57,"34,00,000",1:40,"57,00,000",https://www.netflix.com/tudum/top10
6,07,Death on the Nile,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,1,"34,00,000",2:09,"73,00,000",https://www.netflix.com/tudum/top10
7,08,The Boss Baby,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,27,"33,00,000",1:38,"54,00,000",https://www.netflix.com/tudum/top10
8,09,Joy Ride,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,1,"33,00,000",1:37,"53,00,000",https://www.netflix.com/tudum/top10
9,10,Sniper: No Nation,https://dnm.nflximg.net/api/v6/0Qzqdxw-HG1AiOK...,1,"32,00,000",1:36,"51,00,000",https://www.netflix.com/tudum/top10

## Export Dataset


Save Netflix Top 10 data into CSV format.

In [11]:
df.to_csv("netflix_top10_dataset.csv",index=False)
print("Dataset exported successfully!")

Dataset exported successfully!

## Close Browser


Close Selenium browser after scraping completion.

In [ ]:
driver.quit()