%%html

<style>

.header{
    text-align:center;
    padding:25px;
    border-radius:20px;

    background:
    linear-gradient(
        135deg,
        #6C63FF,
        #00B4DB
    );

    color:white;

    animation:fadeIn 2s ease-in-out;

    box-shadow:
    0 10px 25px rgba(0,0,0,.25);

    font-family:Arial, sans-serif;
}


.header h1{

    font-size:40px;
    margin-bottom:10px;

    animation:glow 2s infinite alternate;

}


.header h2{

    font-size:20px;
    font-weight:normal;
    margin-bottom:18px;

}



.info{

    margin-top:15px;

    display:inline-block;

    text-align:left;

    background:
    rgba(255,255,255,.15);

    padding:18px 30px;

    border-radius:15px;

    line-height:1.8;

    font-size:16px;

}



@keyframes fadeIn{

from{

opacity:0;

transform:translateY(-30px);

}


to{

opacity:1;

transform:translateY(0);

}

}



@keyframes glow{

from{

text-shadow:0 0 8px white;

}


to{

text-shadow:0 0 20px #FFD700;

}

}


</style>



<div class="header">


<h1>▶️ YouTube Trending Videos Scraping Using Selenium</h1>


<h2>
Automating Browser Interaction to Extract Trending YouTube Content
</h2>



<div class="info">


<b>👩‍💻 Prepared By:</b> Sunaina Saini <br>

<b>🎓 Course:</b> B.Tech – Artificial Intelligence & Machine Learning (AIML) <br>

<b>🌐 Website:</b> YouTube Trending Videos <br>

<b>🔗 URL:</b> https://www.youtube.com/results?search_query=trending+videos <br>

<b>🕸️ Scraping Type:</b> Dynamic Web Scraping <br>

<b>🤖 Automation Tool:</b> Selenium WebDriver <br>

<b>💻 Language:</b> Python <br>

<b>📚 Libraries:</b> Selenium, Pandas, Time <br>

<b>🎥 Data Extracted:</b> Title, Channel, Views, Duration, Thumbnail, Link <br>

<b>📂 Output:</b> CSV Dataset of Trending Videos <br>

<b>📅 Date:</b> July 2026


</div>


</div>

## Import Required Libraries


Import all required Python libraries.

In [3]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import pandas as pd
import time

## Launch Chrome Browser


Initialize Chrome WebDriver with browser settings.

In [4]:
options = Options()
options.add_argument("--start-maximized")
options.add_argument("user-agent=Mozilla/5.0")
driver = webdriver.Chrome(options=options)

## Open YouTube Trending Page


Navigate Selenium browser to YouTube search results.

In [5]:
url = "https://www.youtube.com/results?search_query=trending+videos"


driver.get(url)

## Wait for Videos to Load


Wait until YouTube video elements appear.

In [6]:
wait = WebDriverWait(driver,20)


wait.until(
    EC.presence_of_element_located(
        (By.TAG_NAME,"ytd-video-renderer")
    )
)

## Scroll Page


Scroll multiple times to load additional videos dynamically.

In [7]:
for i in range(8):

    driver.execute_script(
        "window.scrollTo(0, document.documentElement.scrollHeight);"
    )

    time.sleep(2)

## Locate Video Containers


Find all available YouTube video containers.

In [15]:
videos = driver.find_elements(
    By.TAG_NAME,
    "ytd-video-renderer"
)


print("Videos Found:",len(videos))

Videos Found: 5

## Create Lists


Create lists to store extracted video information.

In [16]:
titles = []
images = []
channels = []
views = []
durations = []
links = []

## Extract YouTube Video Information


Extract:

- Video Title
- Thumbnail
- Channel Name
- Views
- Duration
- Video Link

In [17]:
seen = set()


for video in videos:


    try:

        title_element = video.find_element(
            By.CSS_SELECTOR,
            "a#video-title"
        )


        title = title_element.text.strip()

        link = title_element.get_attribute("href")


        if not title or title in seen:
            continue


        seen.add(title)


    except:

        continue



    # Thumbnail

    try:

        img = video.find_element(
            By.CSS_SELECTOR,
            "img"
        )


        image = (
            img.get_attribute("src")
            or img.get_attribute("data-thumb")
            or ""
        )


    except:

        image=""



    # Channel

    try:

        channel = video.find_element(
            By.CSS_SELECTOR,
            "#channel-name a"
        ).text.strip()


    except:

        channel="N/A"



    # Views

    try:

        metadata = video.find_elements(
            By.CSS_SELECTOR,
            "#metadata-line span"
        )


        views_value = (
            metadata[0].text
            if len(metadata)>0
            else "N/A"
        )


    except:

        views_value="N/A"



    # Duration

    try:

        duration = video.find_element(
            By.CSS_SELECTOR,
            "span.ytd-thumbnail-overlay-time-status-renderer"
        ).text.strip()


    except:

        duration="N/A"



    titles.append(title)
    images.append(image)
    channels.append(channel)
    views.append(views_value)
    durations.append(duration)
    links.append(link)



    if len(titles)==20:
        break

## Create DataFrame


Convert scraped YouTube data into structured format.

In [18]:
df = pd.DataFrame({

    "Video Title": titles,
    "Thumbnail": images,
    "Channel": channels,
    "Views": views,
    "Duration": durations,
    "Video Link": links

})


df.head()

,Video Title,Thumbnail,Channel,Views,Duration,Video Link
0,How to Create Viral Instagram Motu Patlu AI Vi...,https://i.ytimg.com/vi/9gHGjqgdHqs/hq2.jpg?sqp...,,43K views,,https://www.youtube.com/watch?v=9gHGjqgdHqs&pp...
1,Trending Motu Patlu Video Editing in Telugu | ...,https://i.ytimg.com/vi/7zGHFt3sB9w/hq2.jpg?sqp...,,3.6K views,,https://www.youtube.com/watch?v=7zGHFt3sB9w&pp...
2,Instagram Viral Motu Patlu Wali Ai Video Kaise...,https://i.ytimg.com/vi/YHams3yOviw/hq2.jpg?sqp...,,11K views,,https://www.youtube.com/watch?v=YHams3yOviw&pp...
3,How to Make Reverse World AI Videos? | How to ...,https://i.ytimg.com/vi/SdjvyAQWWHs/hq2.jpg?sqp...,,376 views,,https://www.youtube.com/watch?v=SdjvyAQWWHs&pp...

## Dataset Preview


View extracted YouTube trending videos.

In [19]:
df

,Video Title,Thumbnail,Channel,Views,Duration,Video Link
0,How to Create Viral Instagram Motu Patlu AI Vi...,https://i.ytimg.com/vi/9gHGjqgdHqs/hq2.jpg?sqp...,,43K views,,https://www.youtube.com/watch?v=9gHGjqgdHqs&pp...
1,Trending Motu Patlu Video Editing in Telugu | ...,https://i.ytimg.com/vi/7zGHFt3sB9w/hq2.jpg?sqp...,,3.6K views,,https://www.youtube.com/watch?v=7zGHFt3sB9w&pp...
2,Instagram Viral Motu Patlu Wali Ai Video Kaise...,https://i.ytimg.com/vi/YHams3yOviw/hq2.jpg?sqp...,,11K views,,https://www.youtube.com/watch?v=YHams3yOviw&pp...
3,How to Make Reverse World AI Videos? | How to ...,https://i.ytimg.com/vi/SdjvyAQWWHs/hq2.jpg?sqp...,,376 views,,https://www.youtube.com/watch?v=SdjvyAQWWHs&pp...

## Export Dataset


Save YouTube video data into CSV format.

In [21]:
df.to_csv("youtube_trending_videos.csv",index=False)
print("Dataset exported successfully!")

Dataset exported successfully!

## Close Browser


Close Selenium browser after completing scraping.

In [ ]:
driver.quit()