%%html

<style>
.header{
    text-align:center;
    padding:25px;
    border-radius:20px;
    background:linear-gradient(135deg,#6C63FF,#00B4DB);
    color:white;
    animation:fadeIn 2s ease-in-out;
    box-shadow:0 10px 25px rgba(0,0,0,.25);
    font-family:Arial, sans-serif;
}

.header h1{
    font-size:42px;
    margin-bottom:10px;
    animation:glow 2s infinite alternate;
}

.header h2{
    font-size:20px;
    font-weight:normal;
}

.info{
    margin-top:20px;
    display:inline-block;
    text-align:left;
    background:rgba(255,255,255,.15);
    padding:18px 30px;
    border-radius:15px;
}

@keyframes fadeIn{
    from{opacity:0;transform:translateY(-30px);}
    to{opacity:1;transform:translateY(0);}
}

@keyframes glow{
    from{text-shadow:0 0 8px white;}
    to{text-shadow:0 0 20px yellow;}
}
</style>

<div class="header">

<h1>💱 Currency Exchange API Data Extraction Using Python</h1>

<h2>REST API Integration & Currency Exchange Data Processing Project</h2>

<div class="info">

<b>👩‍💻 Prepared By:</b> Sunaina Saini <br>
<b>🎓 Course:</b> B.Tech – Artificial Intelligence & Machine Learning (AIML) <br>
<b>🏢 Internship:</b> AIML Bootcamp – CodroidHub Pvt. Ltd. <br>
<b>🌐 API Used:</b> Currency Exchange API <br>
<b>💻 Language:</b> Python <br>
<b>📚 Libraries:</b> Requests, Pandas <br>
<b>📅 Date:</b> July 2026

</div>

</div>

## Import Required Libraries
Import essential Python libraries for API requests and data processing.

In [5]:
import requests
import pandas as pd

## Define Currency Exchange API Endpoint
Specify the Exchange Rate API URL to retrieve real-time currency exchange data.

In [6]:
url="https://api.frankfurter.app/latest?from=USD&to=INR,EUR,GBP,JPY"

## Send API Request
Establish a connection with the REST API using an HTTP GET request.

In [7]:
response = requests.get(url)

## Validate API Response
Verify the request was successful by checking the HTTP status code (200 OK).

In [8]:
print(response.status_code)

200

## Retrieve JSON Exchange Rate Data
Fetch and display the JSON response returned by the Currency Exchange API.

In [9]:
currency_data = response.json()

currency_data

{'amount': 1.0,
 'base': 'USD',
 'date': '2026-07-14',
 'rates': {'EUR': 0.87681, 'GBP': 0.74717, 'INR': 96.2, 'JPY': 162.22}}

## Store API Response Data
Store the API response in a Python variable for further processing and analysis.

In [10]:
exchange_data = currency_data

exchange_data

{'amount': 1.0,
 'base': 'USD',
 'date': '2026-07-14',
 'rates': {'EUR': 0.87681, 'GBP': 0.74717, 'INR': 96.2, 'JPY': 162.22}}

## Explore API Response Structure
Examine the JSON response to understand its keys, base currency, date, and exchange rates.

In [11]:
print("Available Keys:")
print(exchange_data.keys())

print("\nBase Currency:", exchange_data["base"])

print("Date:", exchange_data["date"])

Available Keys:
dict_keys(['amount', 'base', 'date', 'rates'])

Base Currency: USD
Date: 2026-07-14

## Extract Currency Rate Information
Loop through each university record returned by the API.

In [12]:
exchange_rates = exchange_data["rates"]

exchange_rates

{'EUR': 0.87681, 'GBP': 0.74717, 'INR': 96.2, 'JPY': 162.22}

## Create Structured Currency Dataset
Organize the extracted currency information into a structured list of dictionaries.

In [13]:
currency_list = []

for currency, rate in exchange_rates.items():
    currency_list.append({
        "Currency": currency,
        "Exchange Rate": rate
    })

currency_list

[{'Currency': 'EUR', 'Exchange Rate': 0.87681},
 {'Currency': 'GBP', 'Exchange Rate': 0.74717},
 {'Currency': 'INR', 'Exchange Rate': 96.2},
 {'Currency': 'JPY', 'Exchange Rate': 162.22}]

## Convert to Pandas DataFrame
Transform the structured data into a DataFrame for analysis.

In [14]:
currency_df = pd.DataFrame(currency_list)

currency_df

  Currency  Exchange Rate
0      EUR        0.87681
1      GBP        0.74717
2      INR       96.20000
3      JPY      162.22000

## Preview Currency Dataset
Display the first few records of the processed currency exchange dataset.

In [15]:
currency_df.head()

  Currency  Exchange Rate
0      EUR        0.87681
1      GBP        0.74717
2      INR       96.20000
3      JPY      162.22000

## Filter Required Currency Rates
Filter and display selected currencies for further analysis or conversion.

In [16]:
selected_currency = currency_df[
    currency_df["Currency"].isin(["INR", "EUR", "GBP", "JPY"])
]

selected_currency

  Currency  Exchange Rate
0      EUR        0.87681
1      GBP        0.74717
2      INR       96.20000
3      JPY      162.22000

## Create Currency Conversion Function
Develop a reusable function to perform currency conversion using real-time exchange rates.

In [17]:
def currency_converter(amount, target_currency):
    exchange_rate = exchange_rates[target_currency]
    converted_amount = amount * exchange_rate
    return converted_amount

## Perform Currency Conversion
Convert a user-specified amount between different currencies using the latest exchange rates.

In [18]:
amount = 100

print(f"100 USD = {currency_converter(amount,'INR'):.2f} INR")
print(f"100 USD = {currency_converter(amount,'EUR'):.2f} EUR")
print(f"100 USD = {currency_converter(amount,'GBP'):.2f} GBP")
print(f"100 USD = {currency_converter(amount,'JPY'):.2f} JPY")

100 USD = 9620.00 INR
100 USD = 87.68 EUR
100 USD = 74.72 GBP
100 USD = 16222.00 JPY

## Export Currency Dataset
Save the processed currency exchange dataset as a CSV file for future use.

In [20]:
currency_df.to_csv("currency_exchange_rates.csv", index=False)

print("Dataset exported successfully.")

Dataset exported successfully.