%%html

<style>
.header{
    text-align:center;
    padding:25px;
    border-radius:20px;
    background:linear-gradient(135deg,#6C63FF,#00B4DB);
    color:white;
    animation:fadeIn 2s ease-in-out;
    box-shadow:0 10px 25px rgba(0,0,0,.25);
    font-family:Arial, sans-serif;
}

.header h1{
    font-size:42px;
    margin-bottom:10px;
    animation:glow 2s infinite alternate;
}

.header h2{
    font-size:20px;
    font-weight:normal;
}

.info{
    margin-top:20px;
    display:inline-block;
    text-align:left;
    background:rgba(255,255,255,.15);
    padding:18px 30px;
    border-radius:15px;
}

@keyframes fadeIn{
    from{opacity:0;transform:translateY(-30px);}
    to{opacity:1;transform:translateY(0);}
}

@keyframes glow{
    from{text-shadow:0 0 8px white;}
    to{text-shadow:0 0 20px yellow;}
}
</style>

<div class="header">

<h1>🛒 Fake Store API Data Extraction Using Python</h1>

<h2>REST API Integration & Product Data Processing Project</h2>

<div class="info">

<b>👩‍💻 Prepared By:</b> Sunaina Saini <br>
<b>🎓 Course:</b> B.Tech – Artificial Intelligence & Machine Learning (AIML) <br>
<b>🏢 Internship:</b> AIML Bootcamp – CodroidHub Pvt. Ltd. <br>
<b>🌐 API Used:</b> Fake Store API <br>
<b>💻 Language:</b> Python <br>
<b>📚 Libraries:</b> Requests, Pandas <br>
<b>📅 Date:</b> July 2026

</div>

</div>

## Import Required Libraries
Import essential Python libraries for API requests and data processing.

In [1]:
import requests
import pandas as pd

## Define Fake Store API Endpoint
Specify the Fake Store API URL to retrieve product information.

In [2]:
url = "https://fakestoreapi.com/products"

## Send API Request
Establish a connection with the REST API using an HTTP GET request.

In [3]:
response = requests.get(url)

## Validate API Response
Verify the request was successful by checking the HTTP status code (200 OK).

In [4]:
print(response.status_code)

200

## Retrieve JSON Data
Fetch and display the JSON response received from the API.

In [5]:
data= response.json()

## Store API Response
Save the JSON response into a Python variable for further processing.

In [6]:
products = data

## Preview Product Records
Display individual product records to understand the JSON structure.

In [7]:
for product in products[:3]:
    print(product)

{'id': 1, 'title': 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 'price': 109.95, 'description': 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday', 'category': "men's clothing", 'image': 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png', 'rating': {'rate': 3.9, 'count': 120}}
{'id': 2, 'title': 'Mens Casual Premium Slim Fit T-Shirts ', 'price': 22.3, 'description': 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.', 'category': "men's clothing", 'image': 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png', 'rating': {'rate': 4.1, 'count': 259}}
{'id': 3, 'title': 'Mens Cotton Jacket', 'price': 55.99, 'description': 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.', 'category': "men's clothing", 'image': 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png', 'rating': {'rate': 4.7, 'count': 500}}

## Iterate Through Records
Loop through each university record returned by the API.

In [8]:
for item in data:
    print(item)

{'id': 1, 'title': 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 'price': 109.95, 'description': 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday', 'category': "men's clothing", 'image': 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png', 'rating': {'rate': 3.9, 'count': 120}}
{'id': 2, 'title': 'Mens Casual Premium Slim Fit T-Shirts ', 'price': 22.3, 'description': 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.', 'category': "men's clothing", 'image': 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png', 'rating': {'rate': 4.1, 'count': 259}}
{'id': 3, 'title': 'Mens Cotton Jacket', 'price': 55.99, 'description': 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.', 'category': "men's clothing", 'image': 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png', 'rating': {'rate': 4.7, 'count': 500}}
{'id': 4, 'title': 'Mens Casual Slim Fit', 'price': 15.99, 'description': 'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.', 'category': "men's clothing", 'image': 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png', 'rating': {'rate': 2.1, 'count': 430}}
{'id': 5, 'title': "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet", 'price': 695, 'description': "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.", 'category': 'jewelery', 'image': 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png', 'rating': {'rate': 4.6, 'count': 400}}
{'id': 6, 'title': 'Solid Gold Petite Micropave ', 'price': 168, 'description': 'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.', 'category': 'jewelery', 'image': 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png', 'rating': {'rate': 3.9, 'count': 70}}
{'id': 7, 'title': 'White Gold Plated Princess', 'price': 9.99, 'description': "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...", 'category': 'jewelery', 'image': 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png', 'rating': {'rate': 3, 'count': 400}}
{'id': 8, 'title': 'Pierced Owl Rose Gold Plated Stainless Steel Double', 'price': 10.99, 'description': 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel', 'category': 'jewelery', 'image': 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_t.png', 'rating': {'rate': 1.9, 'count': 100}}
{'id': 9, 'title': 'WD 2TB Elements Portable External Hard Drive - USB 3.0 ', 'price': 64, 'description': 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system', 'category': 'electronics', 'image': 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png', 'rating': {'rate': 3.3, 'count': 203}}
{'id': 10, 'title': 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', 'price': 109, 'description': 'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)', 'category': 'electronics', 'image': 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png', 'rating': {'rate': 2.9, 'count': 470}}
{'id': 11, 'title': 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5', 'price': 109, 'description': '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.', 'category': 'electronics', 'image': 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png', 'rating': {'rate': 4.8, 'count': 319}}
{'id': 12, 'title': 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', 'price': 114, 'description': "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty", 'category': 'electronics', 'image': 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png', 'rating': {'rate': 4.8, 'count': 400}}
{'id': 13, 'title': 'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin', 'price': 599, 'description': '21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz', 'category': 'electronics', 'image': 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png', 'rating': {'rate': 2.9, 'count': 250}}
{'id': 14, 'title': 'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ', 'price': 999.99, 'description': '49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag', 'category': 'electronics', 'image': 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png', 'rating': {'rate': 2.2, 'count': 140}}
{'id': 15, 'title': "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats", 'price': 56.99, 'description': 'Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates', 'category': "women's clothing", 'image': 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png', 'rating': {'rate': 2.6, 'count': 235}}
{'id': 16, 'title': "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket", 'price': 29.95, 'description': '100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON', 'category': "women's clothing", 'image': 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png', 'rating': {'rate': 2.9, 'count': 340}}
{'id': 17, 'title': 'Rain Jacket Women Windbreaker Striped Climbing Raincoats', 'price': 39.99, 'description': "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.", 'category': "women's clothing", 'image': 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png', 'rating': {'rate': 3.8, 'count': 679}}
{'id': 18, 'title': "MBJ Women's Solid Short Sleeve Boat Neck V ", 'price': 9.85, 'description': '95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem', 'category': "women's clothing", 'image': 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png', 'rating': {'rate': 4.7, 'count': 130}}
{'id': 19, 'title': "Opna Women's Short Sleeve Moisture", 'price': 7.95, 'description': '100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort', 'category': "women's clothing", 'image': 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png', 'rating': {'rate': 4.5, 'count': 146}}
{'id': 20, 'title': 'DANVOUY Womens T Shirt Casual Cotton Short', 'price': 12.99, 'description': '95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.', 'category': "women's clothing", 'image': 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_t.png', 'rating': {'rate': 3.6, 'count': 145}}

## Extract Product Information
Access fields such as product title, price, category, description, rating, and image URL.

In [9]:
records = []

for product in products:
    records.append({
        "Product ID": product["id"],
        "Title": product["title"],
        "Price": product["price"],
        "Category": product["category"],
        "Description": product["description"],
        "Rating": product["rating"]["rate"],
        "Rating Count": product["rating"]["count"],
        "Image URL": product["image"]
    })

## Create Structured Dataset
Organize the extracted product information into a structured list of dictionaries.

In [10]:
records

[{'Product ID': 1,
  'Title': 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
  'Price': 109.95,
  'Category': "men's clothing",
  'Description': 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
  'Rating': 3.9,
  'Rating Count': 120,
  'Image URL': 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png'},
 {'Product ID': 2,
  'Title': 'Mens Casual Premium Slim Fit T-Shirts ',
  'Price': 22.3,
  'Category': "men's clothing",
  'Description': 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.',
  'Rating': 4.1,
  'Rating Count': 259,
  'Image URL': 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png'},
 {'Product ID': 3,
  'Title': 'Mens Cotton Jacket',
  'Price': 55.99,
  'Category': "men's clothing",
  'Description': 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.',
  'Rating': 4.7,
  'Rating Count': 500,
  'Image URL': 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png'},
 {'Product ID': 4,
  'Title': 'Mens Casual Slim Fit',
  'Price': 15.99,
  'Category': "men's clothing",
  'Description': 'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.',
  'Rating': 2.1,
  'Rating Count': 430,
  'Image URL': 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png'},
 {'Product ID': 5,
  'Title': "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
  'Price': 695,
  'Category': 'jewelery',
  'Description': "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
  'Rating': 4.6,
  'Rating Count': 400,
  'Image URL': 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png'},
 {'Product ID': 6,
  'Title': 'Solid Gold Petite Micropave ',
  'Price': 168,
  'Category': 'jewelery',
  'Description': 'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.',
  'Rating': 3.9,
  'Rating Count': 70,
  'Image URL': 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png'},
 {'Product ID': 7,
  'Title': 'White Gold Plated Princess',
  'Price': 9.99,
  'Category': 'jewelery',
  'Description': "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
  'Rating': 3,
  'Rating Count': 400,
  'Image URL': 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png'},
 {'Product ID': 8,
  'Title': 'Pierced Owl Rose Gold Plated Stainless Steel Double',
  'Price': 10.99,
  'Category': 'jewelery',
  'Description': 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel',
  'Rating': 1.9,
  'Rating Count': 100,
  'Image URL': 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_t.png'},
 {'Product ID': 9,
  'Title': 'WD 2TB Elements Portable External Hard Drive - USB 3.0 ',
  'Price': 64,
  'Category': 'electronics',
  'Description': 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system',
  'Rating': 3.3,
  'Rating Count': 203,
  'Image URL': 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png'},
 {'Product ID': 10,
  'Title': 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s',
  'Price': 109,
  'Category': 'electronics',
  'Description': 'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)',
  'Rating': 2.9,
  'Rating Count': 470,
  'Image URL': 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png'},
 {'Product ID': 11,
  'Title': 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5',
  'Price': 109,
  'Category': 'electronics',
  'Description': '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.',
  'Rating': 4.8,
  'Rating Count': 319,
  'Image URL': 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png'},
 {'Product ID': 12,
  'Title': 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive',
  'Price': 114,
  'Category': 'electronics',
  'Description': "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
  'Rating': 4.8,
  'Rating Count': 400,
  'Image URL': 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png'},
 {'Product ID': 13,
  'Title': 'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin',
  'Price': 599,
  'Category': 'electronics',
  'Description': '21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz',
  'Rating': 2.9,
  'Rating Count': 250,
  'Image URL': 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png'},
 {'Product ID': 14,
  'Title': 'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ',
  'Price': 999.99,
  'Category': 'electronics',
  'Description': '49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag',
  'Rating': 2.2,
  'Rating Count': 140,
  'Image URL': 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png'},
 {'Product ID': 15,
  'Title': "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
  'Price': 56.99,
  'Category': "women's clothing",
  'Description': 'Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',
  'Rating': 2.6,
  'Rating Count': 235,
  'Image URL': 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png'},
 {'Product ID': 16,
  'Title': "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
  'Price': 29.95,
  'Category': "women's clothing",
  'Description': '100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON',
  'Rating': 2.9,
  'Rating Count': 340,
  'Image URL': 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png'},
 {'Product ID': 17,
  'Title': 'Rain Jacket Women Windbreaker Striped Climbing Raincoats',
  'Price': 39.99,
  'Category': "women's clothing",
  'Description': "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
  'Rating': 3.8,
  'Rating Count': 679,
  'Image URL': 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png'},
 {'Product ID': 18,
  'Title': "MBJ Women's Solid Short Sleeve Boat Neck V ",
  'Price': 9.85,
  'Category': "women's clothing",
  'Description': '95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem',
  'Rating': 4.7,
  'Rating Count': 130,
  'Image URL': 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png'},
 {'Product ID': 19,
  'Title': "Opna Women's Short Sleeve Moisture",
  'Price': 7.95,
  'Category': "women's clothing",
  'Description': '100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort',
  'Rating': 4.5,
  'Rating Count': 146,
  'Image URL': 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png'},
 {'Product ID': 20,
  'Title': 'DANVOUY Womens T Shirt Casual Cotton Short',
  'Price': 12.99,
  'Category': "women's clothing",
  'Description': '95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.',
  'Rating': 3.6,
  'Rating Count': 145,
  'Image URL': 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_t.png'}]

## Convert to Pandas DataFrame
Transform the structured data into a DataFrame for analysis.

In [11]:
df =pd.DataFrame(data)
df

,id,title,price,description,category,image,rating
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,"{'rate': 3.9, 'count': 120}"
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,"{'rate': 4.1, 'count': 259}"
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,"{'rate': 4.7, 'count': 500}"
3,4,Mens Casual Slim Fit,15.99,The color could be slightly different between ...,men's clothing,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,"{'rate': 2.1, 'count': 430}"
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,"From our Legends Collection, the Naga was insp...",jewelery,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,"{'rate': 4.6, 'count': 400}"
5,6,Solid Gold Petite Micropave,168.00,Satisfaction Guaranteed. Return or exchange an...,jewelery,https://fakestoreapi.com/img/61sbMiUnoGL._AC_U...,"{'rate': 3.9, 'count': 70}"
6,7,White Gold Plated Princess,9.99,Classic Created Wedding Engagement Solitaire D...,jewelery,https://fakestoreapi.com/img/71YAIFU48IL._AC_U...,"{'rate': 3, 'count': 400}"
7,8,Pierced Owl Rose Gold Plated Stainless Steel D...,10.99,Rose Gold Plated Double Flared Tunnel Plug Ear...,jewelery,https://fakestoreapi.com/img/51UDEzMJVpL._AC_U...,"{'rate': 1.9, 'count': 100}"
8,9,WD 2TB Elements Portable External Hard Drive -...,64.00,USB 3.0 and USB 2.0 Compatibility Fast data tr...,electronics,https://fakestoreapi.com/img/61IBBVJvSDL._AC_S...,"{'rate': 3.3, 'count': 203}"
9,10,SanDisk SSD PLUS 1TB Internal SSD - SATA III 6...,109.00,"Easy upgrade for faster boot up, shutdown, app...",electronics,https://fakestoreapi.com/img/61U7T1koQqL._AC_S...,"{'rate': 2.9, 'count': 470}"
10,11,Silicon Power 256GB SSD 3D NAND A55 SLC Cache ...,109.00,3D NAND flash are applied to deliver high tran...,electronics,https://fakestoreapi.com/img/71kWymZ+c+L._AC_S...,"{'rate': 4.8, 'count': 319}"
11,12,WD 4TB Gaming Drive Works with Playstation 4 P...,114.00,"Expand your PS4 gaming experience, Play anywhe...",electronics,https://fakestoreapi.com/img/61mtL65D4cL._AC_S...,"{'rate': 4.8, 'count': 400}"
12,13,Acer SB220Q bi 21.5 inches Full HD (1920 x 108...,599.00,21. 5 inches Full HD (1920 x 1080) widescreen ...,electronics,https://fakestoreapi.com/img/81QpkIctqPL._AC_S...,"{'rate': 2.9, 'count': 250}"
13,14,Samsung 49-Inch CHG90 144Hz Curved Gaming Moni...,999.99,49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MON...,electronics,https://fakestoreapi.com/img/81Zt42ioCgL._AC_S...,"{'rate': 2.2, 'count': 140}"
14,15,BIYLACLESEN Women's 3-in-1 Snowboard Jacket Wi...,56.99,"Note:The Jackets is US standard size, Please c...",women's clothing,https://fakestoreapi.com/img/51Y5NI-I5jL._AC_U...,"{'rate': 2.6, 'count': 235}"
15,16,Lock and Love Women's Removable Hooded Faux Le...,29.95,100% POLYURETHANE(shell) 100% POLYESTER(lining...,women's clothing,https://fakestoreapi.com/img/81XH0e8fefL._AC_U...,"{'rate': 2.9, 'count': 340}"
16,17,Rain Jacket Women Windbreaker Striped Climbing...,39.99,Lightweight perfet for trip or casual wear---L...,women's clothing,https://fakestoreapi.com/img/71HblAHs5xL._AC_U...,"{'rate': 3.8, 'count': 679}"
17,18,MBJ Women's Solid Short Sleeve Boat Neck V,9.85,"95% RAYON 5% SPANDEX, Made in USA or Imported,...",women's clothing,https://fakestoreapi.com/img/71z3kpMAYsL._AC_U...,"{'rate': 4.7, 'count': 130}"
18,19,Opna Women's Short Sleeve Moisture,7.95,"100% Polyester, Machine wash, 100% cationic po...",women's clothing,https://fakestoreapi.com/img/51eg55uWmdL._AC_U...,"{'rate': 4.5, 'count': 146}"
19,20,DANVOUY Womens T Shirt Casual Cotton Short,12.99,"95%Cotton,5%Spandex, Features: Casual, Short S...",women's clothing,https://fakestoreapi.com/img/61pHAEJ4NML._AC_U...,"{'rate': 3.6, 'count': 145}"

## Preview Product Dataset
Display the first few rows of the processed dataset.

In [12]:
df.head()

,id,title,price,description,category,image,rating
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,"{'rate': 3.9, 'count': 120}"
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,"{'rate': 4.1, 'count': 259}"
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,"{'rate': 4.7, 'count': 500}"
3,4,Mens Casual Slim Fit,15.99,The color could be slightly different between ...,men's clothing,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,"{'rate': 2.1, 'count': 430}"
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,"From our Legends Collection, the Naga was insp...",jewelery,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,"{'rate': 4.6, 'count': 400}"

## Export Dataset
Save the processed product dataset as a CSV file for future use.

In [13]:
df.to_csv("fake_store_products.csv", index=False)

print("Dataset exported successfully!")

Dataset exported successfully!